const fs = require('fs');
const path = require('path');

// Generador de ejercicios para FASE 3: Biblioteca Metodológica Profesional v1.0
// 60 ejercicios complementarios altamente detallados y metodológicamente estructurados

const exercises = [
  // ==========================================
  // U6 / Querubín (5 nuevos -> total 10)
  // ==========================================
  {
    nombre: "Los Caza-Tesoros en la Jungla",
    tipo: "circuito",
    familia: "TÉCNICA",
    descripcion: "Juego lúdico de exploración motriz y familiarización con el balón. Los jugadores son exploradores que deben recoger 'tesoros' (conos de colores) conduciendo el balón sin chocar contra las 'rocas' (picas/vallas).",
    organizacion: "Espacio de 15x15m delimitado por líneas claras. Conos de distintos colores repartidos por el suelo.",
    distribucion_inicial: "Cada niño con un balón en sus pies en la zona central.",
    desarrollo: "A la señal del entrenador ('¡A explorar!'), los jugadores conducen su balón con toques cortos. Cuando el entrenador grita un color ('¡Oro amarillo!'), deben conducir hasta un cono amarillo, pisar el balón encima y gritar '¡Tesoro!'.",
    rotaciones: "Continuo sin paradas prolongadas. Duración en bloques de 3 minutos con pausas cortas.",
    reglas: "No se puede tocar el balón con las manos. El balón siempre debe estar a menos de un paso del pie.",
    puntuacion: "Cada cono alcanzado correctamente suma 1 punto simbólico.",
    intervenciones: "Estimular el uso de ambas piernas: '¿Podemos frenar con el pie izquierdo ahora?'. Felicitar cada intento.",
    correcciones: "Animar a levantar la vista para no chocar con otros compañeros. Toques suaves.",
    objetivo_tecnico: ["conducción", "control"],
    objetivo_tactico: ["orientación", "percepción"],
    categoria_edad: ["querubin"],
    age_category: "querubin",
    dificultad: 1,
    duracion_recomendada: 10,
    min_players: 6,
    max_players: 12,
    material: ["balones", "conos de colores", "petos"],
    variantes: [
      "Variante 1: Cambiar de ritmo cuando el entrenador toque las palmas.",
      "Variante 2: Conducir solo con la suela hacia atrás cuando el entrenador diga '¡Peligro!'."
    ],
    tags: ["u6", "lúdico", "conducción", "psicomotricidad"],
    bloque_sesion: "calentamiento",
    carga_fisica: 2,
    carga_cognitiva: 1,
    oposicion: 1,
    representatividad: 1,
    intensity_level: 2,
    game_phase: "attacking_build_up",
    drill_structure: "circuito",
    espacio: "15x15m",
    criterios_exito: ["Mantener el balón controlado cerca del pie", "No chocar con compañeros ni obstáculos"],
    progresion_descripcion: "Añadir al entrenador como 'monstruo dormilón' que despierta y camina lentamente obligando a esquivarlo.",
    regresion_descripcion: "Aumentar el espacio a 20x20m y reducir la cantidad de conos para mayor libertad motriz.",
    fuente: "Metodología propia"
  },
  {
    nombre: "1v1 a Porterías Mágicas de Colores",
    tipo: "SSG",
    familia: "TÉCNICA",
    descripcion: "Duelo 1v1 adaptado a iniciación con 4 miniporterías de conos de diferentes colores.",
    organizacion: "Cuadrado de 12x12m con 4 miniporterías formadas por conos de colores en cada esquina.",
    distribucion_inicial: "1 atacante con balón en el centro y 1 defensor frente a él a 3 metros.",
    desarrollo: "El entrenador nombra un color ('¡Rojo!'). El atacante debe intentar conducir o driblar hacia esa portería y pasar entre los conos.",
    rotaciones: "Cambio de roles atacante-defensor tras cada acción o cada 45 segundos.",
    reglas: "Gol válido solo si el balón cruza los conos por abajo y sin tocar las manos.",
    puntuacion: "1 punto por gol en la portería indicada.",
    intervenciones: "Preguntar al atacante: '¿Dónde está el espacio libre si el defensor te tapa la derecha?'.",
    correcciones: "Fomentar el cambio de dirección con fintas sencillas.",
    objetivo_tecnico: ["regate", "conducción"],
    objetivo_tactico: ["1v1 ofensivo", "toma de decisión"],
    categoria_edad: ["querubin"],
    age_category: "querubin",
    dificultad: 1,
    duracion_recomendada: 12,
    min_players: 4,
    max_players: 8,
    material: ["balones", "conos", "petos"],
    variantes: [
      "Variante 1: El atacante puede elegir cualquiera de las 2 porterías del fondo.",
      "Variante 2: Si el defensor recupera, puede marcar en las porterías contrarias."
    ],
    tags: ["u6", "1v1", "regate", "duelos"],
    bloque_sesion: "principal",
    carga_fisica: 2,
    carga_cognitiva: 2,
    oposicion: 2,
    representatividad: 2,
    intensity_level: 2,
    game_phase: "attacking_build_up",
    drill_structure: "SSG",
    espacio: "12x12m",
    criterios_exito: ["Cambiar de dirección ante la oposición", "Proteger el balón con el cuerpo"],
    progresion_descripcion: "Añadir una segunda opción de portería libre para obligar a fintas de engaño.",
    regresion_descripcion: "El defensor solo puede defender a paso caminando (oposición pasiva).",
    fuente: "UEFA Grassroots Guide"
  },
  {
    nombre: "El Semáforo Loco con Balón",
    tipo: "analitico",
    familia: "COGNITIVO",
    descripcion: "Ejercicio de frenadas, aceleraciones y percepción visual con balón en los pies.",
    organizacion: "Pasillo de 15x10m con línea de salida y línea de meta.",
    distribucion_inicial: "Todos los jugadores en línea con un balón cada uno. Entrenador en la meta de espaldas o con petos de colores.",
    desarrollo: "Verde: conducir rápido hacia adelante. Ámbar: conducir muy despacio pisando balón. Rojo: pisar balón y quedarse como estatuas.",
    rotaciones: "Los que llegan a la meta vuelven conduciendo por fuera y reinician.",
    reglas: "Si te mueves en rojo o se escapa el balón, debes dar 3 toques con la suela en el sitio antes de continuar.",
    puntuacion: "Llegar a la meta sin cometer fallos otorga 'estrella mágica'.",
    intervenciones: "Reforzar la atención visual: el entrenador muestra petos en vez de hablar.",
    correcciones: "No mirar solo al suelo; alternar mirada entre balón y entrenador.",
    objetivo_tecnico: ["control", "conducción"],
    objetivo_tactico: ["percepción", "atención"],
    categoria_edad: ["querubin"],
    age_category: "querubin",
    dificultad: 1,
    duracion_recomendada: 8,
    min_players: 6,
    max_players: 12,
    material: ["balones", "petos verde/amarillo/rojo"],
    variantes: [
      "Variante 1: Estímulo puramente visual sin voz.",
      "Variante 2: Azul significa sentarse sobre el balón."
    ],
    tags: ["u6", "percepción", "frenadas", "control"],
    bloque_sesion: "calentamiento",
    carga_fisica: 2,
    carga_cognitiva: 2,
    oposicion: 1,
    representatividad: 1,
    intensity_level: 2,
    game_phase: "attacking_build_up",
    drill_structure: "analítico",
    espacio: "15x10m",
    criterios_exito: ["Frenar el balón en seco a la primera señal", "Levantar la cabeza al conducir"],
    progresion_descripcion: "Cambio de estímulos invertidos: verde es parar, rojo es correr.",
    regresion_descripcion: "Avisar verbalmente con 2 segundos de antelación antes de mostrar el color.",
    fuente: "FIFA Training Centre"
  },
  {
    nombre: "2v2 Mini-Mundial con Porterías Anchas",
    tipo: "SSG",
    familia: "TÁCTICA OFENSIVA",
    descripcion: "Partido reducido 2v2 donde se premia el juego en equipo básico y el pase al compañero libre.",
    organizacion: "Campo de 16x12m con 2 porterías de 3 metros de ancho sin portero.",
    distribucion_inicial: "Parejas formadas, 2 equipos en campo y el resto esperando para entrar rápido.",
    desarrollo: "Partidos de 1 minuto y medio o primer gol. Balón en juego continuo introducido por el entrenador.",
    rotaciones: "El equipo que marca se queda; si empatan entran los dos siguientes equipos.",
    reglas: "No vale quedarse parado delante de la portería (evitar portero estático).",
    puntuacion: "1 punto por gol.",
    intervenciones: "Incentivar: '¡Busca a tu amigo si tienes a un rival delante!'.",
    correcciones: "Animar al compañero sin balón a separarse para recibir.",
    objetivo_tecnico: ["pase", "golpeo"],
    objetivo_tactico: ["apoyo", "cooperación"],
    categoria_edad: ["querubin"],
    age_category: "querubin",
    dificultad: 1,
    duracion_recomendada: 12,
    min_players: 6,
    max_players: 12,
    material: ["balones", "porterías plegables / conos", "petos"],
    variantes: [
      "Variante 1: Si el gol viene de un pase entre los dos compañeros, vale doble.",
      "Variante 2: Saques de banda realizados conduciendo el balón."
    ],
    tags: ["u6", "2v2", "partido reducido", "apoyo"],
    bloque_sesion: "global",
    carga_fisica: 3,
    carga_cognitiva: 2,
    oposicion: 3,
    representatividad: 4,
    intensity_level: 3,
    game_phase: "attacking_build_up",
    drill_structure: "SSG",
    espacio: "16x12m",
    criterios_exito: ["Buscar al compañero desmarcado", "Finalizar hacia portería con decisión"],
    progresion_descripcion: "Porterías más reducidas de 1.5 metros para exigir mayor precisión.",
    regresion_descripcion: "Añadir 1 comodín neutral de apoyo que juega siempre con el equipo con balón.",
    fuente: "Adaptación metodológica"
  },
  {
    nombre: "Circuito Psicomotriz 'El Río y los Puentes'",
    tipo: "circuito",
    familia: "FÍSICO",
    descripcion: "Circuito de habilidades motrices básicas: saltos en aros, zigzag entre picas y conducción con tiro final.",
    organizacion: "Posta de 4 estaciones: 1) Aros en el suelo, 2) Zigzag picas, 3) Conducción en curva, 4) Golpeo a portería.",
    distribucion_inicial: "Fila de 3-4 niños por posta para garantizar fluidez sin tiempos muertos.",
    desarrollo: "Saltar con pies juntos en aros, rodear las picas trotando, coger balón, conducir 5 metros y disparar a la portería.",
    rotaciones: "Recoger balón y colocarse al final de la fila contraria.",
    reglas: "No derribar las picas. Disparar antes de la línea delimitada.",
    puntuacion: "Celebrar cada gol con chocar de manos.",
    intervenciones: "Guiar la pisada y el equilibrio corporal.",
    correcciones: "Ajustar la fuerza del golpeo al llegar a la zona de tiro.",
    objetivo_tecnico: ["golpeo", "conducción"],
    objetivo_tactico: ["orientación"],
    categoria_edad: ["querubin"],
    age_category: "querubin",
    dificultad: 1,
    duracion_recomendada: 10,
    min_players: 6,
    max_players: 12,
    material: ["aros", "picas", "balones", "conos"],
    variantes: [
      "Variante 1: Salto a la pata coja en los aros.",
      "Variante 2: Golpeo obligatorio con pierna no dominante."
    ],
    tags: ["u6", "psicomotricidad", "coordinación", "tiro"],
    bloque_sesion: "principal",
    carga_fisica: 2,
    carga_cognitiva: 1,
    oposicion: 1,
    representatividad: 1,
    intensity_level: 2,
    game_phase: "attacking_build_up",
    drill_structure: "circuito",
    espacio: "20x15m",
    criterios_exito: ["Coordinar carrera y salto previo a la acción de balón", "Tiro orientado entre los tres palos"],
    progresion_descripcion: "Añadir un defensor pasivo que sale al mismo tiempo desde el lateral para generar ligera presión visual.",
    regresion_descripcion: "Acercar la línea de tiro a 3 metros de la portería.",
    fuente: "YouCoach"
  },

  // ==========================================
  // U7-U8 / Prebenjamín (5 nuevos -> total 10)
  // ==========================================
  {
    nombre: "Rondo 3v1 en Cuadrado de Habilidades",
    tipo: "rondo",
    familia: "TÁCTICA OFENSIVA",
    descripcion: "Rondo de iniciación 3v1 para afianzar el concepto de pase de seguridad y creación de líneas de pase.",
    organizacion: "Cuadrado de 8x8m delimitado con conos.",
    distribucion_inicial: "3 atacantes en tres lados del cuadrado y 1 defensor dentro buscando robar.",
    desarrollo: "Los 3 atacantes mantienen la posesión pasando el balón por fuera o dentro. El jugador sin balón debe moverse al lado libre para ofrecer apoyo constante.",
    rotaciones: "Si el defensor intercepta o toca el balón, intercambia posición con quien falló el pase.",
    reglas: "Máximo 3 toques por jugador. No se puede pasar por encima de la altura de la cintura.",
    puntuacion: "6 pases consecutivos suman 1 punto para los poseedores.",
    intervenciones: "Incidir en el concepto del lado libre: 'Si Juan tiene el balón, ¿a qué lado debes correr para ayudarle?'.",
    correcciones: "Perfil del cuerpo orientado hacia ambos compañeros. Evitar quedarse estático en un vértice.",
    objetivo_tecnico: ["pase", "control orientado"],
    objetivo_tactico: ["apoyo", "creación de espacios"],
    categoria_edad: ["prebenjamin"],
    age_category: "prebenjamin",
    dificultad: 2,
    duracion_recomendada: 12,
    min_players: 4,
    max_players: 8,
    material: ["balones", "conos", "petos"],
    variantes: [
      "Variante 1: Limitar a 2 toques obligatorios (control y pase).",
      "Variante 2: Si el defensor roba, debe conducir fuera del cuadrado para confirmar el robo."
    ],
    tags: ["u8", "rondo", "3v1", "pase", "apoyo"],
    bloque_sesion: "principal",
    carga_fisica: 2,
    carga_cognitiva: 2,
    oposicion: 2,
    representatividad: 3,
    intensity_level: 2,
    game_phase: "attacking_build_up",
    drill_structure: "rondo",
    espacio: "8x8m",
    criterios_exito: ["Movimiento al lado libre antes de que llegue el balón", "Precisión y tensión en el pase"],
    progresion_descripcion: "Reducir el espacio a 6x6m y limitar a 2 toques.",
    regresion_descripcion: "Agrandar a 10x10m y permitir toques ilimitados para dar tiempo de decisión.",
    fuente: "UEFA Grassroots Guide"
  },
  {
    nombre: "Oleadas 2v1 con Transición Rápida a Miniporterías",
    tipo: "SSG",
    familia: "TRANSICIONES",
    descripcion: "Tarea continua de 2 atacantes contra 1 defensor. Al finalizar o robar, el defensor inicia nuevo ataque con su pareja.",
    organizacion: "Campo de 20x15m con 1 portería reglamentaria en un extremo y 2 miniporterías en el opuesto.",
    distribucion_inicial: "2 atacantes salen desde mediocampo, 1 defensor espera en zona de área.",
    desarrollo: "Los 2 atacantes buscan progresar y finalizar. Si el defensor roba, debe conectar pase a cualquiera de las dos miniporterías.",
    rotaciones: "El atacante que finaliza o pierde el balón pasa a ser el próximo defensor; entran dos nuevos atacantes por el fondo.",
    reglas: "Ataque rápido: máximo 8 segundos para finalizar.",
    puntuacion: "1 punto por gol atacante, 2 puntos si el defensor recupera y marca en miniportería.",
    intervenciones: "Fijar al defensor: 'Conduce hacia el defensor para obligarle a decidir antes de pasar a tu compañero'.",
    correcciones: "Desmarque en diagonal del segundo atacante para no meterse en fuera de juego ni encimarse.",
    objetivo_tecnico: ["conducción", "pase", "finalización"],
    objetivo_tactico: ["superioridad", "transición defensa-ataque", "fijar y dividir"],
    categoria_edad: ["prebenjamin"],
    age_category: "prebenjamin",
    dificultad: 2,
    duracion_recomendada: 15,
    min_players: 6,
    max_players: 12,
    material: ["balones", "conos", "porterías", "petos"],
    variantes: [
      "Variante 1: Incorporación de un segundo defensor si el ataque tarda más de 5 segundos.",
      "Variante 2: Obligatorio que los dos atacantes toquen el balón antes del tiro."
    ],
    tags: ["u8", "2v1", "oleadas", "transiciones", "superioridad"],
    bloque_sesion: "principal",
    carga_fisica: 3,
    carga_cognitiva: 3,
    oposicion: 2,
    representatividad: 3,
    intensity_level: 3,
    game_phase: "attacking_build_up",
    drill_structure: "SSG",
    espacio: "20x15m",
    criterios_exito: ["Fijar al defensor mediante conducción antes de soltar el balón", "Finalización rápida y precisa"],
    progresion_descripcion: "Evolución a 2v2 con incorporación retrasada del segundo defensor.",
    regresion_descripcion: "Defensor con limitación de no salir de su zona de 5 metros delante de portería.",
    fuente: "MBP School of Coaches"
  },
  {
    nombre: "Circuito de Pase en Pared y Desmarque de Ruptura",
    tipo: "analitico",
    familia: "TÉCNICA",
    descripcion: "Estructura en Y para automatizar el pase, la devolución de primera (pared) y la aceleración al espacio.",
    organizacion: "Postas triangulares separadas a 8 metros con muñecos/picas como defensores simulados.",
    distribucion_inicial: "3 posiciones: A (pasador inicial), B (apoyo que devuelve de cara), C (receptor que rompe al espacio).",
    desarrollo: "A pasa a B. B devuelve de cara al espacio hacia la carrera de A. A filtra pase profundo para la entrada de C que finaliza a puerta.",
    rotaciones: "A pasa a la posición de B, B a la de C, y C recoge balón y va a la fila de A.",
    reglas: "El pase de devolución debe ser al primer toque.",
    puntuacion: "Sumar número de tiros a portería logrados en 5 minutos.",
    intervenciones: "Sincronizar el pase con el desmarque: 'No salgas antes de que tu compañero levante la cabeza'.",
    correcciones: "Pase tenso con el interior del pie. Bajar el centro de gravedad al devolver.",
    objetivo_tecnico: ["pase", "control orientado", "finalización"],
    objetivo_tactico: ["desmarque", "movilidad"],
    categoria_edad: ["prebenjamin"],
    age_category: "prebenjamin",
    dificultad: 2,
    duracion_recomendada: 12,
    min_players: 6,
    max_players: 12,
    material: ["balones", "picas", "conos", "portería"],
    variantes: [
      "Variante 1: Realizar la pared por el perfil izquierdo.",
      "Variante 2: C debe realizar un control orientado con pierna exterior antes del remate."
    ],
    tags: ["u8", "pared", "pase", "desmarque", "tecnica"],
    bloque_sesion: "principal",
    carga_fisica: 2,
    carga_cognitiva: 2,
    oposicion: 1,
    representatividad: 2,
    intensity_level: 2,
    game_phase: "attacking_build_up",
    drill_structure: "analítico",
    espacio: "25x15m",
    criterios_exito: ["Precisión en la devolución de cara", "Coordinación temporal del desmarque"],
    progresion_descripcion: "Añadir un defensor activo en la posición de remate final.",
    regresion_descripcion: "Permitir 2 toques en el pase de devolución para facilitar el control.",
    fuente: "YouCoach"
  },
  {
    nombre: "Juego Reducido 3v3 con Zonas de Tiro Exclusivas",
    tipo: "SSG",
    familia: "TÁCTICA OFENSIVA",
    descripcion: "Partido en campo reducido dividido en 3 franjas. Solo se puede disparar si se penetra mediante pase o conducción en la zona de finalización.",
    organizacion: "Campo de 24x16m dividido en zona defensiva, zona de creación y zona de finalización.",
    distribucion_inicial: "3v3 en igualdad numérica con porterías pequeñas.",
    desarrollo: "Juego libre en zona de creación. Para marcar, un jugador debe recibir dentro de la zona de finalización tras un desmarque o entrar en conducción.",
    rotaciones: "Cambios de equipo cada 3 minutos.",
    reglas: "No se puede esperar plantado dentro de la zona de finalización antes del pase (evitar fuera de juego conceptual).",
    puntuacion: "Gol normal: 1 punto. Gol de primer toque tras desmarque: 2 puntos.",
    intervenciones: "Valorar el pase filtrado y la profundidad: 'Buscad el espacio a la espalda de la defensa'.",
    correcciones: "Vigilancia defensiva al perder el balón.",
    objetivo_tecnico: ["pase", "control orientado", "golpeo"],
    objetivo_tactico: ["profundidad", "desmarque", "amplitud"],
    categoria_edad: ["prebenjamin"],
    age_category: "prebenjamin",
    dificultad: 2,
    duracion_recomendada: 15,
    min_players: 6,
    max_players: 12,
    material: ["balones", "setas para marcar zonas", "porterías"],
    variantes: [
      "Variante 1: Máximo 3 toques por jugador.",
      "Variante 2: Se añade 1 comodín ofensivo que solo juega en la zona media."
    ],
    tags: ["u8", "3v3", "profundidad", "desmarque", "zonas"],
    bloque_sesion: "global",
    carga_fisica: 3,
    carga_cognitiva: 3,
    oposicion: 3,
    representatividad: 4,
    intensity_level: 3,
    game_phase: "attacking_build_up",
    drill_structure: "SSG",
    espacio: "24x16m",
    criterios_exito: ["Llegar a la zona de finalización con ventaja espacial", "Atacar el balón en carrera"],
    progresion_descripcion: "Defensor puede entrar en la zona de finalización para presionar al atacante.",
    regresion_descripcion: "El atacante tiene 3 segundos sin oposición dentro de la zona de finalización para disparar.",
    fuente: "FIFA Training Centre"
  },
  {
    nombre: "La Jaula del 1v1 Defensivo con Duelo de Espaldas",
    tipo: "analitico",
    familia: "TÁCTICA DEFENSIVA",
    descripcion: "Duelo 1v1 donde el atacante recibe de espaldas y el defensor debe temporizar sin cometer falta ni ser superado en giro.",
    organizacion: "Pasillo estrecho de 10x8m con 1 miniportería en la espalda del defensor.",
    distribucion_inicial: "Atacante situado en el centro de espaldas a portería; defensor pegado a 1 metro de distancia.",
    desarrollo: "El entrenador pasa el balón al atacante. El defensor debe orientar su perfil, no precipitarse y evitar que el atacante gire hacia portería.",
    rotaciones: "Intercambio continuo de atacante a defensor tras cada repetición.",
    reglas: "El defensor no puede meter la pierna a lo loco; debe esperar el fallo o orientar al atacante hacia fuera.",
    puntuacion: "Atacante marca = 1 punto. Defensor recupera o echa el balón fuera = 1 punto.",
    intervenciones: "Postura corporal defensiva: 'Piernas semiflexionadas, perfil lateral y brazos para medir distancia'.",
    correcciones: "No entrar al bulto cuando el atacante está protegido con el cuerpo.",
    objetivo_tecnico: ["protección", "regate"],
    objetivo_tactico: ["1v1 defensivo", "temporización"],
    categoria_edad: ["prebenjamin"],
    age_category: "prebenjamin",
    dificultad: 2,
    duracion_recomendada: 10,
    min_players: 4,
    max_players: 8,
    material: ["balones", "conos", "petos"],
    variantes: [
      "Variante 1: El atacante tiene 6 segundos para finalizar.",
      "Variante 2: Se añade una línea de pase lateral para descarga de emergencia."
    ],
    tags: ["u8", "1v1 defensivo", "temporización", "duelos"],
    bloque_sesion: "principal",
    carga_fisica: 3,
    carga_cognitiva: 2,
    oposicion: 3,
    representatividad: 3,
    intensity_level: 3,
    game_phase: "defending",
    drill_structure: "analítico",
    espacio: "10x8m",
    criterios_exito: ["Mantener la posición entre atacante y portería sin dejarse girar", "Temporizar hasta el momento óptimo de robo"],
    progresion_descripcion: "Aumentar el ancho del espacio a 12m para dar más posibilidades de regate al atacante.",
    regresion_descripcion: "El atacante debe dar obligatoriamente 2 toques antes de poder tirar.",
    fuente: "Adaptación metodológica"
  }
];

// Generar inserts SQL para el resto de categorías hasta completar los 60 ejercicios
const generateSql = () => {
  let sql = `-- 20260819_library_seed.sql\n-- FASE 3: 60 Ejercicios Profesionales Metodológicos U6 -> Senior\n\n`;

  // Plantilla de generación con datos reales estructurados
  const categoriesConfig = [
    // U9-U10 / Benjamín (10 ejercicios)
    { cat: 'benjamin', diff: 2, count: 10, prefix: 'Benjamín' },
    // U11-U12 / Alevín (10 ejercicios)
    { cat: 'alevin', diff: 2, count: 10, prefix: 'Alevín' },
    // U13-U14 / Infantil (10 ejercicios)
    { cat: 'infantil', diff: 3, count: 10, prefix: 'Infantil' },
    // U15-U16 / Cadete (10 ejercicios)
    { cat: 'cadete', diff: 3, count: 10, prefix: 'Cadete' },
    // U17-U19 / Juvenil (5 ejercicios)
    { cat: 'juvenil', diff: 4, count: 5, prefix: 'Juvenil' },
    // Senior (5 ejercicios)
    { cat: 'senior', diff: 4, count: 5, prefix: 'Senior' }
  ];

  // Ejercicios específicos por categoría
  const detailedExercises = [
    // U9-U10 Benjamín (10)
    {
      nombre: "Rondo 4v2 con Tercer Hombre y Cambio de Orientación",
      tipo: "rondo",
      familia: "TÁCTICA OFENSIVA",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["pase", "control orientado"],
      obj_tac: ["tercer hombre", "superioridad", "apoyo"],
      espacio: "12x12m",
      min_p: 6, max_p: 8, dur: 14,
      desc: "Rondo 4v2 donde 4 atacantes exteriores buscan circular el balón. Si conectan con el compañero opuesto a través de un pase intermedio (tercer hombre), suman puntuación especial.",
      desarrollo: "Los 4 atacantes se sitúan en los 4 lados del cuadrado. 2 defensores dentro buscan cortar las líneas de pase.",
      variantes: ["Variante 1: Toques limitados a 2 por jugador.", "Variante 2: Si el defensor roba, intenta salir conduciendo fuera del cuadrado."],
      prog: "Reducir a 10x10m y limitar a 1 toque en pase de devolución.",
      reg: "Aumentar espacio a 14x14m y permitir toques libres al poseedor inicial.",
      criterios: ["Identificar al tercer hombre libre", "Orientar el control hacia el siguiente receptor"],
      carga_f: 2, carga_c: 3, op: 2, rep: 3, int: 3, phase: "attacking_build_up", drill: "rondo", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Juego de Posición 3v3 + 2 Comodines Exteriores",
      tipo: "juego_medio",
      familia: "TÁCTICA OFENSIVA",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["control orientado", "pase"],
      obj_tac: ["amplitud", "progresión", "creación de espacios"],
      espacio: "20x15m",
      min_p: 8, max_p: 10, dur: 15,
      desc: "Estructura de posesión y progresión donde 3 jugadores por dentro juegan apoyados por 2 comodines exteriores en las bandas para dar amplitud.",
      desarrollo: "Equipo con balón busca enlazar 6 pases o conectar de comodín a comodín sin que el equipo rival intercepte.",
      variantes: ["Variante 1: Comodines juegan a 1 toque.", "Variante 2: Gol si tras pase de comodín se finaliza en miniportería."],
      prog: "Comodines pueden ser presionados por 1 defensor que salga de zona interior.",
      reg: "Se añade 1 comodín interior adicional para generar 4v3 dentro.",
      criterios: ["Uso correcto de la amplitud para ensanchar al rival", "Pase tenso a pie lejano"],
      carga_f: 3, carga_c: 3, op: 3, rep: 3, int: 3, phase: "attacking_build_up", drill: "juego_medio", fuente: "YouCoach"
    },
    {
      nombre: "SSG 4v4 con Porteros y Salida de Balón desde Meta",
      tipo: "SSG",
      familia: "TÁCTICA OFENSIVA",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "global",
      obj_tec: ["pase", "golpeo"],
      obj_tac: ["apoyo", "basculación", "salida de balón"],
      espacio: "30x20m",
      min_p: 10, max_p: 12, dur: 16,
      desc: "Partido reducido 4v4 + 2 porteros. Siempre que el balón sale, el reinicio se produce desde el portero en corto para trabajar la salida bajo presión moderada.",
      desarrollo: "Ambos equipos estructurados en 1-2-1. El equipo defensor no puede entrar al área rival hasta el primer pase del portero.",
      variantes: ["Variante 1: Gol tras combinación de 3 jugadores vale doble.", "Variante 2: Presión alta inmediata tras pérdida."],
      prog: "Defensa libre para presionar desde el saque de puerta sin esperar al primer toque.",
      reg: "Línea de presión retrasada a mitad de campo en salida de puerta.",
      criterios: ["Separación de los centrales para recibir con espacio", "Pared con el pivote interior"],
      carga_f: 3, carga_c: 3, op: 3, rep: 4, int: 3, phase: "attacking_build_up", drill: "SSG", fuente: "UEFA Training Ground"
    },
    {
      nombre: "Duelos 2v2 Continuos con Apoyo de Portero como Pivote",
      tipo: "SSG",
      familia: "TRANSICIONES",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["regate", "pase", "finalización"],
      obj_tac: ["1v1 ofensivo", "cooperación", "reacción tras pérdida"],
      espacio: "18x14m",
      min_p: 6, max_p: 10, dur: 12,
      desc: "Duelos intensos 2v2 donde el equipo en posesión puede apoyarse en su portero para descargar el juego y reiniciar ataque.",
      desarrollo: "Acciones de 45 segundos a máxima intensidad con descanso activo.",
      variantes: ["Variante 1: Portero solo puede jugar de primera.", "Variante 2: Tras recuperación, tiro directo antes de 4 segundos."],
      prog: "Reducir a 2 toques por jugador de campo.",
      reg: "Permitir al portero conducir hasta mediocampo como jugador libre.",
      criterios: ["Apoyo de emergencia al portero ante presión intensa", "Transición rápida tras pérdida"],
      carga_f: 4, carga_c: 3, op: 3, rep: 3, int: 4, phase: "attacking_build_up", drill: "SSG", fuente: "Adaptación metodológica"
    },
    {
      nombre: "Circuito de Pase en Rombo con Tercer Hombre y Golpeo",
      tipo: "analitico",
      familia: "TÉCNICA",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["pase", "control orientado", "finalización"],
      obj_tac: ["tercer hombre", "movilidad"],
      espacio: "20x20m",
      min_p: 8, max_p: 12, dur: 12,
      desc: "Estructura en rombo para mecanizar el pase vertical, pase de cara y pase al espacio con tiro final.",
      desarrollo: "Pivote pasa a media punta, media punta descarga de cara al interior, interior filtra al extremo que chuta.",
      variantes: ["Variante 1: Cambiar el sentido de la circulación hacia la banda contraria.", "Variante 2: Remate de cabeza tras centro."],
      prog: "Incorporar un defensor pasivo que intente tapar la línea de pase filtrado.",
      reg: "Distancias más cortas (12m) y permitir dos toques en todas las postas.",
      criterios: ["Tensión del pase raso", "Orientación corporal previa a la recepción"],
      carga_f: 2, carga_c: 2, op: 1, rep: 2, int: 2, phase: "attacking_build_up", drill: "circuito", fuente: "YouCoach"
    },
    {
      nombre: "Presión Tras Pérdida en Rondo 5v2 Doble Zona",
      tipo: "rondo",
      familia: "TRANSICIONES",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["pase", "interceptación"],
      obj_tac: ["presión tras pérdida", "reacción tras pérdida", "vigilancia"],
      espacio: "16x10m (dividido en 2 cuadrados de 8x8m)",
      min_p: 7, max_p: 9, dur: 14,
      desc: "5 atacantes juegan rondo contra 2 defensores en un cuadrado. Si los defensores tocan o roban, deben pasar el balón al cuadrado contiguo.",
      desarrollo: "Los atacantes deben reaccionar inmediatamente en menos de 3 segundos (Regla de los 3s) para ahogar la salida y evitar el pase al otro sector.",
      variantes: ["Variante 1: Si los 5 recuperan en menos de 3 segundos, suman 2 puntos.", "Variante 2: 1 defensor extra esperando en el otro cuadrado."],
      prog: "3 defensores activos en lugar de 2.",
      reg: "Defensores deben dar 2 pases entre ellos antes de poder enviar al otro cuadrado.",
      criterios: ["Acoso inmediato al poseedor tras pérdida", "Cierre de líneas de pase lejanas"],
      carga_f: 3, carga_c: 3, op: 3, rep: 3, int: 3, phase: "defending", drill: "rondo", fuente: "FIFA Training Centre"
    },
    {
      nombre: "Batalla de Coberturas Defensivas 2v2 en Pasillo Central",
      tipo: "SSG",
      familia: "TÁCTICA DEFENSIVA",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["entrada", "interceptación"],
      obj_tac: ["cobertura", "temporización", "1v1 defensivo"],
      espacio: "20x12m",
      min_p: 6, max_p: 8, dur: 12,
      desc: "Duelo de parejas donde se trabaja la coordinación entre el defensor que acosa al balón y el compañero que realiza la cobertura escalonada.",
      desarrollo: "Atacantes intentan rebasar la línea defensiva mediante pase o regate. Defensores deben mantener distancias de cobertura (escalonamiento defensivo).",
      variantes: ["Variante 1: Si el defensor de acoso es superado, el de cobertura debe frenar el avance.", "Variante 2: Obligación de orientar hacia la banda."],
      prog: "Añadir un atacante comodín por detrás para generar superioridad 3v2.",
      reg: "Atacantes limitados a conducir sin poder pasar el balón.",
      criterios: ["Posicionamiento en diagonal del hombre de cobertura", "Comunicación constante entre defensores"],
      carga_f: 3, carga_c: 3, op: 3, rep: 3, int: 3, phase: "defending", drill: "SSG", fuente: "UEFA Grassroots Guide"
    },
    {
      nombre: "Juego Global 5v5 con Cuatro Miniporterías en Esquinas",
      tipo: "juego_global",
      familia: "TÁCTICA OFENSIVA",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "global",
      obj_tec: ["pase", "control orientado", "golpeo"],
      obj_tac: ["amplitud", "cambio de orientación", "creación de espacios"],
      espacio: "35x25m",
      min_p: 10, max_p: 12, dur: 18,
      desc: "Partido 5v5 sin porteros pero con 4 miniporterías en cada esquina del campo. Favorece la alternancia del juego entre banda izquierda y derecha.",
      desarrollo: "Para marcar, se puede elegir cualquiera de las dos porterías de ataque. Si un lado está colapsado, se debe circular rápido al opuesto.",
      variantes: ["Variante 1: No se puede marcar en la misma portería dos veces seguidas.", "Variante 2: Gol tras cambio de orientación vale triple."],
      prog: "Reducir el tamaño de las porterías a 1 metro de ancho.",
      reg: "Añadir un comodín neutral que juegue con el equipo poseedor.",
      criterios: ["Detectar el lado débil del rival", "Pases de orientación precisos"],
      carga_f: 3, carga_c: 3, op: 3, rep: 4, int: 3, phase: "attacking_build_up", drill: "juego_global", fuente: "Adaptación metodológica"
    },
    {
      nombre: "Calentamiento Cognitivo: Rueda de Pases con Colores y Números",
      tipo: "calentamiento",
      familia: "COGNITIVO",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "calentamiento",
      obj_tec: ["pase", "control orientado"],
      obj_tac: ["percepción", "toma de decisión", "orientación"],
      espacio: "15x15m",
      min_p: 8, max_p: 12, dur: 10,
      desc: "Jugadores en parejas dentro de un espacio compartido con conos de 4 colores. Al recibir, deben decir en voz alta el color del cono más cercano antes de pasar a otra pareja.",
      desarrollo: "Circulación continua de 4 balones simultáneos. Atención dividida y escaneo visual permanente.",
      variantes: ["Variante 1: Pasar solo a compañeros con peto de color diferente.", "Variante 2: Realizar finta obligatoria previa al pase."],
      prog: "Introducir números y operaciones matemáticas sencillas antes del pase.",
      reg: "Reducir a 2 balones simultáneos para mayor tiempo de procesamiento.",
      criterios: ["Escaneo del entorno antes de recibir el balón", "Precisión y timing del pase"],
      carga_f: 2, carga_c: 3, op: 1, rep: 2, int: 2, phase: "attacking_build_up", drill: "calentamiento", fuente: "YouCoach"
    },
    {
      nombre: "Circuito de Coordinación y Agilidad con Finalización Tras Duelo",
      tipo: "circuito",
      familia: "FÍSICO",
      categoria: "benjamin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["golpeo", "regate"],
      obj_tac: ["velocidad", "aceleración", "1v1 ofensivo"],
      espacio: "20x15m",
      min_p: 6, max_p: 10, dur: 12,
      desc: "Posta de escaleras de coordinación y cambio de dirección explosivo hacia balón dividido para disputar un 1v1 rápido frente a portería.",
      desarrollo: "Dos jugadores salen a la vez por escaleras laterales paralelas. El entrenador lanza un balón al centro; quien llega primero ataca y el otro defiende.",
      variantes: ["Variante 1: Salida de espaldas a la señal sonora.", "Variante 2: Si el defensor recupera, puede marcar en miniportería lateral."],
      prog: "Balón enviado en trayectoria aérea o con bote para dificultar el control.",
      reg: "El atacante sale con 2 metros de ventaja sobre el defensor.",
      criterios: ["Velocidad de reacción al estímulo del balón", "Resolución contundente del duelo en área"],
      carga_f: 3, carga_c: 2, op: 3, rep: 3, int: 4, phase: "attacking_build_up", drill: "circuito", fuente: "FIFA Training Centre"
    },

    // U11-U12 Alevín (10 ejercicios)
    {
      nombre: "Juego de Posición 4v4 + 3 Comodines (Cruyff Positional)",
      tipo: "juego_medio",
      familia: "TÁCTICA OFENSIVA",
      categoria: "alevin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["control orientado", "pase"],
      obj_tac: ["tercer hombre", "superioridad", "perfil corporal", "amplitud"],
      espacio: "22x22m",
      min_p: 11, max_p: 14, dur: 18,
      desc: "Estructura posicional clásica 4v4 con 2 comodines exteriores y 1 comodín interior (eje). Búsqueda constante de fijar por fuera para encontrar al hombre libre por dentro.",
      desarrollo: "El equipo poseedor busca progresar apoyándose en el comodín central para liberar los lados opuestos.",
      variantes: ["Variante 1: Comodín central a 1 toque.", "Variante 2: Tras 8 pases, opción de pase profundo a zona delimitada."],
      prog: "Reducir a 18x18m con marcaje individual en zona interior.",
      reg: "Toques libres para los comodines exteriores.",
      criterios: ["Perfilación corporal orientada hacia el campo rival", "Pase tenso entre líneas"],
      carga_f: 3, carga_c: 4, op: 3, rep: 3, int: 3, phase: "attacking_build_up", drill: "juego_medio", fuente: "MBP School of Coaches"
    },
    {
      nombre: "SSG 6v6 con Dos Zonas de Creación y Finalización Rápida",
      tipo: "SSG",
      familia: "TÁCTICA OFENSIVA",
      categoria: "alevin",
      dificultad: 3,
      bloque: "global",
      obj_tec: ["pase", "control", "finalización"],
      obj_tac: ["progresión", "desmarque de ruptura", "vigilancia defensiva"],
      espacio: "40x28m",
      min_p: 12, max_p: 14, dur: 20,
      desc: "Campo dividido por línea de mediocampo. En campo propio se juega a 3 toques para asegurar salida limpia; en campo rival juego libre para favorecer desequilibrio individual.",
      desarrollo: "Estructura 1-2-2-1. Fomentar la llegada de jugadores de segunda línea al área rival.",
      variantes: ["Variante 1: Incorporación de 1 defensa al ataque para generar superioridad.", "Variante 2: Gol de primer toque vale doble."],
      prog: "Limitar a 10 segundos el tiempo para rematar una vez cruzado el mediocampo.",
      reg: "Toques libres en todo el terreno de juego.",
      criterios: ["Acelerar la jugada al superar la línea media", "Desmarques coordinados de ruptura y apoyo"],
      carga_f: 3, carga_c: 3, op: 3, rep: 4, int: 3, phase: "attacking_build_up", drill: "SSG", fuente: "YouCoach"
    },
    {
      nombre: "Transición 3v2 + 1 Defensor en Repliegue Rápido",
      tipo: "SSG",
      familia: "TRANSICIONES",
      categoria: "alevin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["conducción", "pase", "finalización"],
      obj_tac: ["contraataque", "superioridad", "temporización", "reorganización"],
      espacio: "30x20m",
      min_p: 8, max_p: 12, dur: 15,
      desc: "Ataque en superioridad 3v2 con salida a máxima velocidad. Un tercer defensor sale desde línea de fondo rival a la carrera intentando replegar y equilibrar el duelo.",
      desarrollo: "Los 3 atacantes tienen máximo 6 segundos para finalizar antes de que el defensor replegado forme el 3v3.",
      variantes: ["Variante 1: Si los 2 defensores roban, juegan directo con su portero.", "Variante 2: Atacantes obligados a finalizar dentro del área."],
      prog: "El defensor replegado sale 1 segundo antes.",
      reg: "El defensor replegado sale cuando el balón cruza el mediocampo.",
      criterios: ["Fijar al central libre mediante conducción rápida", "Finalizar antes de la llegada del defensor en repliegue"],
      carga_f: 4, carga_c: 3, op: 3, rep: 3, int: 4, phase: "attacking_build_up", drill: "SSG", fuente: "UEFA Training Ground"
    },
    {
      nombre: "Rondo de Presión 6v3 con Transición a Contraataque",
      tipo: "rondo",
      familia: "TRANSICIONES",
      categoria: "alevin",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["interceptación", "pase"],
      obj_tac: ["presión tras pérdida", "primera acción tras recuperación", "amplitud"],
      espacio: "16x16m",
      min_p: 9, max_p: 12, dur: 14,
      desc: "6 atacantes en perímetro frente a 3 defensores interiores. Si los 3 recuperan, deben conectar 3 pases rápidos entre ellos o pasar a portería pequeña exterior.",
      desarrollo: "Los 6 atacantes deben presionar inmediatamente tras la pérdida para no dejar salir el balón.",
      variantes: ["Variante 1: Máximo 2 toques para los 6 exteriores.", "Variante 2: Defensores tienen 5 segundos para marcar en miniportería."],
      prog: "Espacio reducido a 14x14m.",
      reg: "Solo 2 defensores dentro en lugar de 3.",
      criterios: ["Cierre de líneas interiores en pérdida", "Pase de seguridad inmediato tras recuperación"],
      carga_f: 3, carga_c: 3, op: 3, rep: 3, int: 3, phase: "defending", drill: "rondo", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Basculación y Bloque Medio 4v4 + 2 Apoyos en Amplitud",
      tipo: "juego_medio",
      familia: "TÁCTICA DEFENSIVA",
      categoria: "alevin",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["interceptación", "despeje"],
      obj_tac: ["basculación", "bloque", "vigilancia", "cobertura"],
      espacio: "28x22m",
      min_p: 10, max_p: 12, dur: 16,
      desc: "Línea de 4 defensores trabajando la basculación coordinada ante la circulación de balón del equipo rival apoyado por extremos abiertos.",
      desarrollo: "El equipo defensor no debe permitir pases que superen su línea media ni desajustes entre central y lateral.",
      variantes: ["Variante 1: Obligación de dejar libre el carril opuesto para concentrar el bloque.", "Variante 2: Presión al salto del lateral si el pase va a banda."],
      prog: "Atacantes incorporan un media punta entre líneas.",
      reg: "Atacantes juegan con toques ilimitados para permitir al bloque ajustarse con calma.",
      criterios: ["Distancia constante de 6-8m entre componentes de la línea defensiva", "Voz de mando del central"],
      carga_f: 3, carga_c: 3, op: 3, rep: 3, int: 3, phase: "defending", drill: "juego_medio", fuente: "FIFA Training Centre"
    },
    {
      nombre: "Juego Global 7v7 con Estructura de 3 Carriles Verticales",
      tipo: "juego_global",
      familia: "TÁCTICA OFENSIVA",
      categoria: "alevin",
      dificultad: 3,
      bloque: "global",
      obj_tec: ["pase", "control orientado", "centro", "finalización"],
      obj_tac: ["amplitud", "ocupación de espacios", "tercer hombre", "cambio de orientación"],
      espacio: "50x35m",
      min_p: 14, max_p: 16, dur: 22,
      desc: "Partido 7v7 en campo reglamentario de F8 delimitado en 3 carriles verticales (izquierdo, central y derecho). Obligación de ocupar los 3 carriles en ataque organizado.",
      desarrollo: "No puede haber más de 2 jugadores del mismo equipo en el carril exterior simultáneamente para evitar atascos.",
      variantes: ["Variante 1: Gol tras centro desde carril lateral vale doble.", "Variante 2: Prohibido dar más de 3 pases consecutivos en el mismo carril."],
      prog: "Defensa libre sin restricciones de carril.",
      reg: "Carriles exteriores exclusivos para atacantes sin oposición.",
      criterios: ["Circulación rápida de carril a carril para desorganizar al rival", "Llegada al área con ocupación de primer y segundo palo"],
      carga_f: 3, carga_c: 4, op: 3, rep: 4, int: 3, phase: "attacking_build_up", drill: "juego_global", fuente: "Adaptación metodológica"
    },
    {
      nombre: "Estrategia ABP: Córner Ofensivo con Bloqueo y Llegada al 2º Palo",
      tipo: "analitico",
      familia: "BALÓN PARADO",
      categoria: "alevin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["golpeo", "juego aéreo", "centro"],
      obj_tac: ["córner ofensivo", "creación de espacios", "anticipación"],
      espacio: "Medio campo",
      min_p: 10, max_p: 14, dur: 12,
      desc: "Mecanización de saque de esquina con movimiento de arrastre al primer palo y entrada limpia del rematador al segundo palo tras bloqueo ciego.",
      desarrollo: "Lanzador perfil zurdo/diestro según efecto. 3 jugadores atacan zonas preestablecidas (primer palo, punto de penalti, segundo palo) + 1 rechace.",
      variantes: ["Variante 1: Saque en corto 2v1 para mejorar ángulo de centro.", "Variante 2: Balón tenso raso al punto de penalti."],
      prog: "Añadir 5 defensores en marcaje mixto real.",
      reg: "Sin defensores para automatizar el timing de carrera de los rematadores.",
      criterios: ["Sincronización de la carrera con el golpeo del lanzador", "Ataque agresivo al balón en el punto más alto"],
      carga_f: 2, carga_c: 2, op: 2, rep: 3, int: 2, phase: "attacking_build_up", drill: "analítico", fuente: "YouCoach"
    },
    {
      nombre: "Circuito Técnico-Cognitivo de Toma de Decisión Bajo Fatiga",
      tipo: "circuito",
      familia: "COGNITIVO",
      categoria: "alevin",
      dificultad: 2,
      bloque: "calentamiento",
      obj_tec: ["control orientado", "pase"],
      obj_tac: ["toma de decisión", "percepción", "adaptabilidad"],
      espacio: "20x20m",
      min_p: 8, max_p: 12, dur: 12,
      desc: "Circuito que combina saltos pliométricos bajos y sprints cortos seguidos inmediatamente de un pase filtrado condicionado por la posición de un cono visual.",
      desarrollo: "El jugador realiza el esfuerzo físico, levanta la cabeza y debe elegir la puerta de pase libre antes de que pasen 2 segundos.",
      variantes: ["Variante 1: Estímulo acústico del entrenador al momento del golpeo.", "Variante 2: Golpeo exclusivo con pierna no hábil."],
      prog: "Reducir a 1 segundo el tiempo de lectura.",
      reg: "Realizar el pase sin fatiga física previa.",
      criterios: ["Mantener la calidad del pase a pesar de la frecuencia cardíaca elevada", "Lectura visual periférica"],
      carga_f: 3, carga_c: 3, op: 1, rep: 2, int: 3, phase: "attacking_build_up", drill: "circuito", fuente: "FIFA Training Centre"
    },
    {
      nombre: "Duelo 1v1 con Entrada Lateral y Protección Corporal",
      tipo: "analitico",
      familia: "TÉCNICA",
      categoria: "alevin",
      dificultad: 2,
      bloque: "principal",
      obj_tec: ["protección", "regate", "conducción"],
      obj_tac: ["1v1 ofensivo", "fuerza"],
      espacio: "15x10m",
      min_p: 6, max_p: 8, dur: 12,
      desc: "Atacante y defensor corren hombro con hombro hacia un balón frontal. Quien gana la posición debe proteger con el cuerpo alejando el balón del rival y girar hacia portería.",
      desarrollo: "Foco en interponer cadera y brazo legal para blindar el balón ante la carga del defensor.",
      variantes: ["Variante 1: Defensor sale medio metro por delante.", "Variante 2: Atacante puede apoyarse en un pasador neutro."],
      prog: "Tiempo límite de 5 segundos para rematar.",
      reg: "Defensor no puede meter cuerpo, solo seguir la trayectoria.",
      criterios: ["Interponer el tren inferior entre balón y adversario", "Uso del brazo de protección"],
      carga_f: 3, carga_c: 2, op: 3, rep: 3, int: 3, phase: "attacking_build_up", drill: "analítico", fuente: "UEFA Grassroots Guide"
    },
    {
      nombre: "Juego de Oleadas 3v2 + 2v1 Continuo de Alta Intensidad",
      tipo: "SSG",
      familia: "TRANSICIONES",
      categoria: "alevin",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["pase", "finalización"],
      obj_tac: ["contraataque", "superioridad", "reacción tras pérdida"],
      espacio: "35x25m",
      min_p: 10, max_p: 14, dur: 16,
      desc: "Oleadas sucesivas: equipo A ataca 3v2 a portería. Al finalizar, los 2 defensores se convierten en atacantes y reciben el balón de su portero para atacar 2v1 al extremo opuesto.",
      desarrollo: "Ritmo vertiginoso sin interrupciones. Cada oleada dura máximo 10 segundos.",
      variantes: ["Variante 1: Obligatorio finalizar con tiro antes del tercer pase.", "Variante 2: Incorporación de 1 jugador defensivo tras 4 segundos."],
      prog: "Evolución a 4v3 + 3v2.",
      reg: "Pausa de 15 segundos entre oleadas para reorganizar marcas.",
      criterios: ["Velocidad en la toma de decisión en superioridad", "Cambio de mentalidad ataque-defensa inmediato"],
      carga_f: 4, carga_c: 3, op: 3, rep: 4, int: 4, phase: "attacking_build_up", drill: "SSG", fuente: "Adaptación metodológica"
    },

    // U13-U14 Infantil (10 ejercicios)
    {
      nombre: "Salida de Balón 4v3 + Pivote Frente a Presión Alta",
      tipo: "juego_medio",
      familia: "TÁCTICA OFENSIVA",
      categoria: "infantil",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["pase", "control orientado"],
      obj_tac: ["salida de balón", "tercer hombre", "fijar y dividir", "perfil corporal"],
      espacio: "35x35m (primer tercio de campo)",
      min_p: 10, max_p: 12, dur: 18,
      desc: "Línea de 4 defensas + pivote contra 3 delanteros rivales que ejecutan presión alta organizada. Objetivo: superar la primera línea de presión y conectar con mini-porterías o extremos.",
      desarrollo: "Portero actúa como hombre libre. Centrales se abren al límite del área grande y pivote ofrece línea diagonal de pase.",
      variantes: ["Variante 1: Extremo rival salta al central exterior si el pase tarda.", "Variante 2: Salida con balón largo a caída de interior."],
      prog: "Presión rival 4v4 con marcaje al hombre sobre el pivote.",
      reg: "Presión pasiva de los 3 delanteros hasta el segundo pase.",
      criterios: ["Paciencia para atraer al rival y encontrar al hombre libre", "Pase tenso a la pierna alejada"],
      carga_f: 3, carga_c: 4, op: 3, rep: 4, int: 3, phase: "attacking_build_up", drill: "juego_medio", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Pressing Tras Pérdida en Cuadrantes Interconectados 4v4+2",
      tipo: "juego_medio",
      familia: "TRANSICIONES",
      categoria: "infantil",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["interceptación", "pase"],
      obj_tac: ["presión tras pérdida", "vigilancia", "reorganización", "densidad"],
      espacio: "24x24m dividido en 4 cuadrantes",
      min_p: 10, max_p: 12, dur: 16,
      desc: "Posesión en cuadrante activo. Al perder la posesión, el equipo debe acosar en el mismo cuadrante para recuperar en menos de 5 segundos antes de que el rival cambie de cuadrante.",
      desarrollo: "Si el rival logra enviar el balón a un cuadrante vacío, el equipo que perdió el balón debe replegar y ceder la iniciativa.",
      variantes: ["Variante 1: Recuperación en cuadrante inicial = 2 puntos.", "Variante 2: Máximo 2 toques por jugador."],
      prog: "Reducir el tiempo de recuperación a 3 segundos.",
      reg: "Cuadrantes más amplios (30x30m).",
      criterios: ["Intensidad en los 3 primeros pasos tras perder la posesión", "Cierre simultáneo del pase de seguridad"],
      carga_f: 4, carga_c: 4, op: 3, rep: 3, int: 4, phase: "defending", drill: "juego_medio", fuente: "UEFA Training Ground"
    },
    {
      nombre: "Juego de Posición 7v7 + 3 con Enfoque en Intervalos y Tercer Hombre",
      tipo: "juego_medio",
      familia: "TÁCTICA OFENSIVA",
      categoria: "infantil",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["control orientado", "pase"],
      obj_tac: ["tercer hombre", "superioridad", "progresión", "amplitud"],
      espacio: "40x35m",
      min_p: 16, max_p: 18, dur: 20,
      desc: "Estructura 7v7 con 3 comodines (2 laterales y 1 pivote central). Foco en filtrar balones en los intervalos entre lateral y central rival.",
      desarrollo: "Los poseedores buscan atraer por fuera para filtrar por dentro hacia el media punta que descarga al tercer hombre en carrera.",
      variantes: ["Variante 1: Gol tras pase filtrado al intervalo vale doble.", "Variante 2: Comodines exteriores a 2 toques."],
      prog: "Comodines interiores con marcaje individual asignado.",
      reg: "Se añade un cuarto comodín para generar superioridad numérica abrumadora.",
      criterios: ["Pase que rompe líneas defensivas", "Desmarque coordinado del tercer hombre"],
      carga_f: 3, carga_c: 4, op: 3, rep: 4, int: 3, phase: "attacking_build_up", drill: "juego_medio", fuente: "YouCoach"
    },
    {
      nombre: "SSG 5v5 + 2 Porteros con Ataque Rápido y Repliegue Intensivo",
      tipo: "SSG",
      familia: "TRANSICIONES",
      categoria: "infantil",
      dificultad: 3,
      bloque: "global",
      obj_tec: ["pase", "finalización", "interceptación"],
      obj_tac: ["contraataque", "ataque rápido", "reorganización", "defensa del área"],
      espacio: "45x30m",
      min_p: 12, max_p: 14, dur: 18,
      desc: "Partido reducido donde tras robo se premia finalizar en menos de 8 segundos. Si no se consigue, el equipo rival repliega en bloque bajo cerrando el carril central.",
      desarrollo: "Partidos de 4 minutos a intensidad máxima con alternancia de roles constante.",
      variantes: ["Variante 1: Gol de contraataque vale 2 puntos.", "Variante 2: No vale pase hacia atrás en los primeros 3 toques tras recuperación."],
      prog: "Reducir a 6 segundos el tiempo de finalización en contraataque.",
      reg: "Aumentar a 12 segundos el margen de ataque rápido.",
      criterios: ["Verticalidad inmediata del primer pase tras recuperar", "Ocupación de zonas de remate a alta velocidad"],
      carga_f: 4, carga_c: 3, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "SSG", fuente: "FIFA Training Centre"
    },
    {
      nombre: "Organización Defensiva de Línea de 4 ante Centros Laterales",
      tipo: "analitico",
      familia: "TÁCTICA DEFENSIVA",
      categoria: "infantil",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["despeje", "juego aéreo", "interceptación"],
      obj_tac: ["defensa del área", "vigilancia", "cobertura", "basculación"],
      espacio: "Área reglamentaria + 10 metros",
      min_p: 10, max_p: 14, dur: 15,
      desc: "Trabajo específico de la línea de 4 defensas + portero defendiendo centros laterales provenientes de banda izquierda y derecha con 3 rematadores atacando el área.",
      desarrollo: "Centrales perfilados cubriendo primer palo y punto de penalti; lateral opuesto cerrando segundo palo. Lateral de banda acosa el centro.",
      variantes: ["Variante 1: Incorporación de un jugador rival al rechace en la frontal.", "Variante 2: Centro raso tenso hacia atrás."],
      prog: "Añadir un cuarto atacante que llegue por sorpresa desde segunda línea.",
      reg: "Centros sin oposición en banda y solo 2 rematadores en el área.",
      criterios: ["Orientación corporal perfilada viendo balón y adversario", "Despeje orientado hacia las bandas"],
      carga_f: 3, carga_c: 3, op: 3, rep: 4, int: 3, phase: "defending", drill: "analítico", fuente: "UEFA Training Ground"
    },
    {
      nombre: "Juego Global 8v8 con Foco en Transiciones Ofensivas Rápidas",
      tipo: "juego_global",
      familia: "TÁCTICA OFENSIVA",
      categoria: "infantil",
      dificultad: 3,
      bloque: "global",
      obj_tec: ["pase", "conducción", "finalización"],
      obj_tac: ["contraataque", "profundidad", "desmarque de ruptura", "movilidad"],
      espacio: "65x45m",
      min_p: 16, max_p: 18, dur: 22,
      desc: "Partido 8v8 con dos porterías reglamentarias. El equipo que recupera en campo propio debe activar un desmarque de ruptura inmediato hacia el carril opuesto.",
      desarrollo: "Estructuras tácticas 1-3-3-1 vs 1-3-2-2. Fomentar la toma de decisión vertical antes del repliegue rival.",
      variantes: ["Variante 1: Si el pase supera 2 líneas rivales, cuenta como pase clave (+1 pto).", "Variante 2: Marcaje al hombre en salida de balón."],
      prog: "Limitar a 3 toques individuales en mediocampo.",
      reg: "Campo más reducido (55x40m) para facilitar las llegadas a portería.",
      criterios: ["Timing del desmarque al espacio libre", "Lectura del momento idóneo para el pase vertical"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "juego_global", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Circuito de Resistencia Específica con Duelos 1v1 + Tiro",
      tipo: "circuito",
      familia: "FÍSICO",
      categoria: "infantil",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["golpeo", "regate"],
      obj_tac: ["resistencia", "velocidad", "1v1 ofensivo"],
      espacio: "30x20m",
      min_p: 8, max_p: 12, dur: 15,
      desc: "Circuito intermitente de alta intensidad: sprint con cambio de dirección, salto de valla y duelo 1v1 en los últimos 15 metros contra portero.",
      desarrollo: "Series de 4 minutos (4 repeticiones por jugador) con descanso de 2 minutos.",
      variantes: ["Variante 1: El defensor inicia 2 metros por detrás en persecución.", "Variante 2: Finalización de volea tras centro."],
      prog: "Aumentar la distancia de sprint previo a 25 metros.",
      reg: "Eliminar el salto de valla previo al duelo.",
      criterios: ["Calidad de ejecución técnica en estado de fatiga", "Eficiencia en la finalización"],
      carga_f: 4, carga_c: 2, op: 3, rep: 3, int: 4, phase: "attacking_build_up", drill: "circuito", fuente: "YouCoach"
    },
    {
      nombre: "Estrategia ABP: Saque de Falta Lateral con Pantalla y Desvío",
      tipo: "analitico",
      familia: "BALÓN PARADO",
      categoria: "infantil",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["golpeo", "juego aéreo", "centro"],
      obj_tac: ["falta", "anticipación", "creación de espacios"],
      espacio: "Tres cuartos de campo",
      min_p: 12, max_p: 16, dur: 14,
      desc: "Falta lateral a 25 metros. Dos jugadores hacen pantalla al borde de la barrera para habilitar la entrada de un tercer jugador libre que peina al segundo palo.",
      desarrollo: "Señales codificadas del lanzador (brazo arriba / mano en cadera). 4 jugadores al remate coordinado.",
      variantes: ["Variante 1: Golpeo directo con rosca al palo corto si el portero da el paso en falso.", "Variante 2: Pase raso a la frontal para golpeo directo."],
      prog: "Oposición real con 6 defensores en marcaje zonal.",
      reg: "Sin defensores para calibrar trayectorias y tiempos de llegada.",
      criterios: ["Precisión del centro a la zona de conflicto", "Ocupación voraz del rechace defensivo"],
      carga_f: 2, carga_c: 3, op: 2, rep: 3, int: 2, phase: "attacking_build_up", drill: "analítico", fuente: "Adaptación metodológica"
    },
    {
      nombre: "Rondo de Posición 5v3 con Cambio de Ritmo Interior-Exterior",
      tipo: "rondo",
      familia: "TÁCTICA OFENSIVA",
      categoria: "infantil",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["pase", "control orientado"],
      obj_tac: ["movilidad", "tercer hombre", "percepción"],
      espacio: "15x15m",
      min_p: 8, max_p: 10, dur: 14,
      desc: "Rondo dinámico donde 4 exteriores y 1 interior juegan contra 3 defensores que presionan en triángulo.",
      desarrollo: "La consigna es jugar a 1 toque cuando el balón pasa por el interior y 2 toques en los exteriores para acelerar la circulación.",
      variantes: ["Variante 1: Obligatorio conectar con el interior cada 3 pases.", "Variante 2: Si los 3 defensores tocan balón 3 veces seguidas, cambio completo."],
      prog: "Reducir espacio a 12x12m.",
      reg: "Permitir 2 toques al jugador interior.",
      criterios: ["Orientación corporal del jugador interior", "Alternancia de juego corto y medio"],
      carga_f: 3, carga_c: 4, op: 3, rep: 3, int: 3, phase: "attacking_build_up", drill: "rondo", fuente: "FIFA Training Centre"
    },
    {
      nombre: "Duelo Táctico 3v3 en Rombo con Transiciones Continuas",
      tipo: "SSG",
      familia: "TÁCTICA OFENSIVA",
      categoria: "infantil",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["regate", "pase", "finalización"],
      obj_tac: ["apoyo", "desmarque", "1v1 defensivo", "reacción tras pérdida"],
      espacio: "22x18m",
      min_p: 6, max_p: 10, dur: 14,
      desc: "3v3 en espacio en forma de rombo. Cada equipo cuenta con 1 base, 2 alas y 1 punta alternándose. Máxima exigencia en coberturas y permutas.",
      desarrollo: "Juego continuo con balón siempre vivo. El gol solo es válido si el equipo atacante tiene a todos sus jugadores en campo rival.",
      variantes: ["Variante 1: Máximo 2 toques individuales.", "Variante 2: Si el defensor roba en campo rival, gol directo vale doble."],
      prog: "Añadir 1 comodín neutral para forzar situaciones de inferioridad al defender.",
      reg: "Juego a toques libres.",
      criterios: ["Ocupación equilibrada de la estructura en rombo", "Intensidad en los repliegues"],
      carga_f: 4, carga_c: 3, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "SSG", fuente: "MBP School of Coaches"
    },

    // U15-U16 Cadete (10 ejercicios)
    {
      nombre: "Pressing Alto y Bloqueo de Salida en Estructura 4-3-3",
      tipo: "juego_medio",
      familia: "TÁCTICA DEFENSIVA",
      categoria: "cadete",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["interceptación", "entrada"],
      obj_tac: ["presión", "basculación", "vigilancia", "temporización"],
      espacio: "50x45m",
      min_p: 14, max_p: 18, dur: 20,
      desc: "Entrenamiento del salto de presión de los 3 delanteros + interiores sobre la línea defensiva rival para forzar el robo en el último tercio de campo.",
      desarrollo: "Trigger de presión: cuando el balón viaja hacia el lateral rival o cuando el central realiza un control defectuoso hacia atrás.",
      variantes: ["Variante 1: Forzar el pase hacia dentro para embudo interior.", "Variante 2: Forzar el pase hacia fuera para encerrar en banda."],
      prog: "El equipo rival cuenta con mediocentro de primer nivel que busca zafarse de la marca.",
      reg: "El rival solo puede jugar en corto sin opciones de pase largo.",
      criterios: ["Sincronización en bloque de las tres líneas", "Acoso al receptor antes de que controle"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "defending", drill: "juego_medio", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Ataque Posicional 10v8 con Foco en Tercer Hombre y Llegada de Interiores",
      tipo: "juego_global",
      familia: "TÁCTICA OFENSIVA",
      categoria: "cadete",
      dificultad: 3,
      bloque: "global",
      obj_tec: ["pase", "control orientado", "centro", "finalización"],
      obj_tac: ["creación de espacios", "tercer hombre", "superioridad", "amplitud"],
      espacio: "Tres cuartos de campo (65x60m)",
      min_p: 18, max_p: 20, dur: 22,
      desc: "Simulación de ataque organizado contra un bloque medio-bajo 1-4-4-2. El equipo atacante (1-4-3-3) busca generar superioridades por dentro para activar a los extremos.",
      desarrollo: "Circulación de lado a lado con fijación de centrales para liberar el pase diagonal a la ruptura del interior a la espalda de los mediocentros.",
      variantes: ["Variante 1: Obligación de rematar antes de 5 pases en zona 3.", "Variante 2: Si la defensa roba, tiene 10 segundos para marcar en miniporterías."],
      prog: "Defensa con 9 jugadores (1-4-4-1) con presión más agresiva.",
      reg: "Defensa con 7 jugadores para dar mayor holgura a las combinaciones ofensivas.",
      criterios: ["Paciencia en la circulación previa a la aceleración", "Llegada contundente al área de 4 jugadores"],
      carga_f: 3, carga_c: 4, op: 4, rep: 4, int: 3, phase: "attacking_build_up", drill: "juego_global", fuente: "UEFA Training Ground"
    },
    {
      nombre: "Transición Ofensiva Explosiva Tras Recuperación en Bloque Medio",
      tipo: "SSG",
      familia: "TRANSICIONES",
      categoria: "cadete",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["conducción", "pase", "finalización"],
      obj_tac: ["contraataque", "ataque rápido", "primera acción tras recuperación"],
      espacio: "55x40m",
      min_p: 12, max_p: 16, dur: 18,
      desc: "Situación de 6v6 + porteros. El equipo defensor espera en bloque medio. Al recuperar, el primer pase debe ser vertical hacia el delantero de referencia en menos de 2 segundos.",
      desarrollo: "Extremos rompen en diagonal hacia los espacios intermedios para recibir la prolongación y definir ante el portero.",
      variantes: ["Variante 1: Máximo 3 toques para el jugador que realiza el primer pase.", "Variante 2: Obligación de rematar antes de que el rival repliegue."],
      prog: "Tiempo límite de 6 segundos para finalizar la jugada.",
      reg: "El rival solo puede replegar con 4 de sus 6 jugadores.",
      criterios: ["Calidad del primer pase tras recuperación (pase de seguridad o vertical)", "Velocidad de desmarque sin balón"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "SSG", fuente: "YouCoach"
    },
    {
      nombre: "Juego de Posición 6v6 + 3 con Cambio de Orientación y Amplitud",
      tipo: "juego_medio",
      familia: "TÁCTICA OFENSIVA",
      categoria: "cadete",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["pase", "control orientado"],
      obj_tac: ["cambio de orientación", "amplitud", "basculación", "tercer hombre"],
      espacio: "35x30m",
      min_p: 15, max_p: 16, dur: 18,
      desc: "Posesión 6v6 con 2 comodines exteriores fijos en bandas y 1 comodín interior. Búsqueda de atraer la presión al carril izquierdo para girar el juego al carril derecho en 2 toques.",
      desarrollo: "Se cuenta 1 punto por cada 10 pases y 2 puntos si el balón viaja de comodín exterior a comodín exterior en menos de 3 pases.",
      variantes: ["Variante 1: Comodines exteriores a 1 toque.", "Variante 2: Defensores pueden presionar a los comodines exteriores."],
      prog: "Reducir el ancho del espacio a 25 metros.",
      reg: "Toques libres para todos los jugadores.",
      criterios: ["Tensión del pase de cambio de orientación", "Movimiento de apoyo del comodín central"],
      carga_f: 3, carga_c: 4, op: 3, rep: 3, int: 3, phase: "attacking_build_up", drill: "juego_medio", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Defensa de la Última Línea: Fuera de Juego y Cobertura a la Espalda",
      tipo: "analitico",
      familia: "TÁCTICA DEFENSIVA",
      categoria: "cadete",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["interceptación", "despeje"],
      obj_tac: ["vigilancia", "cobertura", "bloque", "temporización"],
      espacio: "Medio campo defensivo",
      min_p: 10, max_p: 14, dur: 15,
      desc: "Coordinación de los 4 defensas ante lanzamientos en profundidad del mediocampo rival. Trabajo de achique hacia adelante (tirar la línea) o repliegue en carrera perfilada.",
      desarrollo: "Trigger de achique: balón no presionado = repliegue; balón presionado o de espaldas = achique hacia adelante.",
      variantes: ["Variante 1: Introducir 3 delanteros rivales que cruzan desmarques.", "Variante 2: Pase bombeado a la espalda del lateral."],
      prog: "Atacantes juegan con toques rápidos para dificultar la lectura del poseedor.",
      reg: "Lanzador avisa con voz el momento del golpeo.",
      criterios: ["Lectura unánime de poseedor con o sin tiempo/espacio", "Carrera de repliegue perfilada sin perder de vista el balón"],
      carga_f: 3, carga_c: 4, op: 3, rep: 4, int: 3, phase: "defending", drill: "analítico", fuente: "FIFA Training Centre"
    },
    {
      nombre: "SSG 7v7 + 2 Porteros con Zonas de Presión y Transición Vertiginosa",
      tipo: "SSG",
      familia: "TRANSICIONES",
      categoria: "cadete",
      dificultad: 3,
      bloque: "global",
      obj_tec: ["pase", "finalización", "regate"],
      obj_tac: ["presión tras pérdida", "contraataque", "superioridad", "densidad"],
      espacio: "55x40m dividido en 3 zonas",
      min_p: 14, max_p: 16, dur: 20,
      desc: "Partido 7v7 con regla de presión obligatoria en zona 1. Si el equipo recupera en zona 1, tiene superioridad automática de 4v2 para finalizar a portería.",
      desarrollo: "Estructuras tácticas flexibles. Máxima intensidad física y táctica durante bloques de 5 minutos.",
      variantes: ["Variante 1: Si no se finaliza en 8 segundos, el gol solo vale 1 punto.", "Variante 2: Todos los jugadores deben pasar de mediocampo para validar gol."],
      prog: "Máximo 2 toques para todos los jugadores de campo.",
      reg: "Zona 1 más amplia para facilitar la presión.",
      criterios: ["Presión agresiva pero sin cometer faltas tácticas absurdas", "Despliegue vertical fulgurante"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "SSG", fuente: "YouCoach"
    },
    {
      nombre: "Estrategia ABP: Córner Defensivo en Estructura Zonal Mixta",
      tipo: "analitico",
      familia: "BALÓN PARADO",
      categoria: "cadete",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["despeje", "juego aéreo"],
      obj_tac: ["córner defensivo", "vigilancia", "defensa del área", "primera acción tras recuperación"],
      espacio: "Área grande completa",
      min_p: 14, max_p: 18, dur: 15,
      desc: "Mecanización defensiva de saque de esquina: 5 jugadores en zona (primer palo, área pequeña central, segundo palo), 3 al hombre con los rematadores rivales más peligrosos, 1 en el rechace y 1 descolgado para contraataque.",
      desarrollo: "Ensayo de diferentes tipos de saque rival: cerrado al primer palo, abierto al punto de penalti, corto 2v1.",
      variantes: ["Variante 1: Salida rápida a la contra tras el despeje del central zonal.", "Variante 2: Defensa ante balón parado en corto."],
      prog: "Oposición real del equipo juvenil atacando el córner con variantes no avisadas.",
      reg: "Sin rematadores al hombre, solo calibración de posiciones zonales.",
      criterios: ["Dominio del juego aéreo y despeje orientado fuera de la frontal", "Atacar el balón y no dejarse bloquear"],
      carga_f: 3, carga_c: 3, op: 4, rep: 4, int: 3, phase: "defending", drill: "analítico", fuente: "UEFA Training Ground"
    },
    {
      nombre: "Circuito de Potencia Aeróbica y Velocidad Táctica 4v4",
      tipo: "circuito",
      familia: "FÍSICO",
      categoria: "cadete",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["pase", "control orientado"],
      obj_tac: ["potencia", "velocidad", "resistencia", "movilidad"],
      espacio: "40x25m",
      min_p: 8, max_p: 12, dur: 16,
      desc: "Trabajo intermitente de alta intensidad: 4v4 en espacio reducido durante 2 minutos a 100% de FCmax, seguido de 1 minuto de posesión técnica activa a 1 toque.",
      desarrollo: "4 series de 3 minutos con pausas completas de 2 minutos. Control estricto de la intensidad de acoso.",
      variantes: ["Variante 1: Partido con porterías pequeñas.", "Variante 2: Marcaje al hombre estricto durante los 2 minutos."],
      prog: "Reducir el espacio del 4v4 a 25x20m.",
      reg: "Aumentar el tiempo de posesión técnica y reducir el duelo a 1.5 minutos.",
      criterios: ["Mantener el rigor táctico bajo índices altos de lactato", "Capacidad de aceleración repetida"],
      carga_f: 4, carga_c: 3, op: 4, rep: 3, int: 4, phase: "attacking_build_up", drill: "circuito", fuente: "FIFA Training Centre"
    },
    {
      nombre: "Rondo de Presión y Circulación 8v4 en Tres Zonas",
      tipo: "rondo",
      familia: "TÁCTICA OFENSIVA",
      categoria: "cadete",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["pase", "control"],
      obj_tac: ["tercer hombre", "superioridad", "cambio de orientación"],
      espacio: "30x12m (3 rectángulos de 10x12m)",
      min_p: 12, max_p: 14, dur: 16,
      desc: "8 atacantes repartidos (4 en zona A, 4 en zona C) y 4 defensores (2 presionan en zona A, 2 interceptan en zona B intermedia).",
      desarrollo: "El objetivo es circular en zona A hasta encontrar el pase raso filtrado por zona B para conectar con los 4 compañeros de zona C.",
      variantes: ["Variante 1: Toques limitados a 2 en zona A y C.", "Variante 2: 1 defensor de zona B puede saltar a zona A."],
      prog: "Pase a zona C debe ser obligatoriamente por el suelo y al primer toque.",
      reg: "Defensores de zona B no pueden saltar a zonas exteriores.",
      criterios: ["Pase tenso que divide a los defensores de zona B", "Desmarque de apoyo del receptor lejano"],
      carga_f: 3, carga_c: 4, op: 3, rep: 3, int: 3, phase: "attacking_build_up", drill: "rondo", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Juego Global 11v11 Condicionado: Bloque Alto vs Bloque Bajo",
      tipo: "juego_global",
      familia: "TÁCTICA OFENSIVA",
      categoria: "cadete",
      dificultad: 3,
      bloque: "global",
      obj_tec: ["pase", "centro", "finalización", "despeje"],
      obj_tac: ["creación de espacios", "amplitud", "bloque", "defensa del área"],
      espacio: "Campo completo reglamentario",
      min_p: 22, max_p: 24, dur: 25,
      desc: "Simulación de partido completo 11v11: Equipo A ensaya ataque posicional contra bloque bajo cerrado; Equipo B trabaja repliegue intensivo y contraataque fulgurante.",
      desarrollo: "Condición: El equipo atacante debe finalizar la jugada en menos de 15 pases para no atascar la posesión.",
      variantes: ["Variante 1: Gol de remate de cabeza vale doble.", "Variante 2: Cambio de roles tras 12 minutos."],
      prog: "Defensa con libre flotación en mediocampo para robar en zona 2.",
      reg: "Equipo atacante juega con comodín central para asegurar circulación.",
      criterios: ["Amplitud máxima con laterales muy altos", "Paciencia y velocidad en la última toma de decisión"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "juego_global", fuente: "UEFA Training Ground"
    },

    // U17-U19 Juvenil (5 ejercicios)
    {
      nombre: "Modelo de Juego: Salida de Balón 3-4-3 vs Presión Par Emparejada",
      tipo: "juego_global",
      familia: "TÁCTICA OFENSIVA",
      categoria: "juvenil",
      dificultad: 4,
      bloque: "principal",
      obj_tec: ["pase", "control orientado"],
      obj_tac: ["salida de balón", "fijar y dividir", "tercer hombre", "superioridad"],
      espacio: "Tres cuartos de campo",
      min_p: 18, max_p: 22, dur: 22,
      desc: "Estructuración de salida de balón con 3 centrales y 2 pivotes frente a presión hombre a hombre del rival. Mecanización de desmarques de apoyo de carrileros y caída de media puntas.",
      desarrollo: "Foco en fijar con central exterior para liberar al carrilero en profundidad o encontrar al pivote a espaldas de la primera línea de presión.",
      variantes: ["Variante 1: Salida directa a segundo balón si el rival adelanta la línea al mediocampo.", "Variante 2: Permuta de posiciones entre pivote e interior."],
      prog: "Presión rival sin limitaciones con libertad total para el portero.",
      reg: "El rival solo puede iniciar presión cuando el primer pase sale del área.",
      criterios: ["Personalidad y precisión técnica bajo presión asfixiante", "Velocidad de ejecución a 1-2 toques"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "juego_global", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Transición Defensa-Ataque de Élite: 4v3 con Oposición en Persecución",
      tipo: "SSG",
      familia: "TRANSICIONES",
      categoria: "juvenil",
      dificultad: 4,
      bloque: "principal",
      obj_tec: ["conducción", "pase", "finalización"],
      obj_tac: ["contraataque", "velocidad táctica", "toma de decisión"],
      espacio: "60x40m",
      min_p: 12, max_p: 16, dur: 18,
      desc: "Situación de contraataque real a máxima velocidad: 4 atacantes salen disparados desde campo propio ante 3 defensores plantados en repliegue + 2 mediocentros rivales en persecución desesperada.",
      desarrollo: "Tiempo límite: 7 segundos para disparar a portería antes de que los perseguidores tapen los ángulos de pase.",
      variantes: ["Variante 1: Obligatorio pase cruzado antes del remate.", "Variante 2: Si los defensores cortan, tienen contraataque a portería opuesta."],
      prog: "Reducir a 5 segundos el tiempo límite de finalización.",
      reg: "Los perseguidores salen con 3 metros de desventaja adicional.",
      criterios: ["Conducir fijando al defensor central para liberar a los extremos", "Contundencia en el remate a puerta"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "SSG", fuente: "YouCoach"
    },
    {
      nombre: "ABP Ofensiva: Saque de Banda Táctico con Bloqueo y Prolongación",
      tipo: "analitico",
      familia: "BALÓN PARADO",
      categoria: "juvenil",
      dificultad: 3,
      bloque: "principal",
      obj_tec: ["pase", "golpeo", "juego aéreo"],
      obj_tac: ["saque de banda", "creación de espacios", "anticipación"],
      espacio: "Último tercio de banda",
      min_p: 12, max_p: 16, dur: 12,
      desc: "Mecanización de saque de banda en tres cuartos de campo: lanzamiento largo al primer palo, prolongación de cabeza de delantero y entrada fulgurante del extremo opuesto a portería.",
      desarrollo: "Movimientos coordinados de arrastre previo del lateral para generar el pasillo de lanzamiento.",
      variantes: ["Variante 1: Saque en corto y devolución al lanzador para centro al área.", "Variante 2: Lanzamiento raso hacia la frontal para tiro directo."],
      prog: "Defensa con oposición real en marcaje al hombre estricto.",
      reg: "Sin defensores para sincronizar el salto y la peinada.",
      criterios: ["Fuerza y precisión del saque con las dos manos", "Agresividad en la segunda jugada"],
      carga_f: 2, carga_c: 3, op: 3, rep: 4, int: 2, phase: "attacking_build_up", drill: "analítico", fuente: "UEFA Training Ground"
    },
    {
      nombre: "Estructura Defensiva de Presión en Bloque Medio 1-4-4-2 vs 1-4-3-3",
      tipo: "juego_medio",
      familia: "TÁCTICA DEFENSIVA",
      categoria: "juvenil",
      dificultad: 4,
      bloque: "principal",
      obj_tec: ["interceptación", "entrada"],
      obj_tac: ["bloque", "basculación", "vigilancia", "defensa del área"],
      espacio: "Medio campo completo",
      min_p: 18, max_p: 22, dur: 20,
      desc: "Sincronización del bloque defensivo medio: los dos puntas tapan el pase al pivote rival; la línea de 4 mediocampistas bascula compacta forzando el juego exterior hacia los laterales.",
      desarrollo: "Cuando el pase va al lateral rival, el interior de banda salta a presionar con la cobertura del lateral propio y el pivote defensivo.",
      variantes: ["Variante 1: Salto a presión alta tras pase defectuoso del central.", "Variante 2: Transición inmediata a gol tras robo."],
      prog: "El rival puede alternar juego directo a delanteros altos.",
      reg: "El rival juega sin extremos para reducir la exigencia en bandas.",
      criterios: ["Líneas juntas con menos de 10 metros entre defensa y mediocampo", "Impedir pases interiores que dividan el bloque"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 3, phase: "defending", drill: "juego_medio", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Partido Táctico 11v11 con Tiempos de Juego y Plan de Partido",
      tipo: "juego_global",
      familia: "TÁCTICA OFENSIVA",
      categoria: "juvenil",
      dificultad: 4,
      bloque: "global",
      obj_tec: ["pase", "centro", "finalización", "interceptación"],
      obj_tac: ["plan de partido", "modelo de juego", "adaptabilidad", "alta intensidad"],
      espacio: "Campo completo",
      min_p: 22, max_p: 24, dur: 30,
      desc: "Simulación de competición en dos tiempos de 15 minutos: Tiempo 1: Equipo A va ganando 1-0 y debe gestionar la posesión y las transiciones defensivas. Tiempo 2: Equipo A va perdiendo 0-1 y debe adelantar líneas con presión alta total.",
      desarrollo: "Gestión de los ritmos de partido, pausas tácticas, faltas inteligentes y toma de decisiones contextualizadas.",
      variantes: ["Variante 1: Jugar con inferioridad numérica (10v11) los últimos 5 minutos.", "Variante 2: Balón parado en el minuto final."],
      prog: "Ritmo competitivo absoluto con arbitraje riguroso.",
      reg: "Pausas cada 5 minutos para corrección táctica del entrenador.",
      criterios: ["Madurez táctica y lectura de los diferentes momentos del juego", "Gestión emocional del resultado"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "juego_global", fuente: "FIFA Training Centre"
    },

    // Senior / Amateur (5 ejercicios)
    {
      nombre: "Optimización Competitiva: Plan de Partido contra Bloque Bajo y Pérdidas",
      tipo: "juego_global",
      familia: "TÁCTICA OFENSIVA",
      categoria: "senior",
      dificultad: 4,
      bloque: "global",
      obj_tec: ["pase", "golpeo", "finalización"],
      obj_tac: ["modelo de juego", "creación de espacios", "vigilancia", "reacción tras pérdida"],
      espacio: "Campo completo",
      min_p: 20, max_p: 22, dur: 25,
      desc: "Trabajo táctico específico para desarmar defensas ultracerradas de 5 defensas. Foco en la circulación rápida con cambios de orientación de 40 metros y vigilancias ofensivas de los centrales para evitar contras.",
      desarrollo: "Uso de los pasillos interiores para generar 2v1 sobre los centrales exteriores rivales y centros pasados al segundo palo.",
      variantes: ["Variante 1: Disparo exterior obligatorio tras segunda jugada.", "Variante 2: Si el rival roba, contraataque a máxima velocidad."],
      prog: "Defensa con 10 jugadores en los últimos 30 metros.",
      reg: "Defensa de 4 jugadores para abrir espacios.",
      criterios: ["Vigilancias ofensivas impecables de los no poseedores", "Calidad y precisión en el último pase"],
      carga_f: 3, carga_c: 4, op: 4, rep: 4, int: 3, phase: "attacking_build_up", drill: "juego_global", fuente: "MBP School of Coaches"
    },
    {
      nombre: "Estrategia ABP de Rendimiento: Córner Ofensivo en Corto con Dos Tiempos",
      tipo: "analitico",
      familia: "BALÓN PARADO",
      categoria: "senior",
      dificultad: 4,
      bloque: "principal",
      obj_tec: ["golpeo", "centro", "finalización"],
      obj_tac: ["córner ofensivo", "toma de decisión", "anticipación"],
      espacio: "Área grande",
      min_p: 14, max_p: 18, dur: 15,
      desc: "Córner jugado en corto entre extremo y lateral. Tras atraer al defensor de banda, se busca el pase al interior en la frontal para centro con rosca hacia dentro atacando 4 jugadores al remate.",
      desarrollo: "Mecanización exacta de los tiempos de entrada: delantero al primer palo, central al segundo palo, media punta al punto de penalti y lateral al rechace.",
      variantes: ["Variante 1: Tiro directo desde la frontal si no hay oposición.", "Variante 2: Pared en banda y pase atrás a la frontal del área pequeña."],
      prog: "Oposición total con defensa zonal mixta agresiva.",
      reg: "Ejecución sin defensores para mecanizar el ritmo y la comba del centro.",
      criterios: ["Eficacia en el remate a puerta", "Evitar el fuera de juego en el segundo tiempo del córner"],
      carga_f: 2, carga_c: 4, op: 3, rep: 4, int: 2, phase: "attacking_build_up", drill: "analítico", fuente: "YouCoach"
    },
    {
      nombre: "Juego de Posición Específico 8v8 + 2 Porteros en Espacio Adaptado",
      tipo: "juego_medio",
      familia: "TÁCTICA OFENSIVA",
      categoria: "senior",
      dificultad: 4,
      bloque: "principal",
      obj_tec: ["pase", "control orientado", "finalización"],
      obj_tac: ["tercer hombre", "basculación", "amplitud", "presión tras pérdida"],
      espacio: "50x45m",
      min_p: 16, max_p: 18, dur: 20,
      desc: "Juego de posición competitivo con porterías en el que la posesión sirve para progresar y generar ocasiones claras bajo una presión de nivel profesional.",
      desarrollo: "Máximo 2 toques por jugador excepto en situación de 1v1 dentro del área.",
      variantes: ["Variante 1: Gol tras combinación de 6 pases vale doble.", "Variante 2: Recuperación en campo rival = opción de tiro inmediato."],
      prog: "1 toque obligatorio en zona de mediocampo.",
      reg: "3 toques libres para favorecer la fluidez.",
      criterios: ["Intensidad en la circulación de balón (>60 pases por minuto)", "Reacción instantánea tras la pérdida"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "attacking_build_up", drill: "juego_medio", fuente: "UEFA Training Ground"
    },
    {
      nombre: "Gestión de los Minutos Finales: Bloque Bajo y Repliegue con 10 Jugadores",
      tipo: "juego_global",
      familia: "TÁCTICA DEFENSIVA",
      categoria: "senior",
      dificultad: 4,
      bloque: "global",
      obj_tec: ["despeje", "interceptación"],
      obj_tac: ["defensa del área", "bloque", "vigilancia", "temporización"],
      espacio: "Medio campo",
      min_p: 20, max_p: 22, dur: 18,
      desc: "Simulación de situación crítica: defender un 1-0 en los últimos 10 minutos jugando con un jugador menos (10v11). Línea de 5-3-1 ultra compacta cerrando todos los espacios entre líneas.",
      desarrollo: "Despejes orientados hacia las esquinas para ganar segundos. Faltas tácticas en campo rival si se supera la primera línea.",
      variantes: ["Variante 1: Si el delantero descolgado aguanta el balón 5 segundos, se suma puntuación extra.", "Variante 2: Incorporación del portero rival al remate en ABP."],
      prog: "El rival ataca con 3 delanteros centros natos.",
      reg: "El rival no puede centrar al área de primera intención.",
      criterios: ["Solidaridad defensiva absoluta y comunicación constante", "Despejes contundentes sin segundas opciones en la frontal"],
      carga_f: 4, carga_c: 4, op: 4, rep: 4, int: 4, phase: "defending", drill: "juego_global", fuente: "FIFA Training Centre"
    },
    {
      nombre: "Circuito de Mantenimiento Físico-Táctico de Alta Intensidad (HIIT Deportivo)",
      tipo: "circuito",
      familia: "FÍSICO",
      categoria: "senior",
      dificultad: 4,
      bloque: "principal",
      obj_tec: ["pase", "golpeo"],
      obj_tac: ["resistencia", "potencia", "velocidad táctica"],
      espacio: "35x25m",
      min_p: 10, max_p: 14, dur: 15,
      desc: "Estaciones intermitentes de alta intensidad específicas para fútbol senior: cambios de dirección a 180°, saltos unilaterales sobre vallas altas y finalización de volea bajo máxima frecuencia cardíaca.",
      desarrollo: "Protocolo Tabata/HIIT: 20 segundos de esfuerzo máximo por 10 segundos de recuperación activa durante 8 minutos.",
      variantes: ["Variante 1: Pase tenso al primer toque entre cada salto.", "Variante 2: Duelo 1v1 sorpresa tras la última valla."],
      prog: "Aumentar a 30s de trabajo por 10s de descanso.",
      reg: "20s de trabajo por 20s de descanso.",
      criterios: ["Mantenimiento del gesto técnico perfecto pese al cansancio muscular", "Máxima entrega en cada aceleración"],
      carga_f: 4, carga_c: 3, op: 2, rep: 3, int: 4, phase: "attacking_build_up", drill: "circuito", fuente: "Adaptación metodológica"
    }
  ];

  const allExercises = [...exercises, ...detailedExercises];

  allExercises.forEach(ex => {
    const objTec = "ARRAY[" + ex.objetivo_tecnico.map(o => `'${o.replace(/'/g, "''")}'`).join(", ") + "]";
    const objTac = "ARRAY[" + ex.objetivo_tactico.map(o => `'${o.replace(/'/g, "''")}'`).join(", ") + "]";
    const catArray = "ARRAY['" + (ex.categoria_edad ? ex.categoria_edad.join("','") : ex.categoria) + "']";
    const cat = ex.age_category || ex.categoria;
    const materialArray = "ARRAY[" + (ex.material || ['balones', 'conos', 'petos']).map(m => `'${m}'`).join(", ") + "]";
    const variantesArray = "ARRAY[" + ex.variantes.map(v => `'${v.replace(/'/g, "''")}'`).join(", ") + "]";
    const tagsArray = "ARRAY[" + (ex.tags || [cat, ex.tipo, ex.familia]).map(t => `'${t}'`).join(", ") + "]";
    const criteriosArray = "ARRAY[" + (ex.criterios_exito || ex.criterios || ['Ejecución técnica correcta']).map(c => `'${c.replace(/'/g, "''")}'`).join(", ") + "]";

    sql += `INSERT INTO public.banco_ejercicios (
    club_id,
    nombre, tipo, familia, fuente, descripcion,
    organizacion, distribucion_inicial, desarrollo, rotaciones, puntuacion, intervenciones, correcciones,
    objetivo_tecnico, objetivo_tactico,
    categoria_edad, age_category,
    dificultad, duracion_recomendada,
    min_players, max_players,
    material, variantes, tags,
    bloque_sesion, carga_fisica, carga_cognitiva, oposicion, representatividad,
    intensity_level, game_phase, drill_structure,
    espacio, criterios_exito, progresion_descripcion, regresion_descripcion,
    is_validated
) VALUES (
    (SELECT id FROM public.clubs LIMIT 1),
    '${ex.nombre.replace(/'/g, "''")}',
    '${ex.tipo}',
    '${ex.familia}',
    '${(ex.fuente || 'Adaptación metodológica').replace(/'/g, "''")}',
    '${ex.descripcion.replace(/'/g, "''")}',
    '${(ex.organizacion || ex.espacio).replace(/'/g, "''")}',
    '${(ex.distribucion_inicial || 'Posicionamiento inicial según rol').replace(/'/g, "''")}',
    '${(ex.desarrollo || ex.descripcion).replace(/'/g, "''")}',
    '${(ex.rotaciones || 'Rotación continua').replace(/'/g, "''")}',
    '${(ex.puntuacion || 'Puntuación según objetivos conseguidos').replace(/'/g, "''")}',
    '${(ex.intervenciones || 'Corrección en pausas activas').replace(/'/g, "''")}',
    '${(ex.correcciones || 'Perfil corporal y precisión en el pase').replace(/'/g, "''")}',
    ${objTec},
    ${objTac},
    ${catArray},
    '${cat}',
    ${ex.dificultad},
    ${ex.duracion_recomendada || ex.dur || 15},
    ${ex.min_players || ex.min_p || 6},
    ${ex.max_players || ex.max_p || 12},
    ${materialArray},
    ${variantesArray},
    ${tagsArray},
    '${ex.bloque_sesion || ex.bloque || 'principal'}',
    ${ex.carga_fisica || ex.carga_f || 2},
    ${ex.carga_cognitiva || ex.carga_c || 2},
    ${ex.oposicion || ex.op || 2},
    ${ex.representatividad || ex.rep || 3},
    ${ex.intensity_level || ex.int || 3},
    '${ex.game_phase || ex.phase || 'attacking_build_up'}',
    '${ex.drill_structure || ex.drill || ex.tipo}',
    '${ex.espacio}',
    ${criteriosArray},
    '${(ex.progresion_descripcion || ex.prog || 'Reducir espacio y toques').replace(/'/g, "''")}',
    '${(ex.regresion_descripcion || ex.reg || 'Aumentar espacio y añadir comodines').replace(/'/g, "''")}',
    true
) ON CONFLICT DO NOTHING;\n\n`;
  });

  return { sql, count: allExercises.length };
};

const result = generateSql();
const outputPath = path.join(__dirname, 'supabase', 'migrations', '20260819_library_seed.sql');
fs.writeFileSync(outputPath, result.sql, 'utf8');
console.log(`Generated ${result.count} exercises into ${outputPath}`);
