import { useState, useMemo, useCallback } from 'react';

export interface TissueSubportion {
  code: string;
  label: string;
  shortLabel: string;
  munichSuggested: '1A' | '1B' | '2A' | '2B' | '3A' | '3B' | '4';
  description: string;
}

export interface AnatomicalZone {
  code: string;
  name: string;
  generalRegion: string;
  muscleGroup: string;
  laterality?: 'Izquierdo' | 'Derecho' | 'Bilateral' | 'No aplica';
  thumbnailKey?: string;
  viewDefault?: 'frontal' | 'posterior';
  incidencia?: 'Muy Alta' | 'Alta' | 'Moderada' | 'Leve' | 'Baja' | 'Grave';
  mecanismoComun?: string;
  munichDefault?: '1A' | '1B' | '2A' | '2B' | '3A' | '3B' | '4';
  subportions?: TissueSubportion[];
  isGoalkeeperZone?: boolean;
}

export const CANONICAL_SUBPORTIONS: TissueSubportion[] = [
  {
    code: 'tercio_proximal',
    label: 'Tercio Proximal / Inserción de Origen',
    shortLabel: 'Proximal',
    munichSuggested: '4',
    description: 'Entesis o tendón proximal (zona de tracción excéntrica y avulsión)',
  },
  {
    code: 'union_miotendinosa',
    label: 'Unión Miotendinosa (UMT)',
    shortLabel: 'Unión Miotendinosa',
    munichSuggested: '3B',
    description: 'Transición entre músculo y tendón (máxima vulnerabilidad en sprint y golpeo)',
  },
  {
    code: 'vientre_muscular',
    label: 'Vientre Muscular Central',
    shortLabel: 'Vientre Muscular',
    munichSuggested: '3A',
    description: 'Porción contráctil central (rotura miofascial o intramuscular)',
  },
  {
    code: 'tercio_distal',
    label: 'Tercio Distal / Inserción Distal',
    shortLabel: 'Distal',
    munichSuggested: '3B',
    description: 'Tendón libre distal o unión distal miotendinosa',
  },
];

export const LIGAMENT_SUBPORTIONS: TissueSubportion[] = [
  {
    code: 'insercion_proximal',
    label: 'Inserción Proximal (Origen óseo)',
    shortLabel: 'Inserción Proximal',
    munichSuggested: '4',
    description: 'Desinserción o arrancamiento óseo proximal',
  },
  {
    code: 'tercio_medio',
    label: 'Tercio Medio (Cuerpo ligamentoso)',
    shortLabel: 'Tercio Medio',
    munichSuggested: '3B',
    description: 'Disrupción intraligamentosa o rotura intersticial en el cuerpo',
  },
  {
    code: 'insercion_distal',
    label: 'Inserción Distal (Anclaje distal)',
    shortLabel: 'Inserción Distal',
    munichSuggested: '4',
    description: 'Avulsión o arrancamiento en el anclaje óseo distal',
  },
];

export const MENISCUS_SUBPORTIONS: TissueSubportion[] = [
  {
    code: 'cuerno_posterior',
    label: 'Cuerno Posterior',
    shortLabel: 'Cuerno Posterior',
    munichSuggested: '3B',
    description: 'Zona de mayor carga axial en flexión profunda de rodilla',
  },
  {
    code: 'cuerpo_medio',
    label: 'Cuerpo Medio',
    shortLabel: 'Cuerpo Medio',
    munichSuggested: '3B',
    description: 'Roturas radiales o en asa de cubo',
  },
  {
    code: 'cuerno_anterior',
    label: 'Cuerno Anterior',
    shortLabel: 'Cuerno Anterior',
    munichSuggested: '3A',
    description: 'Lesiones por compresión anterior e hiperextensión',
  },
];

export function getSubportionsForStructure(zoneCode?: string, structureName?: string): TissueSubportion[] {
  const code = (zoneCode || '').toLowerCase();
  const name = (structureName || '').toLowerCase();

  if (code.includes('menisco') || name.includes('menisco')) {
    return MENISCUS_SUBPORTIONS;
  }
  if (code.includes('cruzado') || code.includes('lca') || code.includes('ligamento') || name.includes('ligamento') || name.includes('esguince')) {
    return LIGAMENT_SUBPORTIONS;
  }
  return CANONICAL_SUBPORTIONS;
}

export const ANATOMICAL_ZONES: Record<string, AnatomicalZone> = {
  // === PUBIS / PUBALGIA / PELVIS ===
  pubis: {
    code: 'pubis',
    name: 'Pubis / Sínfisis Púbica (Pubalgia)',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Sínfisis Púbica y Entesis',
    laterality: 'No aplica',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Descompensación entre pared abdominal y aductores, cambios de dirección continuos y golpeo repetitivo de balón.',
    munichDefault: '2A',
  },
  pubis_der: {
    code: 'pubis_der',
    name: 'Pubis (Inserción Aductor Derecho)',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Sínfisis Púbica',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Entesopatía púbica por tracción excéntrica del aductor largo en frenadas y golpeo.',
    munichDefault: '3A',
  },
  pubis_izq: {
    code: 'pubis_izq',
    name: 'Pubis (Inserción Aductor Izquierdo)',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Sínfisis Púbica',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Entesopatía púbica por tracción excéntrica del aductor largo en frenadas y golpeo.',
    munichDefault: '3A',
  },

  // === CUÁDRICEPS (COMPLETO) ===
  cuadriceps_general_der: {
    code: 'cuadriceps_general_der',
    name: 'Cuádriceps Derecho (Global)',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Extensión forzada de rodilla en lanzamientos a portería y desaceleración brusca.',
    munichDefault: '3A',
  },
  cuadriceps_general_izq: {
    code: 'cuadriceps_general_izq',
    name: 'Cuádriceps Izquierdo (Global)',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Extensión forzada de rodilla en lanzamientos a portería y desaceleración brusca.',
    munichDefault: '3A',
  },
  recto_anterior_der: {
    code: 'recto_anterior_der',
    name: 'Recto anterior (Cuádriceps) Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Golpeo potente de balón con empeine, despejes al vuelo y sprint excéntrico.',
    munichDefault: '3B',
  },
  recto_anterior_izq: {
    code: 'recto_anterior_izq',
    name: 'Recto anterior (Cuádriceps) Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Golpeo potente de balón con empeine, despejes al vuelo y sprint excéntrico.',
    munichDefault: '3B',
  },
  vasto_lateral_der: {
    code: 'vasto_lateral_der',
    name: 'Vasto lateral (Cuádriceps) Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión forzada de rodilla en frenadas y desaceleraciones.',
    munichDefault: '3A',
  },
  vasto_lateral_izq: {
    code: 'vasto_lateral_izq',
    name: 'Vasto lateral (Cuádriceps) Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión forzada de rodilla en frenadas y desaceleraciones.',
    munichDefault: '3A',
  },
  vasto_medial_der: {
    code: 'vasto_medial_der',
    name: 'Vasto medial (Cuádriceps) Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Fallo de estabilización rotuliana en apoyos y giros con carga monopodal.',
    munichDefault: '2B',
  },
  vasto_medial_izq: {
    code: 'vasto_medial_izq',
    name: 'Vasto medial (Cuádriceps) Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Fallo de estabilización rotuliana en apoyos y giros con carga monopodal.',
    munichDefault: '2B',
  },
  vasto_intermedio_der: {
    code: 'vasto_intermedio_der',
    name: 'Vasto intermedio (Crural) Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Contusión directa ("bocadillo") o sobrecarga profunda por cargas de choque.',
    munichDefault: '3A',
  },
  vasto_intermedio_izq: {
    code: 'vasto_intermedio_izq',
    name: 'Vasto intermedio (Crural) Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Contusión directa ("bocadillo") o sobrecarga profunda por cargas de choque.',
    munichDefault: '3A',
  },
  tendon_cuadricipital_der: {
    code: 'tendon_cuadricipital_der',
    name: 'Tendón cuadricipital Derecho',
    generalRegion: 'Rodilla / Muslo',
    muscleGroup: 'Aparato extensor',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Carga excéntrica masiva al frenar o caer de un salto.',
    munichDefault: '4',
  },
  tendon_cuadricipital_izq: {
    code: 'tendon_cuadricipital_izq',
    name: 'Tendón cuadricipital Izquierdo',
    generalRegion: 'Rodilla / Muslo',
    muscleGroup: 'Aparato extensor',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Carga excéntrica masiva al frenar o caer de un salto.',
    munichDefault: '4',
  },
  sartorio_der: {
    code: 'sartorio_der',
    name: 'Sartorio Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Flexores de Cadera / Muslo',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Flexión combinada de cadera y rotación externa de rodilla en conducciones.',
    munichDefault: '1A',
  },
  sartorio_izq: {
    code: 'sartorio_izq',
    name: 'Sartorio Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Flexores de Cadera / Muslo',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Flexión combinada de cadera y rotación externa de rodilla en conducciones.',
    munichDefault: '1A',
  },

  // === SÓLEO Y PANTORRILLA ===
  soleo_der: {
    code: 'soleo_der',
    name: 'Sóleo Derecho',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Alta',
    mecanismoComun: 'Fatiga continua, carreras de fondo a media intensidad y acumulación de partidos.',
    munichDefault: '2A',
  },
  soleo_izq: {
    code: 'soleo_izq',
    name: 'Sóleo Izquierdo',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Alta',
    mecanismoComun: 'Fatiga continua, carreras de fondo a media intensidad y acumulación de partidos.',
    munichDefault: '2A',
  },
  gastrocnemio_medial_der: {
    code: 'gastrocnemio_medial_der',
    name: 'Gemelo interno (Gastrocnemio medial) Der.',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Arrancadas explosivas, saltos de cabeza y extensión brusca de rodilla con flexión dorsal.',
    munichDefault: '3B',
  },
  gastrocnemio_medial_izq: {
    code: 'gastrocnemio_medial_izq',
    name: 'Gemelo interno (Gastrocnemio medial) Izq.',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Arrancadas explosivas, saltos de cabeza y extensión brusca de rodilla con flexión dorsal.',
    munichDefault: '3B',
  },
  gastrocnemio_lateral_der: {
    code: 'gastrocnemio_lateral_der',
    name: 'Gemelo externo (Gastrocnemio lateral) Der.',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión brusca de tobillo y recepción forzada en apoyo en carrera.',
    munichDefault: '3A',
  },
  gastrocnemio_lateral_izq: {
    code: 'gastrocnemio_lateral_izq',
    name: 'Gemelo externo (Gastrocnemio lateral) Izq.',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión brusca de tobillo y recepción forzada en apoyo en carrera.',
    munichDefault: '3A',
  },
  plantar_delgado_der: {
    code: 'plantar_delgado_der',
    name: 'Plantar delgado Derecho',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Pantorrilla',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Sensación súbita de "pedrada" o chasquido en aceleración brusca.',
    munichDefault: '3A',
  },
  plantar_delgado_izq: {
    code: 'plantar_delgado_izq',
    name: 'Plantar delgado Izquierdo',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Pantorrilla',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Sensación súbita de "pedrada" o chasquido en aceleración brusca.',
    munichDefault: '3A',
  },
  tibial_anterior_der: {
    code: 'tibial_anterior_der',
    name: 'Tibial anterior Derecho',
    generalRegion: 'Pierna Anterior',
    muscleGroup: 'Compartimento anterior',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Sobrecarga por golpeo repetitivo de balón y superficies de césped duro.',
    munichDefault: '1A',
  },
  tibial_anterior_izq: {
    code: 'tibial_anterior_izq',
    name: 'Tibial anterior Izquierdo',
    generalRegion: 'Pierna Anterior',
    muscleGroup: 'Compartimento anterior',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Sobrecarga por golpeo repetitivo de balón y superficies de césped duro.',
    munichDefault: '1A',
  },
  peroneos_der: {
    code: 'peroneos_der',
    name: 'Peroneos (Largo / Corto) Derecho',
    generalRegion: 'Pierna Lateral',
    muscleGroup: 'Compartimento lateral',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Tendinopatía o luxación de retináculo peroneo tras inversión forzada de tobillo.',
    munichDefault: '3A',
  },
  peroneos_izq: {
    code: 'peroneos_izq',
    name: 'Peroneos (Largo / Corto) Izquierdo',
    generalRegion: 'Pierna Lateral',
    muscleGroup: 'Compartimento lateral',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Tendinopatía o luxación de retináculo peroneo tras inversión forzada de tobillo.',
    munichDefault: '3A',
  },

  // === ISQUIOTIBIALES ===
  isquiotibiales_der: {
    code: 'isquiotibiales_der',
    name: 'Isquiotibiales Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Sprints a máxima velocidad en fase de desaceleración / oscilación tardía.',
    munichDefault: '3B',
  },
  isquiotibiales_izq: {
    code: 'isquiotibiales_izq',
    name: 'Isquiotibiales Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Sprints a máxima velocidad en fase de desaceleración / oscilación tardía.',
    munichDefault: '3B',
  },
  biceps_femoral_larga_der: {
    code: 'biceps_femoral_larga_der',
    name: 'Bíceps femoral (Cabeza larga) Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Sprints a máxima velocidad en fase de desaceleración / oscilación tardía.',
    munichDefault: '3B',
  },
  biceps_femoral_larga_izq: {
    code: 'biceps_femoral_larga_izq',
    name: 'Bíceps femoral (Cabeza larga) Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Sprints a máxima velocidad en fase de desaceleración / oscilación tardía.',
    munichDefault: '3B',
  },
  biceps_femoral_corta_der: {
    code: 'biceps_femoral_corta_der',
    name: 'Bíceps femoral (Cabeza corta) Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Baja',
    mecanismoComun: 'Desaceleraciones bruscas y flexión pronunciada de rodilla.',
    munichDefault: '3A',
  },
  biceps_femoral_corta_izq: {
    code: 'biceps_femoral_corta_izq',
    name: 'Bíceps femoral (Cabeza corta) Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Baja',
    mecanismoComun: 'Desaceleraciones bruscas y flexión pronunciada de rodilla.',
    munichDefault: '3A',
  },
  semitendinoso_der: {
    code: 'semitendinoso_der',
    name: 'Semitendinoso Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Alta',
    mecanismoComun: 'Aceleraciones súbitas y cambios de ritmo durante transiciones ofensivas.',
    munichDefault: '3A',
  },
  semitendinoso_izq: {
    code: 'semitendinoso_izq',
    name: 'Semitendinoso Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Alta',
    mecanismoComun: 'Aceleraciones súbitas y cambios de ritmo durante transiciones ofensivas.',
    munichDefault: '3A',
  },
  semimembranoso_der: {
    code: 'semimembranoso_der',
    name: 'Semimembranoso Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Frenadas bruscas, estiramientos forzados y golpeos en extensión de cadera.',
    munichDefault: '3B',
  },
  semimembranoso_izq: {
    code: 'semimembranoso_izq',
    name: 'Semimembranoso Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Frenadas bruscas, estiramientos forzados y golpeos en extensión de cadera.',
    munichDefault: '3B',
  },

  // === ADUCTORES E INGLE ===
  aductor_largo_der: {
    code: 'aductor_largo_der',
    name: 'Aductor largo Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Cambios de dirección bruscos, golpeo con empeine interior y pubalgia.',
    munichDefault: '3A',
  },
  aductor_largo_izq: {
    code: 'aductor_largo_izq',
    name: 'Aductor largo Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Cambios de dirección bruscos, golpeo con empeine interior y pubalgia.',
    munichDefault: '3A',
  },
  aductor_mayor_der: {
    code: 'aductor_mayor_der',
    name: 'Aductor mayor Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Aperturas forzadas de piernas, estiramientos y caídas en tijera.',
    munichDefault: '3B',
  },
  aductor_mayor_izq: {
    code: 'aductor_mayor_izq',
    name: 'Aductor mayor Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Aperturas forzadas de piernas, estiramientos y caídas en tijera.',
    munichDefault: '3B',
  },
  gracilis_der: {
    code: 'gracilis_der',
    name: 'Gracilis (Recto interno) Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Aducción combinada con flexión de rodilla en controles orientados.',
    munichDefault: '1A',
  },
  gracilis_izq: {
    code: 'gracilis_izq',
    name: 'Gracilis (Recto interno) Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Aducción combinada con flexión de rodilla en controles orientados.',
    munichDefault: '1A',
  },
  psoas_der: {
    code: 'psoas_der',
    name: 'Psoas ilíaco Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Flexores de Cadera',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Hiperextensión brusca de cadera o golpeos al aire sin balón.',
    munichDefault: '2A',
  },
  psoas_izq: {
    code: 'psoas_izq',
    name: 'Psoas ilíaco Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Flexores de Cadera',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Hiperextensión brusca de cadera o golpeos al aire sin balón.',
    munichDefault: '2A',
  },
  pectineo_der: {
    code: 'pectineo_der',
    name: 'Pectíneo Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Flexores / Aductores',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Movimientos explosivos de flexión y aducción de cadera en espacios reducidos.',
    munichDefault: '1A',
  },
  pectineo_izq: {
    code: 'pectineo_izq',
    name: 'Pectíneo Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Flexores / Aductores',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Movimientos explosivos de flexión y aducción de cadera en espacios reducidos.',
    munichDefault: '1A',
  },

  // === ROTURAS DE LIGAMENTOS Y MENISCOS (RODILLA) ===
  ligamento_cruzado_ant_der: {
    code: 'ligamento_cruzado_ant_der',
    name: 'Rotura Ligamento Cruzado Anterior (LCA) Der.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Pivote central de rodilla',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Valgo forzado con rotación externa y desaceleración sin contacto (mecanismo clásico LCA).',
    munichDefault: '4',
  },
  ligamento_cruzado_ant_izq: {
    code: 'ligamento_cruzado_ant_izq',
    name: 'Rotura Ligamento Cruzado Anterior (LCA) Izq.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Pivote central de rodilla',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Valgo forzado con rotación externa y desaceleración sin contacto (mecanismo clásico LCA).',
    munichDefault: '4',
  },
  ligamento_cruzado_post_der: {
    code: 'ligamento_cruzado_post_der',
    name: 'Rotura Ligamento Cruzado Posterior (LCP) Der.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Pivote central de rodilla',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'posterior',
    incidencia: 'Grave',
    mecanismoComun: 'Impacto directo contra la tibia proximal con la rodilla flexionada (choque con rival o poste).',
    munichDefault: '4',
  },
  ligamento_cruzado_post_izq: {
    code: 'ligamento_cruzado_post_izq',
    name: 'Rotura Ligamento Cruzado Posterior (LCP) Izq.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Pivote central de rodilla',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'posterior',
    incidencia: 'Grave',
    mecanismoComun: 'Impacto directo contra la tibia proximal con la rodilla flexionada (choque con rival o poste).',
    munichDefault: '4',
  },
  ligamento_colateral_medial_der: {
    code: 'ligamento_colateral_medial_der',
    name: 'Ligamento Colateral Medial / Interno (LCM) Der.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Estabilidad lateral de rodilla',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Traumatismo directo en la cara externa de la rodilla forzando apertura medial en valgo.',
    munichDefault: '3A',
  },
  ligamento_colateral_medial_izq: {
    code: 'ligamento_colateral_medial_izq',
    name: 'Ligamento Colateral Medial / Interno (LCM) Izq.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Estabilidad lateral de rodilla',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Traumatismo directo en la cara externa de la rodilla forzando apertura medial en valgo.',
    munichDefault: '3A',
  },
  menisco_interno_der: {
    code: 'menisco_interno_der',
    name: 'Rotura Menisco Interno (Medial) Derecho',
    generalRegion: 'Rodilla',
    muscleGroup: 'Meniscos y fibrocartílago',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Torsión brusca de rodilla con el pie fijo en el césped en flexión (rotura en asa de cubo o cuerno posterior).',
    munichDefault: '3B',
  },
  menisco_interno_izq: {
    code: 'menisco_interno_izq',
    name: 'Rotura Menisco Interno (Medial) Izquierdo',
    generalRegion: 'Rodilla',
    muscleGroup: 'Meniscos y fibrocartílago',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Torsión brusca de rodilla con el pie fijo en el césped en flexión (rotura en asa de cubo o cuerno posterior).',
    munichDefault: '3B',
  },
  menisco_externo_der: {
    code: 'menisco_externo_der',
    name: 'Rotura Menisco Externo (Lateral) Derecho',
    generalRegion: 'Rodilla',
    muscleGroup: 'Meniscos y fibrocartílago',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Impacto o torsión con carga en varo rotacional en frenadas bruscas.',
    munichDefault: '3B',
  },
  menisco_externo_izq: {
    code: 'menisco_externo_izq',
    name: 'Rotura Menisco Externo (Lateral) Izquierdo',
    generalRegion: 'Rodilla',
    muscleGroup: 'Meniscos y fibrocartílago',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Impacto o torsión con carga en varo rotacional en frenadas bruscas.',
    munichDefault: '3B',
  },
  tendon_rotuliano_der: {
    code: 'tendon_rotuliano_der',
    name: 'Tendón rotuliano Derecho',
    generalRegion: 'Rodilla',
    muscleGroup: 'Aparato extensor',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Impactos reiterados de salto, frenado en carrera e hiperpresión patelar ("rodilla del saltador").',
    munichDefault: '3B',
  },
  tendon_rotuliano_izq: {
    code: 'tendon_rotuliano_izq',
    name: 'Tendón rotuliano Izquierdo',
    generalRegion: 'Rodilla',
    muscleGroup: 'Aparato extensor',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Impactos reiterados de salto, frenado en carrera e hiperpresión patelar ("rodilla del saltador").',
    munichDefault: '3B',
  },

  // === LIGAMENTOS DE TOBILLO Y TENDÓN DE AQUILES ===
  tendon_aquiles_der: {
    code: 'tendon_aquiles_der',
    name: 'Rotura / Tendinopatía Aquiles Derecho',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Tendón calcáneo',
    laterality: 'Derecho',
    thumbnailKey: 'tobillo',
    viewDefault: 'posterior',
    incidencia: 'Grave',
    mecanismoComun: 'Despegues explosivos, caídas descompensadas y microtraumatismo reiterado.',
    munichDefault: '4',
  },
  tendon_aquiles_izq: {
    code: 'tendon_aquiles_izq',
    name: 'Rotura / Tendinopatía Aquiles Izquierdo',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Tendón calcáneo',
    laterality: 'Izquierdo',
    thumbnailKey: 'tobillo',
    viewDefault: 'posterior',
    incidencia: 'Grave',
    mecanismoComun: 'Despegues explosivos, caídas descompensadas y microtraumatismo reiterado.',
    munichDefault: '4',
  },
  tobillo_ligamentos_der: {
    code: 'tobillo_ligamentos_der',
    name: 'Rotura / Esguince Ligamentos Tobillo (LPAA) Der.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Complejo ligamentoso lateral',
    laterality: 'Derecho',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Inversión forzada con flexión plantar al pisar a un rival o irregularidad del terreno.',
    munichDefault: '3A',
  },
  tobillo_ligamentos_izq: {
    code: 'tobillo_ligamentos_izq',
    name: 'Rotura / Esguince Ligamentos Tobillo (LPAA) Izq.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Complejo ligamentoso lateral',
    laterality: 'Izquierdo',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Inversión forzada con flexión plantar al pisar a un rival o irregularidad del terreno.',
    munichDefault: '3A',
  },
  sindesmosis_tobillo_der: {
    code: 'sindesmosis_tobillo_der',
    name: 'Esguince Sindesmosis Tibioperonea (Esguince Alto) Der.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Sindesmosis tibioperonea',
    laterality: 'Derecho',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Rotación externa forzada del pie con dorsiflexión máxima tras entrada lateral.',
    munichDefault: '3B',
  },
  sindesmosis_tobillo_izq: {
    code: 'sindesmosis_tobillo_izq',
    name: 'Esguince Sindesmosis Tibioperonea (Esguince Alto) Izq.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Sindesmosis tibioperonea',
    laterality: 'Izquierdo',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Rotación externa forzada del pie con dorsiflexión máxima tras entrada lateral.',
    munichDefault: '3B',
  },

  // === TARSO Y METATARSO (PIE) ===
  tarso_navicular_der: {
    code: 'tarso_navicular_der',
    name: 'Tarso / Escafoides Tarsiano (Navicular) Der.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Huesos del Tarso',
    laterality: 'Derecho',
    thumbnailKey: 'pie_tarso',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Fractura por estrés del escafoides tarsiano por impacto continuo y flexión dorsal forzada.',
    munichDefault: '4',
  },
  tarso_navicular_izq: {
    code: 'tarso_navicular_izq',
    name: 'Tarso / Escafoides Tarsiano (Navicular) Izq.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Huesos del Tarso',
    laterality: 'Izquierdo',
    thumbnailKey: 'pie_tarso',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Fractura por estrés del escafoides tarsiano por impacto continuo y flexión dorsal forzada.',
    munichDefault: '4',
  },
  metatarso_5to_der: {
    code: 'metatarso_5to_der',
    name: '5º Metatarsiano (Fractura de Jones) Derecho',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Metatarso',
    laterality: 'Derecho',
    thumbnailKey: 'pie_meta',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Inversión violenta del mediopié durante cambios de dirección o pisadas en falso (zona de Jones).',
    munichDefault: '4',
  },
  metatarso_5to_izq: {
    code: 'metatarso_5to_izq',
    name: '5º Metatarsiano (Fractura de Jones) Izquierdo',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Metatarso',
    laterality: 'Izquierdo',
    thumbnailKey: 'pie_meta',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Inversión violenta del mediopié durante cambios de dirección o pisadas en falso (zona de Jones).',
    munichDefault: '4',
  },
  metatarso_general_der: {
    code: 'metatarso_general_der',
    name: 'Metatarsalgia / Metatarsos (1º a 4º) Derecho',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Metatarso',
    laterality: 'Derecho',
    thumbnailKey: 'pie_meta',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Periostitis o microfracturas por estrés por tacos sobre césped artificial duro.',
    munichDefault: '3A',
  },
  metatarso_general_izq: {
    code: 'metatarso_general_izq',
    name: 'Metatarsalgia / Metatarsos (1º a 4º) Izquierdo',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Metatarso',
    laterality: 'Izquierdo',
    thumbnailKey: 'pie_meta',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Periostitis o microfracturas por estrés por tacos sobre césped artificial duro.',
    munichDefault: '3A',
  },

  // === GLÚTEOS Y CADERA ===
  gluteo_mayor_der: {
    code: 'gluteo_mayor_der',
    name: 'Glúteo mayor Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Glúteos',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión potente de cadera, despegue en saltos y aceleraciones iniciales.',
    munichDefault: '3A',
  },
  gluteo_mayor_izq: {
    code: 'gluteo_mayor_izq',
    name: 'Glúteo mayor Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Glúteos',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión potente de cadera, despegue en saltos y aceleraciones iniciales.',
    munichDefault: '3A',
  },
  gluteo_medio_der: {
    code: 'gluteo_medio_der',
    name: 'Glúteo medio / menor Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Glúteos',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Cambios de dirección, apoyos monopodales forzados e inestabilidad pélvica.',
    munichDefault: '2B',
  },
  gluteo_medio_izq: {
    code: 'gluteo_medio_izq',
    name: 'Glúteo medio / menor Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Glúteos',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Cambios de dirección, apoyos monopodales forzados e inestabilidad pélvica.',
    munichDefault: '2B',
  },

  // === TRONCO Y ZONAS SUPERIORES ===
  abdomen: {
    code: 'abdomen',
    name: 'Recto abdominal / Oblicuos (Core)',
    generalRegion: 'Tronco',
    muscleGroup: 'Pared abdominal',
    laterality: 'No aplica',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Torsiones forzadas de tronco en disputas aéreas y remates descompensados.',
    munichDefault: '2A',
  },
  lumbar: {
    code: 'lumbar',
    name: 'Zona Lumbar / Paravertebrales',
    generalRegion: 'Tronco',
    muscleGroup: 'Erectores de columna',
    laterality: 'No aplica',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Sobrecargas mecánicas por impacto, choque de cargas y frenadas repetitivas.',
    munichDefault: '2A',
  },
  pecho: {
    code: 'pecho',
    name: 'Pectoral / Tórax',
    generalRegion: 'Tronco',
    muscleGroup: 'Pectoral',
    laterality: 'No aplica',
    thumbnailKey: 'brazo',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Contusiones por choque con rivales o caídas al suelo.',
    munichDefault: '1A',
  },
  dorsal: {
    code: 'dorsal',
    name: 'Dorsal ancho / Espalda alta',
    generalRegion: 'Tronco',
    muscleGroup: 'Espalda',
    laterality: 'No aplica',
    thumbnailKey: 'cuello',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Tirones en disputas de agarre y apoyos en salto.',
    munichDefault: '1A',
  },
  hombro_der: {
    code: 'hombro_der',
    name: 'Hombro / Manguito rotador Derecho',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Hombro',
    laterality: 'Derecho',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Caídas sobre el brazo extendido o luxaciones glenohumerales en porteros.',
    munichDefault: '3A',
  },
  hombro_izq: {
    code: 'hombro_izq',
    name: 'Hombro / Manguito rotador Izquierdo',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Hombro',
    laterality: 'Izquierdo',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Caídas sobre el brazo extendido o luxaciones glenohumerales en porteros.',
    munichDefault: '3A',
  },
  cuello: {
    code: 'cuello',
    name: 'Cuello / Cervical',
    generalRegion: 'Cabeza y cuello',
    muscleGroup: 'Trapecio y Esternocleidomastoideo',
    laterality: 'No aplica',
    thumbnailKey: 'cuello',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Latigazo cervical en remates forzados de cabeza o colisiones aéreas.',
    munichDefault: '1A',
  },
  cabeza: {
    code: 'cabeza',
    name: 'Cabeza / Región Craneofacial',
    generalRegion: 'Cabeza y cuello',
    muscleGroup: 'Craneofacial',
    laterality: 'No aplica',
    thumbnailKey: 'cabeza',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Impactos fortuitos cabeza con cabeza, golpes de codo o conmoción deportiva.',
    munichDefault: '1A',
  },

  // === INGLE Y CADERA: GRÁCIL, PSOAS Y TENSOR DE LA FASCIA LATA ===
  gracil_der: {
    code: 'gracil_der',
    name: 'Grácil / Recto interno Derecho',
    generalRegion: 'Ingle y Cadera',
    muscleGroup: 'Aductores',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Movimientos de torsión con pie fijo y desaceleración en rotación interna.',
    munichDefault: '3A',
  },
  gracil_izq: {
    code: 'gracil_izq',
    name: 'Grácil / Recto interno Izquierdo',
    generalRegion: 'Ingle y Cadera',
    muscleGroup: 'Aductores',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Movimientos de torsión con pie fijo y desaceleración en rotación interna.',
    munichDefault: '3A',
  },
  psoas_iliaco_der: {
    code: 'psoas_iliaco_der',
    name: 'Psoas ilíaco Derecho',
    generalRegion: 'Ingle y Cadera',
    muscleGroup: 'Flexores de cadera',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Flexión potente de la pierna en el golpeo de balón y arrancadas en carrera.',
    munichDefault: '3A',
  },
  psoas_iliaco_izq: {
    code: 'psoas_iliaco_izq',
    name: 'Psoas ilíaco Izquierdo',
    generalRegion: 'Ingle y Cadera',
    muscleGroup: 'Flexores de cadera',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Flexión potente de la pierna en el golpeo de balón y arrancadas en carrera.',
    munichDefault: '3A',
  },
  tensor_fascia_lata_der: {
    code: 'tensor_fascia_lata_der',
    name: 'Tensor de la fascia lata Derecho',
    generalRegion: 'Ingle y Cadera',
    muscleGroup: 'Flexores y abductores de cadera',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Carreras laterales, cambios de dirección y estabilización pélvica.',
    munichDefault: '2B',
  },
  tensor_fascia_lata_izq: {
    code: 'tensor_fascia_lata_izq',
    name: 'Tensor de la fascia lata Izquierdo',
    generalRegion: 'Ingle y Cadera',
    muscleGroup: 'Flexores y abductores de cadera',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Carreras laterales, cambios de dirección y estabilización pélvica.',
    munichDefault: '2B',
  },

  // === PIERNA INFERIOR: PERONEOS LATERALES ===
  peroneo_lateral_der: {
    code: 'peroneo_lateral_der',
    name: 'Peroneos laterales Derechos (Largo / Corto)',
    generalRegion: 'Pantorrilla y Tobillo',
    muscleGroup: 'Compartimento lateral de la pierna',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Secundario a esguinces de tobillo por inversión violenta o tracción del tendón.',
    munichDefault: '2A',
  },
  peroneo_lateral_izq: {
    code: 'peroneo_lateral_izq',
    name: 'Peroneos laterales Izquierdos (Largo / Corto)',
    generalRegion: 'Pantorrilla y Tobillo',
    muscleGroup: 'Compartimento lateral de la pierna',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Secundario a esguinces de tobillo por inversión violenta o tracción del tendón.',
    munichDefault: '2A',
  },

  // === CORE Y TRONCO ===
  recto_abdominal: {
    code: 'recto_abdominal',
    name: 'Recto abdominal (Core)',
    generalRegion: 'Core y Tronco',
    muscleGroup: 'Pared abdominal',
    laterality: 'Bilateral',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Giros en el aire, saques de banda de larga distancia e hiperflexión excéntrica.',
    munichDefault: '3A',
  },
  oblicuo_abdomen_der: {
    code: 'oblicuo_abdomen_der',
    name: 'Oblicuo abdominal Derecho (Interno / Externo)',
    generalRegion: 'Core y Tronco',
    muscleGroup: 'Pared abdominal',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Torsiones de tronco bruscas en carrera, saltos o disparos descompensados.',
    munichDefault: '2A',
  },
  oblicuo_abdomen_izq: {
    code: 'oblicuo_abdomen_izq',
    name: 'Oblicuo abdominal Izquierdo (Interno / Externo)',
    generalRegion: 'Core y Tronco',
    muscleGroup: 'Pared abdominal',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Torsiones de tronco bruscas en carrera, saltos o disparos descompensados.',
    munichDefault: '2A',
  },
  erectores_columna: {
    code: 'erectores_columna',
    name: 'Erectores de la columna (Masa lumbar común)',
    generalRegion: 'Core y Tronco',
    muscleGroup: 'Espalda baja / Paravertebrales',
    laterality: 'Bilateral',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Impactos, caídas y saltos repetitivos con microtraumatismo axial.',
    munichDefault: '2A',
  },

  // === TREN SUPERIOR / EXCLUSIVOS Y FRECUENTES EN PORTERO ===
  supraespinoso_der: {
    code: 'supraespinoso_der',
    name: 'Supraespinoso Derecho (Hombro)',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Manguito rotador',
    laterality: 'Derecho',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Estiradas, caídas apoyando el brazo y desaceleración en lanzamientos.',
    munichDefault: '3B',
    isGoalkeeperZone: true,
  },
  supraespinoso_izq: {
    code: 'supraespinoso_izq',
    name: 'Supraespinoso Izquierdo (Hombro)',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Manguito rotador',
    laterality: 'Izquierdo',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Estiradas, caídas apoyando el brazo y desaceleración en lanzamientos.',
    munichDefault: '3B',
    isGoalkeeperZone: true,
  },
  subescapular_der: {
    code: 'subescapular_der',
    name: 'Subescapular / Redondo mayor Derecho',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Manguito rotador y escápula',
    laterality: 'Derecho',
    thumbnailKey: 'hombro',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Saques de mano de larga distancia y rotación interna forzada.',
    munichDefault: '3A',
    isGoalkeeperZone: true,
  },
  subescapular_izq: {
    code: 'subescapular_izq',
    name: 'Subescapular / Redondo mayor Izquierdo',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Manguito rotador y escápula',
    laterality: 'Izquierdo',
    thumbnailKey: 'hombro',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Saques de mano de larga distancia y rotación interna forzada.',
    munichDefault: '3A',
    isGoalkeeperZone: true,
  },
  dorsal_ancho_der: {
    code: 'dorsal_ancho_der',
    name: 'Dorsal ancho Derecho',
    generalRegion: 'Espalda y Tronco',
    muscleGroup: 'Espalda',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Impactos contra el suelo o postes en estiradas defensivas.',
    munichDefault: '2A',
    isGoalkeeperZone: true,
  },
  dorsal_ancho_izq: {
    code: 'dorsal_ancho_izq',
    name: 'Dorsal ancho Izquierdo',
    generalRegion: 'Espalda y Tronco',
    muscleGroup: 'Espalda',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Impactos contra el suelo o postes en estiradas defensivas.',
    munichDefault: '2A',
    isGoalkeeperZone: true,
  },
  pectoral_mayor_der: {
    code: 'pectoral_mayor_der',
    name: 'Pectoral mayor Derecho',
    generalRegion: 'Tórax y Tronco',
    muscleGroup: 'Pectoral',
    laterality: 'Derecho',
    thumbnailKey: 'brazo',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Bloqueos de balón frontales potentes y choques con el suelo en estiradas.',
    munichDefault: '2A',
    isGoalkeeperZone: true,
  },
  pectoral_mayor_izq: {
    code: 'pectoral_mayor_izq',
    name: 'Pectoral mayor Izquierdo',
    generalRegion: 'Tórax y Tronco',
    muscleGroup: 'Pectoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'brazo',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Bloqueos de balón frontales potentes y choques con el suelo en estiradas.',
    munichDefault: '2A',
    isGoalkeeperZone: true,
  },

  // === TREN SUPERIOR Y BRAZOS (MIEMBROS SUPERIORES) ===
  deltoides_ant_der: {
    code: 'deltoides_ant_der',
    name: 'Deltoides anterior / medio Derecho',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Hombro',
    laterality: 'Derecho',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Contusiones directas en caídas, choques hombro con hombro y sobrecarga por lanzamientos.',
    munichDefault: '1A',
  },
  deltoides_ant_izq: {
    code: 'deltoides_ant_izq',
    name: 'Deltoides anterior / medio Izquierdo',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Hombro',
    laterality: 'Izquierdo',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Contusiones directas en caídas, choques hombro con hombro y sobrecarga por lanzamientos.',
    munichDefault: '1A',
  },
  deltoides_post_der: {
    code: 'deltoides_post_der',
    name: 'Deltoides posterior Derecho',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Hombro',
    laterality: 'Derecho',
    thumbnailKey: 'hombro',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Tracción en caídas hacia atrás y desaceleración brusca de brazos.',
    munichDefault: '1A',
  },
  deltoides_post_izq: {
    code: 'deltoides_post_izq',
    name: 'Deltoides posterior Izquierdo',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Hombro',
    laterality: 'Izquierdo',
    thumbnailKey: 'hombro',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Tracción en caídas hacia atrás y desaceleración brusca de brazos.',
    munichDefault: '1A',
  },
  biceps_braquial_der: {
    code: 'biceps_braquial_der',
    name: 'Bíceps braquial Derecho',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Brazo',
    laterality: 'Derecho',
    thumbnailKey: 'brazo',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Flexión potente resistida, tirones en forcejeos o paradas de balón.',
    munichDefault: '2A',
  },
  biceps_braquial_izq: {
    code: 'biceps_braquial_izq',
    name: 'Bíceps braquial Izquierdo',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Brazo',
    laterality: 'Izquierdo',
    thumbnailKey: 'brazo',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Flexión potente resistida, tirones en forcejeos o paradas de balón.',
    munichDefault: '2A',
  },
  triceps_braquial_der: {
    code: 'triceps_braquial_der',
    name: 'Tríceps braquial Derecho',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Brazo',
    laterality: 'Derecho',
    thumbnailKey: 'brazo',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Extensión forzada de codo en caídas apoyando la mano o lanzamientos.',
    munichDefault: '2A',
  },
  triceps_braquial_izq: {
    code: 'triceps_braquial_izq',
    name: 'Tríceps braquial Izquierdo',
    generalRegion: 'Hombro y Brazo',
    muscleGroup: 'Brazo',
    laterality: 'Izquierdo',
    thumbnailKey: 'brazo',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Extensión forzada de codo en caídas apoyando la mano o lanzamientos.',
    munichDefault: '2A',
  },
  codo_der: {
    code: 'codo_der',
    name: 'Codo / Epicóndilo Derecho',
    generalRegion: 'Codo y Antebrazo',
    muscleGroup: 'Articulación del Codo',
    laterality: 'Derecho',
    thumbnailKey: 'codo',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Hiperextensión en caídas o impacto directo con el terreno de juego.',
    munichDefault: '1A',
  },
  codo_izq: {
    code: 'codo_izq',
    name: 'Codo / Epicóndilo Izquierdo',
    generalRegion: 'Codo y Antebrazo',
    muscleGroup: 'Articulación del Codo',
    laterality: 'Izquierdo',
    thumbnailKey: 'codo',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Hiperextensión en caídas o impacto directo con el terreno de juego.',
    munichDefault: '1A',
  },
  antebrazo_flexores_der: {
    code: 'antebrazo_flexores_der',
    name: 'Antebrazo (Flexores) Derecho',
    generalRegion: 'Codo y Antebrazo',
    muscleGroup: 'Antebrazo',
    laterality: 'Derecho',
    thumbnailKey: 'antebrazo',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Sobrecarga en agarres, paradas de balón en porteros y tracción de muñeca.',
    munichDefault: '2A',
  },
  antebrazo_flexores_izq: {
    code: 'antebrazo_flexores_izq',
    name: 'Antebrazo (Flexores) Izquierdo',
    generalRegion: 'Codo y Antebrazo',
    muscleGroup: 'Antebrazo',
    laterality: 'Izquierdo',
    thumbnailKey: 'antebrazo',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Sobrecarga en agarres, paradas de balón en porteros y tracción de muñeca.',
    munichDefault: '2A',
  },
  antebrazo_extensores_der: {
    code: 'antebrazo_extensores_der',
    name: 'Antebrazo (Extensores) Derecho',
    generalRegion: 'Codo y Antebrazo',
    muscleGroup: 'Antebrazo',
    laterality: 'Derecho',
    thumbnailKey: 'antebrazo',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Sobrecarga por microtraumatismo repetitivo o caídas con muñeca en flexión.',
    munichDefault: '2A',
  },
  antebrazo_extensores_izq: {
    code: 'antebrazo_extensores_izq',
    name: 'Antebrazo (Extensores) Izquierdo',
    generalRegion: 'Codo y Antebrazo',
    muscleGroup: 'Antebrazo',
    laterality: 'Izquierdo',
    thumbnailKey: 'antebrazo',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Sobrecarga por microtraumatismo repetitivo o caídas con muñeca en flexión.',
    munichDefault: '2A',
  },
  muneca_mano_der: {
    code: 'muneca_mano_der',
    name: 'Muñeca y Mano Derecha',
    generalRegion: 'Muñeca y Mano',
    muscleGroup: 'Muñeca y Dedos',
    laterality: 'Derecho',
    thumbnailKey: 'muneca',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Esguince por hiperextensión en caídas al suelo o disparos a corta distancia en porteros.',
    munichDefault: '1A',
  },
  muneca_mano_izq: {
    code: 'muneca_mano_izq',
    name: 'Muñeca y Mano Izquierda',
    generalRegion: 'Muñeca y Mano',
    muscleGroup: 'Muñeca y Dedos',
    laterality: 'Izquierdo',
    thumbnailKey: 'muneca',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Esguince por hiperextensión en caídas al suelo o disparos a corta distancia en porteros.',
    munichDefault: '1A',
  },
};

export type AnatomicalTabCategory = 'todos' | 'superior' | 'core' | 'muslos' | 'piernas' | 'portero';

export interface AnatomicalTabInfo {
  id: AnatomicalTabCategory;
  label: string;
  badge?: string;
}

export const ANATOMICAL_TABS: AnatomicalTabInfo[] = [
  { id: 'todos', label: 'Todos los Músculos' },
  { id: 'superior', label: 'Tren Superior y Brazos' },
  { id: 'core', label: 'Core y Espalda' },
  { id: 'muslos', label: 'Muslos y Cadera' },
  { id: 'piernas', label: 'Piernas y Tobillos' },
  { id: 'portero', label: '🧤 Especial Portero' },
];

export function getTabCategoryForZone(zone: AnatomicalZone): AnatomicalTabCategory {
  if (zone.isGoalkeeperZone) return 'portero';
  const reg = (zone.generalRegion || '').toLowerCase();
  const grp = (zone.muscleGroup || '').toLowerCase();
  const name = (zone.name || '').toLowerCase();

  if (
    reg.includes('hombro') ||
    reg.includes('brazo') ||
    reg.includes('codo') ||
    reg.includes('antebrazo') ||
    reg.includes('muñeca') ||
    reg.includes('mano') ||
    grp.includes('brazo') ||
    grp.includes('codo') ||
    name.includes('deltoides') ||
    name.includes('bíceps braquial') ||
    name.includes('tríceps')
  ) {
    return 'superior';
  }
  if (
    reg.includes('core') ||
    reg.includes('tronco') ||
    reg.includes('espalda') ||
    grp.includes('abdominal') ||
    grp.includes('paravertebral') ||
    name.includes('recto abdominal') ||
    name.includes('oblicuo') ||
    name.includes('erectores')
  ) {
    return 'core';
  }
  if (
    reg.includes('muslo') ||
    reg.includes('cadera') ||
    reg.includes('ingle') ||
    grp.includes('isquiotibial') ||
    grp.includes('cuádriceps') ||
    grp.includes('aductor') ||
    grp.includes('flexores') ||
    name.includes('isquio') ||
    name.includes('femoral') ||
    name.includes('cuádriceps') ||
    name.includes('sartorio') ||
    name.includes('grácil') ||
    name.includes('psoas') ||
    name.includes('fascia lata') ||
    name.includes('pubis')
  ) {
    return 'muslos';
  }
  if (
    reg.includes('pantorrilla') ||
    reg.includes('pierna') ||
    reg.includes('tobillo') ||
    reg.includes('pie') ||
    grp.includes('gastrocnemio') ||
    grp.includes('sóleo') ||
    name.includes('gemelo') ||
    name.includes('sóleo') ||
    name.includes('tibial') ||
    name.includes('peroneo') ||
    name.includes('aquiles')
  ) {
    return 'piernas';
  }
  return 'superior';
}

export const QUICK_SELECT_LIST = [
  { key: 'cadera', label: 'Pubis (Pubalgia)', defaultCode: 'pubis' },
  { key: 'muslo_post', label: 'Cuádriceps', defaultCode: 'recto_anterior_der' },
  { key: 'pierna', label: 'Sóleo', defaultCode: 'soleo_der' },
  { key: 'muslo_post', label: 'Isquiotibiales', defaultCode: 'biceps_femoral_larga_der' },
  { key: 'rodilla', label: 'Ligamento (LCA)', defaultCode: 'ligamento_cruzado_ant_der' },
  { key: 'rodilla', label: 'Menisco Interno', defaultCode: 'menisco_interno_der' },
  { key: 'cadera', label: 'Aductores', defaultCode: 'aductor_largo_der' },
  { key: 'pierna', label: 'Gemelos', defaultCode: 'gastrocnemio_medial_der' },
  { key: 'tobillo', label: 'Ligamento Tobillo (LPAA)', defaultCode: 'tobillo_ligamentos_der' },
  { key: 'tobillo', label: 'Tendón Aquiles', defaultCode: 'tendon_aquiles_der' },
  { key: 'pie_meta', label: '5º Metatarso (Jones)', defaultCode: 'metatarso_5to_der' },
  { key: 'pie_tarso', label: 'Tarso (Navicular)', defaultCode: 'tarso_navicular_der' },
  { key: 'cadera', label: 'Glúteos', defaultCode: 'gluteo_mayor_der' },
  { key: 'cadera', label: 'Abdomen / Core', defaultCode: 'abdomen' },
  { key: 'hombro', label: 'Hombro', defaultCode: 'hombro_der' },
];

export function useAnatomySelection(initialZoneCode: string = '') {
  // Estado inicial limpio por defecto: NADA preseleccionado
  const [selectedCode, setSelectedCode] = useState<string>(initialZoneCode);
  const [hoveredCode, setHoveredCode] = useState<string | null>(null);
  const [cameraView, setCameraView] = useState<'frontal' | 'posterior' | 'lateral_izq' | 'lateral_der'>('frontal');

  const selectedZone = useMemo(() => {
    return selectedCode ? ANATOMICAL_ZONES[selectedCode] || null : null;
  }, [selectedCode]);

  const selectZone = useCallback((code: string) => {
    if (ANATOMICAL_ZONES[code]) {
      setSelectedCode(code);
      if (ANATOMICAL_ZONES[code].viewDefault) {
        setCameraView(ANATOMICAL_ZONES[code].viewDefault);
      }
    } else if (code === '') {
      setSelectedCode('');
    }
  }, []);

  return {
    selectedCode,
    selectedZone,
    hoveredCode,
    setHoveredCode,
    cameraView,
    setCameraView,
    selectZone,
  };
}
