import { useState, useMemo, useCallback } from 'react';

export interface AnatomicalZone {
  code: string;
  name: string;
  generalRegion: string;
  muscleGroup: string;
  laterality?: 'Izquierdo' | 'Derecho' | 'Bilateral' | 'No aplica';
  thumbnailKey?: string;
  viewDefault?: 'frontal' | 'posterior';
  incidencia?: 'Muy Alta' | 'Alta' | 'Moderada' | 'Leve' | 'Baja' | 'Grave';
  mecanismoComun?: string;
  munichDefault?: '1A' | '1B' | '2A' | '2B' | '3A' | '3B' | '4';
}

export const ANATOMICAL_ZONES: Record<string, AnatomicalZone> = {
  // === PUBIS / PUBALGIA / PELVIS ===
  pubis: {
    code: 'pubis',
    name: 'Pubis / Sínfisis Púbica (Pubalgia)',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Sínfisis Púbica y Entesis',
    laterality: 'No aplica',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Descompensación entre pared abdominal y aductores, cambios de dirección continuos y golpeo repetitivo de balón.',
    munichDefault: '2A',
  },
  pubis_der: {
    code: 'pubis_der',
    name: 'Pubis (Inserción Aductor Derecho)',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Sínfisis Púbica',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Entesopatía púbica por tracción excéntrica del aductor largo en frenadas y golpeo.',
    munichDefault: '3A',
  },
  pubis_izq: {
    code: 'pubis_izq',
    name: 'Pubis (Inserción Aductor Izquierdo)',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Sínfisis Púbica',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Entesopatía púbica por tracción excéntrica del aductor largo en frenadas y golpeo.',
    munichDefault: '3A',
  },

  // === CUÁDRICEPS (COMPLETO) ===
  cuadriceps_general_der: {
    code: 'cuadriceps_general_der',
    name: 'Cuádriceps Derecho (Global)',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Extensión forzada de rodilla en lanzamientos a portería y desaceleración brusca.',
    munichDefault: '3A',
  },
  cuadriceps_general_izq: {
    code: 'cuadriceps_general_izq',
    name: 'Cuádriceps Izquierdo (Global)',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Extensión forzada de rodilla en lanzamientos a portería y desaceleración brusca.',
    munichDefault: '3A',
  },
  recto_anterior_der: {
    code: 'recto_anterior_der',
    name: 'Recto anterior (Cuádriceps) Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Golpeo potente de balón con empeine, despejes al vuelo y sprint excéntrico.',
    munichDefault: '3B',
  },
  recto_anterior_izq: {
    code: 'recto_anterior_izq',
    name: 'Recto anterior (Cuádriceps) Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Golpeo potente de balón con empeine, despejes al vuelo y sprint excéntrico.',
    munichDefault: '3B',
  },
  vasto_lateral_der: {
    code: 'vasto_lateral_der',
    name: 'Vasto lateral (Cuádriceps) Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión forzada de rodilla en frenadas y desaceleraciones.',
    munichDefault: '3A',
  },
  vasto_lateral_izq: {
    code: 'vasto_lateral_izq',
    name: 'Vasto lateral (Cuádriceps) Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión forzada de rodilla en frenadas y desaceleraciones.',
    munichDefault: '3A',
  },
  vasto_medial_der: {
    code: 'vasto_medial_der',
    name: 'Vasto medial (Cuádriceps) Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Fallo de estabilización rotuliana en apoyos y giros con carga monopodal.',
    munichDefault: '2B',
  },
  vasto_medial_izq: {
    code: 'vasto_medial_izq',
    name: 'Vasto medial (Cuádriceps) Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Fallo de estabilización rotuliana en apoyos y giros con carga monopodal.',
    munichDefault: '2B',
  },
  vasto_intermedio_der: {
    code: 'vasto_intermedio_der',
    name: 'Vasto intermedio (Crural) Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Contusión directa ("bocadillo") o sobrecarga profunda por cargas de choque.',
    munichDefault: '3A',
  },
  vasto_intermedio_izq: {
    code: 'vasto_intermedio_izq',
    name: 'Vasto intermedio (Crural) Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Cuádriceps femoral',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Contusión directa ("bocadillo") o sobrecarga profunda por cargas de choque.',
    munichDefault: '3A',
  },
  tendon_cuadricipital_der: {
    code: 'tendon_cuadricipital_der',
    name: 'Tendón cuadricipital Derecho',
    generalRegion: 'Rodilla / Muslo',
    muscleGroup: 'Aparato extensor',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Carga excéntrica masiva al frenar o caer de un salto.',
    munichDefault: '4',
  },
  tendon_cuadricipital_izq: {
    code: 'tendon_cuadricipital_izq',
    name: 'Tendón cuadricipital Izquierdo',
    generalRegion: 'Rodilla / Muslo',
    muscleGroup: 'Aparato extensor',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Carga excéntrica masiva al frenar o caer de un salto.',
    munichDefault: '4',
  },
  sartorio_der: {
    code: 'sartorio_der',
    name: 'Sartorio Derecho',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Flexores de Cadera / Muslo',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Flexión combinada de cadera y rotación externa de rodilla en conducciones.',
    munichDefault: '1A',
  },
  sartorio_izq: {
    code: 'sartorio_izq',
    name: 'Sartorio Izquierdo',
    generalRegion: 'Muslo Anterior',
    muscleGroup: 'Flexores de Cadera / Muslo',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Flexión combinada de cadera y rotación externa de rodilla en conducciones.',
    munichDefault: '1A',
  },

  // === SÓLEO Y PANTORRILLA ===
  soleo_der: {
    code: 'soleo_der',
    name: 'Sóleo Derecho',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Alta',
    mecanismoComun: 'Fatiga continua, carreras de fondo a media intensidad y acumulación de partidos.',
    munichDefault: '2A',
  },
  soleo_izq: {
    code: 'soleo_izq',
    name: 'Sóleo Izquierdo',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Alta',
    mecanismoComun: 'Fatiga continua, carreras de fondo a media intensidad y acumulación de partidos.',
    munichDefault: '2A',
  },
  gastrocnemio_medial_der: {
    code: 'gastrocnemio_medial_der',
    name: 'Gemelo interno (Gastrocnemio medial) Der.',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Arrancadas explosivas, saltos de cabeza y extensión brusca de rodilla con flexión dorsal.',
    munichDefault: '3B',
  },
  gastrocnemio_medial_izq: {
    code: 'gastrocnemio_medial_izq',
    name: 'Gemelo interno (Gastrocnemio medial) Izq.',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Arrancadas explosivas, saltos de cabeza y extensión brusca de rodilla con flexión dorsal.',
    munichDefault: '3B',
  },
  gastrocnemio_lateral_der: {
    code: 'gastrocnemio_lateral_der',
    name: 'Gemelo externo (Gastrocnemio lateral) Der.',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión brusca de tobillo y recepción forzada en apoyo en carrera.',
    munichDefault: '3A',
  },
  gastrocnemio_lateral_izq: {
    code: 'gastrocnemio_lateral_izq',
    name: 'Gemelo externo (Gastrocnemio lateral) Izq.',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Tríceps sural',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión brusca de tobillo y recepción forzada en apoyo en carrera.',
    munichDefault: '3A',
  },
  plantar_delgado_der: {
    code: 'plantar_delgado_der',
    name: 'Plantar delgado Derecho',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Pantorrilla',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Sensación súbita de "pedrada" o chasquido en aceleración brusca.',
    munichDefault: '3A',
  },
  plantar_delgado_izq: {
    code: 'plantar_delgado_izq',
    name: 'Plantar delgado Izquierdo',
    generalRegion: 'Pierna / Pantorrilla',
    muscleGroup: 'Pantorrilla',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Sensación súbita de "pedrada" o chasquido en aceleración brusca.',
    munichDefault: '3A',
  },
  tibial_anterior_der: {
    code: 'tibial_anterior_der',
    name: 'Tibial anterior Derecho',
    generalRegion: 'Pierna Anterior',
    muscleGroup: 'Compartimento anterior',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Sobrecarga por golpeo repetitivo de balón y superficies de césped duro.',
    munichDefault: '1A',
  },
  tibial_anterior_izq: {
    code: 'tibial_anterior_izq',
    name: 'Tibial anterior Izquierdo',
    generalRegion: 'Pierna Anterior',
    muscleGroup: 'Compartimento anterior',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Sobrecarga por golpeo repetitivo de balón y superficies de césped duro.',
    munichDefault: '1A',
  },
  peroneos_der: {
    code: 'peroneos_der',
    name: 'Peroneos (Largo / Corto) Derecho',
    generalRegion: 'Pierna Lateral',
    muscleGroup: 'Compartimento lateral',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Tendinopatía o luxación de retináculo peroneo tras inversión forzada de tobillo.',
    munichDefault: '3A',
  },
  peroneos_izq: {
    code: 'peroneos_izq',
    name: 'Peroneos (Largo / Corto) Izquierdo',
    generalRegion: 'Pierna Lateral',
    muscleGroup: 'Compartimento lateral',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Tendinopatía o luxación de retináculo peroneo tras inversión forzada de tobillo.',
    munichDefault: '3A',
  },

  // === ISQUIOTIBIALES ===
  isquiotibiales_der: {
    code: 'isquiotibiales_der',
    name: 'Isquiotibiales Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Sprints a máxima velocidad en fase de desaceleración / oscilación tardía.',
    munichDefault: '3B',
  },
  isquiotibiales_izq: {
    code: 'isquiotibiales_izq',
    name: 'Isquiotibiales Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Sprints a máxima velocidad en fase de desaceleración / oscilación tardía.',
    munichDefault: '3B',
  },
  biceps_femoral_larga_der: {
    code: 'biceps_femoral_larga_der',
    name: 'Bíceps femoral (Cabeza larga) Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Sprints a máxima velocidad en fase de desaceleración / oscilación tardía.',
    munichDefault: '3B',
  },
  biceps_femoral_larga_izq: {
    code: 'biceps_femoral_larga_izq',
    name: 'Bíceps femoral (Cabeza larga) Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Sprints a máxima velocidad en fase de desaceleración / oscilación tardía.',
    munichDefault: '3B',
  },
  biceps_femoral_corta_der: {
    code: 'biceps_femoral_corta_der',
    name: 'Bíceps femoral (Cabeza corta) Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Baja',
    mecanismoComun: 'Desaceleraciones bruscas y flexión pronunciada de rodilla.',
    munichDefault: '3A',
  },
  biceps_femoral_corta_izq: {
    code: 'biceps_femoral_corta_izq',
    name: 'Bíceps femoral (Cabeza corta) Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Baja',
    mecanismoComun: 'Desaceleraciones bruscas y flexión pronunciada de rodilla.',
    munichDefault: '3A',
  },
  semitendinoso_der: {
    code: 'semitendinoso_der',
    name: 'Semitendinoso Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Alta',
    mecanismoComun: 'Aceleraciones súbitas y cambios de ritmo durante transiciones ofensivas.',
    munichDefault: '3A',
  },
  semitendinoso_izq: {
    code: 'semitendinoso_izq',
    name: 'Semitendinoso Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Alta',
    mecanismoComun: 'Aceleraciones súbitas y cambios de ritmo durante transiciones ofensivas.',
    munichDefault: '3A',
  },
  semimembranoso_der: {
    code: 'semimembranoso_der',
    name: 'Semimembranoso Derecho',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Frenadas bruscas, estiramientos forzados y golpeos en extensión de cadera.',
    munichDefault: '3B',
  },
  semimembranoso_izq: {
    code: 'semimembranoso_izq',
    name: 'Semimembranoso Izquierdo',
    generalRegion: 'Isquiotibiales',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Frenadas bruscas, estiramientos forzados y golpeos en extensión de cadera.',
    munichDefault: '3B',
  },

  // === ADUCTORES E INGLE ===
  aductor_largo_der: {
    code: 'aductor_largo_der',
    name: 'Aductor largo Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Cambios de dirección bruscos, golpeo con empeine interior y pubalgia.',
    munichDefault: '3A',
  },
  aductor_largo_izq: {
    code: 'aductor_largo_izq',
    name: 'Aductor largo Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Cambios de dirección bruscos, golpeo con empeine interior y pubalgia.',
    munichDefault: '3A',
  },
  aductor_mayor_der: {
    code: 'aductor_mayor_der',
    name: 'Aductor mayor Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Aperturas forzadas de piernas, estiramientos y caídas en tijera.',
    munichDefault: '3B',
  },
  aductor_mayor_izq: {
    code: 'aductor_mayor_izq',
    name: 'Aductor mayor Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Aperturas forzadas de piernas, estiramientos y caídas en tijera.',
    munichDefault: '3B',
  },
  gracilis_der: {
    code: 'gracilis_der',
    name: 'Gracilis (Recto interno) Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Aducción combinada con flexión de rodilla en controles orientados.',
    munichDefault: '1A',
  },
  gracilis_izq: {
    code: 'gracilis_izq',
    name: 'Gracilis (Recto interno) Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Aductores',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Aducción combinada con flexión de rodilla en controles orientados.',
    munichDefault: '1A',
  },
  psoas_der: {
    code: 'psoas_der',
    name: 'Psoas ilíaco Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Flexores de Cadera',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Hiperextensión brusca de cadera o golpeos al aire sin balón.',
    munichDefault: '2A',
  },
  psoas_izq: {
    code: 'psoas_izq',
    name: 'Psoas ilíaco Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Flexores de Cadera',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Hiperextensión brusca de cadera o golpeos al aire sin balón.',
    munichDefault: '2A',
  },
  pectineo_der: {
    code: 'pectineo_der',
    name: 'Pectíneo Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Flexores / Aductores',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Movimientos explosivos de flexión y aducción de cadera en espacios reducidos.',
    munichDefault: '1A',
  },
  pectineo_izq: {
    code: 'pectineo_izq',
    name: 'Pectíneo Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Flexores / Aductores',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Movimientos explosivos de flexión y aducción de cadera en espacios reducidos.',
    munichDefault: '1A',
  },

  // === ROTURAS DE LIGAMENTOS Y MENISCOS (RODILLA) ===
  ligamento_cruzado_ant_der: {
    code: 'ligamento_cruzado_ant_der',
    name: 'Rotura Ligamento Cruzado Anterior (LCA) Der.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Pivote central de rodilla',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Valgo forzado con rotación externa y desaceleración sin contacto (mecanismo clásico LCA).',
    munichDefault: '4',
  },
  ligamento_cruzado_ant_izq: {
    code: 'ligamento_cruzado_ant_izq',
    name: 'Rotura Ligamento Cruzado Anterior (LCA) Izq.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Pivote central de rodilla',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Valgo forzado con rotación externa y desaceleración sin contacto (mecanismo clásico LCA).',
    munichDefault: '4',
  },
  ligamento_cruzado_post_der: {
    code: 'ligamento_cruzado_post_der',
    name: 'Rotura Ligamento Cruzado Posterior (LCP) Der.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Pivote central de rodilla',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'posterior',
    incidencia: 'Grave',
    mecanismoComun: 'Impacto directo contra la tibia proximal con la rodilla flexionada (choque con rival o poste).',
    munichDefault: '4',
  },
  ligamento_cruzado_post_izq: {
    code: 'ligamento_cruzado_post_izq',
    name: 'Rotura Ligamento Cruzado Posterior (LCP) Izq.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Pivote central de rodilla',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'posterior',
    incidencia: 'Grave',
    mecanismoComun: 'Impacto directo contra la tibia proximal con la rodilla flexionada (choque con rival o poste).',
    munichDefault: '4',
  },
  ligamento_colateral_medial_der: {
    code: 'ligamento_colateral_medial_der',
    name: 'Ligamento Colateral Medial / Interno (LCM) Der.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Estabilidad lateral de rodilla',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Traumatismo directo en la cara externa de la rodilla forzando apertura medial en valgo.',
    munichDefault: '3A',
  },
  ligamento_colateral_medial_izq: {
    code: 'ligamento_colateral_medial_izq',
    name: 'Ligamento Colateral Medial / Interno (LCM) Izq.',
    generalRegion: 'Rodilla',
    muscleGroup: 'Estabilidad lateral de rodilla',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Traumatismo directo en la cara externa de la rodilla forzando apertura medial en valgo.',
    munichDefault: '3A',
  },
  menisco_interno_der: {
    code: 'menisco_interno_der',
    name: 'Rotura Menisco Interno (Medial) Derecho',
    generalRegion: 'Rodilla',
    muscleGroup: 'Meniscos y fibrocartílago',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Torsión brusca de rodilla con el pie fijo en el césped en flexión (rotura en asa de cubo o cuerno posterior).',
    munichDefault: '3B',
  },
  menisco_interno_izq: {
    code: 'menisco_interno_izq',
    name: 'Rotura Menisco Interno (Medial) Izquierdo',
    generalRegion: 'Rodilla',
    muscleGroup: 'Meniscos y fibrocartílago',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Alta',
    mecanismoComun: 'Torsión brusca de rodilla con el pie fijo en el césped en flexión (rotura en asa de cubo o cuerno posterior).',
    munichDefault: '3B',
  },
  menisco_externo_der: {
    code: 'menisco_externo_der',
    name: 'Rotura Menisco Externo (Lateral) Derecho',
    generalRegion: 'Rodilla',
    muscleGroup: 'Meniscos y fibrocartílago',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Impacto o torsión con carga en varo rotacional en frenadas bruscas.',
    munichDefault: '3B',
  },
  menisco_externo_izq: {
    code: 'menisco_externo_izq',
    name: 'Rotura Menisco Externo (Lateral) Izquierdo',
    generalRegion: 'Rodilla',
    muscleGroup: 'Meniscos y fibrocartílago',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Impacto o torsión con carga en varo rotacional en frenadas bruscas.',
    munichDefault: '3B',
  },
  tendon_rotuliano_der: {
    code: 'tendon_rotuliano_der',
    name: 'Tendón rotuliano Derecho',
    generalRegion: 'Rodilla',
    muscleGroup: 'Aparato extensor',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Impactos reiterados de salto, frenado en carrera e hiperpresión patelar ("rodilla del saltador").',
    munichDefault: '3B',
  },
  tendon_rotuliano_izq: {
    code: 'tendon_rotuliano_izq',
    name: 'Tendón rotuliano Izquierdo',
    generalRegion: 'Rodilla',
    muscleGroup: 'Aparato extensor',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Impactos reiterados de salto, frenado en carrera e hiperpresión patelar ("rodilla del saltador").',
    munichDefault: '3B',
  },

  // === LIGAMENTOS DE TOBILLO Y TENDÓN DE AQUILES ===
  tendon_aquiles_der: {
    code: 'tendon_aquiles_der',
    name: 'Rotura / Tendinopatía Aquiles Derecho',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Tendón calcáneo',
    laterality: 'Derecho',
    thumbnailKey: 'tobillo',
    viewDefault: 'posterior',
    incidencia: 'Grave',
    mecanismoComun: 'Despegues explosivos, caídas descompensadas y microtraumatismo reiterado.',
    munichDefault: '4',
  },
  tendon_aquiles_izq: {
    code: 'tendon_aquiles_izq',
    name: 'Rotura / Tendinopatía Aquiles Izquierdo',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Tendón calcáneo',
    laterality: 'Izquierdo',
    thumbnailKey: 'tobillo',
    viewDefault: 'posterior',
    incidencia: 'Grave',
    mecanismoComun: 'Despegues explosivos, caídas descompensadas y microtraumatismo reiterado.',
    munichDefault: '4',
  },
  tobillo_ligamentos_der: {
    code: 'tobillo_ligamentos_der',
    name: 'Rotura / Esguince Ligamentos Tobillo (LPAA) Der.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Complejo ligamentoso lateral',
    laterality: 'Derecho',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Inversión forzada con flexión plantar al pisar a un rival o irregularidad del terreno.',
    munichDefault: '3A',
  },
  tobillo_ligamentos_izq: {
    code: 'tobillo_ligamentos_izq',
    name: 'Rotura / Esguince Ligamentos Tobillo (LPAA) Izq.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Complejo ligamentoso lateral',
    laterality: 'Izquierdo',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
    incidencia: 'Muy Alta',
    mecanismoComun: 'Inversión forzada con flexión plantar al pisar a un rival o irregularidad del terreno.',
    munichDefault: '3A',
  },
  sindesmosis_tobillo_der: {
    code: 'sindesmosis_tobillo_der',
    name: 'Esguince Sindesmosis Tibioperonea (Esguince Alto) Der.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Sindesmosis tibioperonea',
    laterality: 'Derecho',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Rotación externa forzada del pie con dorsiflexión máxima tras entrada lateral.',
    munichDefault: '3B',
  },
  sindesmosis_tobillo_izq: {
    code: 'sindesmosis_tobillo_izq',
    name: 'Esguince Sindesmosis Tibioperonea (Esguince Alto) Izq.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Sindesmosis tibioperonea',
    laterality: 'Izquierdo',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Rotación externa forzada del pie con dorsiflexión máxima tras entrada lateral.',
    munichDefault: '3B',
  },

  // === TARSO Y METATARSO (PIE) ===
  tarso_navicular_der: {
    code: 'tarso_navicular_der',
    name: 'Tarso / Escafoides Tarsiano (Navicular) Der.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Huesos del Tarso',
    laterality: 'Derecho',
    thumbnailKey: 'pie_tarso',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Fractura por estrés del escafoides tarsiano por impacto continuo y flexión dorsal forzada.',
    munichDefault: '4',
  },
  tarso_navicular_izq: {
    code: 'tarso_navicular_izq',
    name: 'Tarso / Escafoides Tarsiano (Navicular) Izq.',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Huesos del Tarso',
    laterality: 'Izquierdo',
    thumbnailKey: 'pie_tarso',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Fractura por estrés del escafoides tarsiano por impacto continuo y flexión dorsal forzada.',
    munichDefault: '4',
  },
  metatarso_5to_der: {
    code: 'metatarso_5to_der',
    name: '5º Metatarsiano (Fractura de Jones) Derecho',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Metatarso',
    laterality: 'Derecho',
    thumbnailKey: 'pie_meta',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Inversión violenta del mediopié durante cambios de dirección o pisadas en falso (zona de Jones).',
    munichDefault: '4',
  },
  metatarso_5to_izq: {
    code: 'metatarso_5to_izq',
    name: '5º Metatarsiano (Fractura de Jones) Izquierdo',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Metatarso',
    laterality: 'Izquierdo',
    thumbnailKey: 'pie_meta',
    viewDefault: 'frontal',
    incidencia: 'Grave',
    mecanismoComun: 'Inversión violenta del mediopié durante cambios de dirección o pisadas en falso (zona de Jones).',
    munichDefault: '4',
  },
  metatarso_general_der: {
    code: 'metatarso_general_der',
    name: 'Metatarsalgia / Metatarsos (1º a 4º) Derecho',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Metatarso',
    laterality: 'Derecho',
    thumbnailKey: 'pie_meta',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Periostitis o microfracturas por estrés por tacos sobre césped artificial duro.',
    munichDefault: '3A',
  },
  metatarso_general_izq: {
    code: 'metatarso_general_izq',
    name: 'Metatarsalgia / Metatarsos (1º a 4º) Izquierdo',
    generalRegion: 'Tobillo y Pie',
    muscleGroup: 'Metatarso',
    laterality: 'Izquierdo',
    thumbnailKey: 'pie_meta',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Periostitis o microfracturas por estrés por tacos sobre césped artificial duro.',
    munichDefault: '3A',
  },

  // === GLÚTEOS Y CADERA ===
  gluteo_mayor_der: {
    code: 'gluteo_mayor_der',
    name: 'Glúteo mayor Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Glúteos',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión potente de cadera, despegue en saltos y aceleraciones iniciales.',
    munichDefault: '3A',
  },
  gluteo_mayor_izq: {
    code: 'gluteo_mayor_izq',
    name: 'Glúteo mayor Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Glúteos',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Extensión potente de cadera, despegue en saltos y aceleraciones iniciales.',
    munichDefault: '3A',
  },
  gluteo_medio_der: {
    code: 'gluteo_medio_der',
    name: 'Glúteo medio / menor Derecho',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Glúteos',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Cambios de dirección, apoyos monopodales forzados e inestabilidad pélvica.',
    munichDefault: '2B',
  },
  gluteo_medio_izq: {
    code: 'gluteo_medio_izq',
    name: 'Glúteo medio / menor Izquierdo',
    generalRegion: 'Pelvis / Cadera / Ingle',
    muscleGroup: 'Glúteos',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Cambios de dirección, apoyos monopodales forzados e inestabilidad pélvica.',
    munichDefault: '2B',
  },

  // === TRONCO Y ZONAS SUPERIORES ===
  abdomen: {
    code: 'abdomen',
    name: 'Recto abdominal / Oblicuos (Core)',
    generalRegion: 'Tronco',
    muscleGroup: 'Pared abdominal',
    laterality: 'No aplica',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Torsiones forzadas de tronco en disputas aéreas y remates descompensados.',
    munichDefault: '2A',
  },
  lumbar: {
    code: 'lumbar',
    name: 'Zona Lumbar / Paravertebrales',
    generalRegion: 'Tronco',
    muscleGroup: 'Erectores de columna',
    laterality: 'No aplica',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
    incidencia: 'Moderada',
    mecanismoComun: 'Sobrecargas mecánicas por impacto, choque de cargas y frenadas repetitivas.',
    munichDefault: '2A',
  },
  pecho: {
    code: 'pecho',
    name: 'Pectoral / Tórax',
    generalRegion: 'Tronco',
    muscleGroup: 'Pectoral',
    laterality: 'No aplica',
    thumbnailKey: 'brazo',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Contusiones por choque con rivales o caídas al suelo.',
    munichDefault: '1A',
  },
  dorsal: {
    code: 'dorsal',
    name: 'Dorsal ancho / Espalda alta',
    generalRegion: 'Tronco',
    muscleGroup: 'Espalda',
    laterality: 'No aplica',
    thumbnailKey: 'cuello',
    viewDefault: 'posterior',
    incidencia: 'Leve',
    mecanismoComun: 'Tirones en disputas de agarre y apoyos en salto.',
    munichDefault: '1A',
  },
  hombro_der: {
    code: 'hombro_der',
    name: 'Hombro / Manguito rotador Derecho',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Hombro',
    laterality: 'Derecho',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Caídas sobre el brazo extendido o luxaciones glenohumerales en porteros.',
    munichDefault: '3A',
  },
  hombro_izq: {
    code: 'hombro_izq',
    name: 'Hombro / Manguito rotador Izquierdo',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Hombro',
    laterality: 'Izquierdo',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Caídas sobre el brazo extendido o luxaciones glenohumerales en porteros.',
    munichDefault: '3A',
  },
  cuello: {
    code: 'cuello',
    name: 'Cuello / Cervical',
    generalRegion: 'Cabeza y cuello',
    muscleGroup: 'Trapecio y Esternocleidomastoideo',
    laterality: 'No aplica',
    thumbnailKey: 'cuello',
    viewDefault: 'frontal',
    incidencia: 'Leve',
    mecanismoComun: 'Latigazo cervical en remates forzados de cabeza o colisiones aéreas.',
    munichDefault: '1A',
  },
  cabeza: {
    code: 'cabeza',
    name: 'Cabeza / Región Craneofacial',
    generalRegion: 'Cabeza y cuello',
    muscleGroup: 'Craneofacial',
    laterality: 'No aplica',
    thumbnailKey: 'cabeza',
    viewDefault: 'frontal',
    incidencia: 'Moderada',
    mecanismoComun: 'Impactos fortuitos cabeza con cabeza, golpes de codo o conmoción deportiva.',
    munichDefault: '1A',
  },
};

export const QUICK_SELECT_LIST = [
  { key: 'cadera', label: 'Pubis (Pubalgia)', defaultCode: 'pubis' },
  { key: 'muslo_post', label: 'Cuádriceps', defaultCode: 'recto_anterior_der' },
  { key: 'pierna', label: 'Sóleo', defaultCode: 'soleo_der' },
  { key: 'muslo_post', label: 'Isquiotibiales', defaultCode: 'biceps_femoral_larga_der' },
  { key: 'rodilla', label: 'Ligamento (LCA)', defaultCode: 'ligamento_cruzado_ant_der' },
  { key: 'rodilla', label: 'Menisco Interno', defaultCode: 'menisco_interno_der' },
  { key: 'cadera', label: 'Aductores', defaultCode: 'aductor_largo_der' },
  { key: 'pierna', label: 'Gemelos', defaultCode: 'gastrocnemio_medial_der' },
  { key: 'tobillo', label: 'Ligamento Tobillo (LPAA)', defaultCode: 'tobillo_ligamentos_der' },
  { key: 'tobillo', label: 'Tendón Aquiles', defaultCode: 'tendon_aquiles_der' },
  { key: 'pie_meta', label: '5º Metatarso (Jones)', defaultCode: 'metatarso_5to_der' },
  { key: 'pie_tarso', label: 'Tarso (Navicular)', defaultCode: 'tarso_navicular_der' },
  { key: 'cadera', label: 'Glúteos', defaultCode: 'gluteo_mayor_der' },
  { key: 'cadera', label: 'Abdomen / Core', defaultCode: 'abdomen' },
  { key: 'hombro', label: 'Hombro', defaultCode: 'hombro_der' },
];

export function useAnatomySelection(initialZoneCode: string = '') {
  // Estado inicial limpio por defecto: NADA preseleccionado
  const [selectedCode, setSelectedCode] = useState<string>(initialZoneCode);
  const [hoveredCode, setHoveredCode] = useState<string | null>(null);
  const [cameraView, setCameraView] = useState<'frontal' | 'posterior' | 'lateral_izq' | 'lateral_der'>('frontal');

  const selectedZone = useMemo(() => {
    return selectedCode ? ANATOMICAL_ZONES[selectedCode] || null : null;
  }, [selectedCode]);

  const selectZone = useCallback((code: string) => {
    if (ANATOMICAL_ZONES[code]) {
      setSelectedCode(code);
      if (ANATOMICAL_ZONES[code].viewDefault) {
        setCameraView(ANATOMICAL_ZONES[code].viewDefault);
      }
    } else if (code === '') {
      setSelectedCode('');
    }
  }, []);

  return {
    selectedCode,
    selectedZone,
    hoveredCode,
    setHoveredCode,
    cameraView,
    setCameraView,
    selectZone,
  };
}
