import { useState, useMemo, useCallback } from 'react';

export interface AnatomicalZone {
  code: string;
  name: string;
  generalRegion: string;
  muscleGroup: string;
  laterality?: 'Izquierdo' | 'Derecho' | 'Bilateral' | 'No aplica';
  thumbnailKey?: string;
  viewDefault?: 'frontal' | 'posterior';
}

export const ANATOMICAL_ZONES: Record<string, AnatomicalZone> = {
  isquiotibiales_der: {
    code: 'isquiotibiales_der',
    name: 'Isquiotibiales Derecho',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
  },
  isquiotibiales_izq: {
    code: 'isquiotibiales_izq',
    name: 'Isquiotibiales Izquierdo',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Isquiotibiales',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
  },
  cuadriceps_der: {
    code: 'cuadriceps_der',
    name: 'Cuádriceps Derecho',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Cuádriceps (Recto anterior)',
    laterality: 'Derecho',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
  },
  cuadriceps_izq: {
    code: 'cuadriceps_izq',
    name: 'Cuádriceps Izquierdo',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Cuádriceps (Recto anterior)',
    laterality: 'Izquierdo',
    thumbnailKey: 'muslo_post',
    viewDefault: 'frontal',
  },
  aductor_der: {
    code: 'aductor_der',
    name: 'Aductor Derecho',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Aductores / Ingle',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
  },
  aductor_izq: {
    code: 'aductor_izq',
    name: 'Aductor Izquierdo',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Aductores / Ingle',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
  },
  gemelos_der: {
    code: 'gemelos_der',
    name: 'Gemelo Derecho',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Gastrocnemio / Sóleo',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
  },
  gemelos_izq: {
    code: 'gemelos_izq',
    name: 'Gemelo Izquierdo',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Gastrocnemio / Sóleo',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'posterior',
  },
  rodilla_der: {
    code: 'rodilla_der',
    name: 'Rodilla Derecha',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Rodilla y Tendón Rotuliano',
    laterality: 'Derecho',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
  },
  rodilla_izq: {
    code: 'rodilla_izq',
    name: 'Rodilla Izquierda',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Rodilla y Tendón Rotuliano',
    laterality: 'Izquierdo',
    thumbnailKey: 'rodilla',
    viewDefault: 'frontal',
  },
  tobillo_der: {
    code: 'tobillo_der',
    name: 'Tobillo Derecho',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Ligamentos del Tobillo',
    laterality: 'Derecho',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
  },
  tobillo_izq: {
    code: 'tobillo_izq',
    name: 'Tobillo Izquierdo',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Ligamentos del Tobillo',
    laterality: 'Izquierdo',
    thumbnailKey: 'tobillo',
    viewDefault: 'frontal',
  },
  pie_tarso_der: {
    code: 'pie_tarso_der',
    name: 'Pie (tarso) Derecho',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Tarso y Fascia Plantar',
    laterality: 'Derecho',
    thumbnailKey: 'pie_tarso',
    viewDefault: 'frontal',
  },
  pie_tarso_izq: {
    code: 'pie_tarso_izq',
    name: 'Pie (tarso) Izquierdo',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Tarso y Fascia Plantar',
    laterality: 'Izquierdo',
    thumbnailKey: 'pie_tarso',
    viewDefault: 'frontal',
  },
  dedos_der: {
    code: 'dedos_der',
    name: 'Dedos / Metatarso Derecho',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Metatarsos y Falanges',
    laterality: 'Derecho',
    thumbnailKey: 'dedos',
    viewDefault: 'frontal',
  },
  dedos_izq: {
    code: 'dedos_izq',
    name: 'Dedos / Metatarso Izquierdo',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Metatarsos y Falanges',
    laterality: 'Izquierdo',
    thumbnailKey: 'dedos',
    viewDefault: 'frontal',
  },
  pierna_der: {
    code: 'pierna_der',
    name: 'Pierna (Tibia) Derecha',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Tibial anterior / Peroneos',
    laterality: 'Derecho',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
  },
  pierna_izq: {
    code: 'pierna_izq',
    name: 'Pierna (Tibia) Izquierda',
    generalRegion: 'Miembros inferiores',
    muscleGroup: 'Tibial anterior / Peroneos',
    laterality: 'Izquierdo',
    thumbnailKey: 'pierna',
    viewDefault: 'frontal',
  },
  cadera: {
    code: 'cadera',
    name: 'Cadera / Pelvis',
    generalRegion: 'Tronco inferior',
    muscleGroup: 'Cadera y Flexores',
    laterality: 'No aplica',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
  },
  gluteo_der: {
    code: 'gluteo_der',
    name: 'Glúteo Derecho',
    generalRegion: 'Tronco inferior',
    muscleGroup: 'Glúteo mayor / mediano',
    laterality: 'Derecho',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
  },
  gluteo_izq: {
    code: 'gluteo_izq',
    name: 'Glúteo Izquierdo',
    generalRegion: 'Tronco inferior',
    muscleGroup: 'Glúteo mayor / mediano',
    laterality: 'Izquierdo',
    thumbnailKey: 'cadera',
    viewDefault: 'posterior',
  },
  abdomen: {
    code: 'abdomen',
    name: 'Abdomen / Core',
    generalRegion: 'Tronco',
    muscleGroup: 'Recto abdominal y Oblicuos',
    laterality: 'No aplica',
    thumbnailKey: 'cadera',
    viewDefault: 'frontal',
  },
  pecho: {
    code: 'pecho',
    name: 'Pectoral / Pecho',
    generalRegion: 'Tronco',
    muscleGroup: 'Pectoral mayor y menor',
    laterality: 'No aplica',
    thumbnailKey: 'brazo',
    viewDefault: 'frontal',
  },
  dorsal: {
    code: 'dorsal',
    name: 'Espalda / Dorsal ancho',
    generalRegion: 'Tronco',
    muscleGroup: 'Dorsal y Trapecio medio',
    laterality: 'No aplica',
    thumbnailKey: 'cuello',
    viewDefault: 'posterior',
  },
  lumbar: {
    code: 'lumbar',
    name: 'Zona Lumbar',
    generalRegion: 'Tronco',
    muscleGroup: 'Erectores espinales lumbares',
    laterality: 'No aplica',
    thumbnailKey: 'muslo_post',
    viewDefault: 'posterior',
  },
  hombro_der: {
    code: 'hombro_der',
    name: 'Hombro Derecho',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Deltoides y Manguito rotador',
    laterality: 'Derecho',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
  },
  hombro_izq: {
    code: 'hombro_izq',
    name: 'Hombro Izquierdo',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Deltoides y Manguito rotador',
    laterality: 'Izquierdo',
    thumbnailKey: 'hombro',
    viewDefault: 'frontal',
  },
  brazo_der: {
    code: 'brazo_der',
    name: 'Brazo Derecho',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Bíceps / Tríceps braquial',
    laterality: 'Derecho',
    thumbnailKey: 'brazo',
    viewDefault: 'frontal',
  },
  brazo_izq: {
    code: 'brazo_izq',
    name: 'Brazo Izquierdo',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Bíceps / Tríceps braquial',
    laterality: 'Izquierdo',
    thumbnailKey: 'brazo',
    viewDefault: 'frontal',
  },
  codo_der: {
    code: 'codo_der',
    name: 'Codo Derecho',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Epicóndilos y Cápsula articular',
    laterality: 'Derecho',
    thumbnailKey: 'codo',
    viewDefault: 'frontal',
  },
  codo_izq: {
    code: 'codo_izq',
    name: 'Codo Izquierdo',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Epicóndilos y Cápsula articular',
    laterality: 'Izquierdo',
    thumbnailKey: 'codo',
    viewDefault: 'frontal',
  },
  antebrazo_der: {
    code: 'antebrazo_der',
    name: 'Antebrazo Derecho',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Flexores y Extensores de muñeca',
    laterality: 'Derecho',
    thumbnailKey: 'antebrazo',
    viewDefault: 'frontal',
  },
  antebrazo_izq: {
    code: 'antebrazo_izq',
    name: 'Antebrazo Izquierdo',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Flexores y Extensores de muñeca',
    laterality: 'Izquierdo',
    thumbnailKey: 'antebrazo',
    viewDefault: 'frontal',
  },
  muneca_der: {
    code: 'muneca_der',
    name: 'Muñeca Derecha',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Articulación radiocarpiana',
    laterality: 'Derecho',
    thumbnailKey: 'muneca',
    viewDefault: 'frontal',
  },
  muneca_izq: {
    code: 'muneca_izq',
    name: 'Muñeca Izquierda',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Articulación radiocarpiana',
    laterality: 'Izquierdo',
    thumbnailKey: 'muneca',
    viewDefault: 'frontal',
  },
  mano_der: {
    code: 'mano_der',
    name: 'Mano Derecha',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Metacarpo y Dedos',
    laterality: 'Derecho',
    thumbnailKey: 'mano',
    viewDefault: 'frontal',
  },
  mano_izq: {
    code: 'mano_izq',
    name: 'Mano Izquierda',
    generalRegion: 'Miembros superiores',
    muscleGroup: 'Metacarpo y Dedos',
    laterality: 'Izquierdo',
    thumbnailKey: 'mano',
    viewDefault: 'frontal',
  },
  cuello: {
    code: 'cuello',
    name: 'Cuello / Cervical',
    generalRegion: 'Cabeza y cuello',
    muscleGroup: 'Trapecio superior y Esternocleidomastoideo',
    laterality: 'No aplica',
    thumbnailKey: 'cuello',
    viewDefault: 'frontal',
  },
  cabeza: {
    code: 'cabeza',
    name: 'Cabeza / Facial',
    generalRegion: 'Cabeza y cuello',
    muscleGroup: 'Región craneofacial',
    laterality: 'No aplica',
    thumbnailKey: 'cabeza',
    viewDefault: 'frontal',
  },
};

export const QUICK_SELECT_LIST = [
  { key: 'cabeza', label: 'Cabeza', defaultCode: 'cabeza' },
  { key: 'cuello', label: 'Cuello', defaultCode: 'cuello' },
  { key: 'hombro', label: 'Hombro', defaultCode: 'hombro_der' },
  { key: 'brazo', label: 'Brazo', defaultCode: 'brazo_der' },
  { key: 'codo', label: 'Codo', defaultCode: 'codo_der' },
  { key: 'antebrazo', label: 'Antebrazo', defaultCode: 'antebrazo_der' },
  { key: 'muneca', label: 'Muñeca', defaultCode: 'muneca_der' },
  { key: 'mano', label: 'Mano', defaultCode: 'mano_der' },
  { key: 'cadera', label: 'Cadera', defaultCode: 'cadera' },
  { key: 'muslo_post', label: 'Muslo post.', defaultCode: 'isquiotibiales_der' },
  { key: 'rodilla', label: 'Rodilla', defaultCode: 'rodilla_der' },
  { key: 'pierna', label: 'Pierna', defaultCode: 'pierna_der' },
  { key: 'tobillo', label: 'Tobillo', defaultCode: 'tobillo_der' },
  { key: 'pie_tarso', label: 'Pie (tarso)', defaultCode: 'pie_tarso_der' },
  { key: 'dedos', label: 'Dedos (metatarso)', defaultCode: 'dedos_der' },
];

export function useAnatomySelection(initialZoneCode: string = 'isquiotibiales_der') {
  const [selectedCode, setSelectedCode] = useState<string>(initialZoneCode);
  const [hoveredCode, setHoveredCode] = useState<string | null>(null);
  const [cameraView, setCameraView] = useState<'frontal' | 'posterior' | 'lateral_izq' | 'lateral_der'>('posterior');

  const selectedZone = useMemo(() => {
    return ANATOMICAL_ZONES[selectedCode] || ANATOMICAL_ZONES.isquiotibiales_der;
  }, [selectedCode]);

  const selectZone = useCallback((code: string) => {
    if (ANATOMICAL_ZONES[code]) {
      setSelectedCode(code);
      if (ANATOMICAL_ZONES[code].viewDefault) {
        setCameraView(ANATOMICAL_ZONES[code].viewDefault);
      }
    }
  }, []);

  return {
    selectedCode,
    selectedZone,
    hoveredCode,
    setHoveredCode,
    cameraView,
    setCameraView,
    selectZone,
  };
}
