-- 20260818_methodology_seed.sql
-- Seed Data for Methodology OS
-- All carga_fisica, carga_cognitiva, oposicion, representatividad values are BETWEEN 1 AND 4
-- intensity_level is BETWEEN 1 AND 5 (existing column)

-- Insert Curriculum Entries
INSERT INTO public.methodology_curriculum (club_id, category_code, category_label, age_min, age_max, philosophy_text)
VALUES 
((SELECT id FROM public.clubs LIMIT 1), 'U6', 'Querubín', 4, 5, 'Primer contacto con el balón, enfocado a la diversión y motricidad básica.'),
((SELECT id FROM public.clubs LIMIT 1), 'U7-U8', 'Prebenjamín', 6, 7, 'Descubrimiento guiado del juego, fomento del regate y relación con el balón.'),
((SELECT id FROM public.clubs LIMIT 1), 'U9-U10', 'Benjamín', 8, 9, 'Iniciación al juego colectivo, fomento del pase y control orientado.'),
((SELECT id FROM public.clubs LIMIT 1), 'U11-U12', 'Alevín', 10, 11, 'Desarrollo de los principios tácticos básicos, juego de posesión y fundamentos técnicos.'),
((SELECT id FROM public.clubs LIMIT 1), 'U13-U14', 'Infantil', 12, 13, 'Introducción al fútbol 11. Estructuración espacial y toma de decisiones.'),
((SELECT id FROM public.clubs LIMIT 1), 'U15-U16', 'Cadete', 14, 15, 'Especialización por posiciones, desarrollo del modelo de juego, transiciones rápidas.'),
((SELECT id FROM public.clubs LIMIT 1), 'U17-U19', 'Juvenil', 16, 18, 'Perfeccionamiento táctico, preparación física específica y mentalidad competitiva.'),
((SELECT id FROM public.clubs LIMIT 1), 'Senior', 'Amateur / Primer Equipo', 19, 99, 'Rendimiento y optimización táctica, estrategia operativa (ABP) e intensidad competitiva.')
ON CONFLICT DO NOTHING;

-- Insert Principles (using U15-U16 curriculum as reference for demo)
WITH curr AS (SELECT id FROM public.methodology_curriculum WHERE category_code = 'U15-U16' AND club_id = (SELECT id FROM public.clubs LIMIT 1) LIMIT 1)
INSERT INTO public.methodology_principles (club_id, curriculum_id, name, game_phase, description)
VALUES 
((SELECT id FROM public.clubs LIMIT 1), (SELECT id FROM curr), 'Presión Alta', 'Defensa', 'Recuperar el balón lo más cerca de la portería rival.'),
((SELECT id FROM public.clubs LIMIT 1), (SELECT id FROM curr), 'Salida de Balón', 'Ataque', 'Progresar desde atrás mediante pases cortos y atraer rivales.'),
((SELECT id FROM public.clubs LIMIT 1), (SELECT id FROM curr), 'Transición Defensiva (Tras Pérdida)', 'Transición Ataque-Defensa', 'Presión instantánea al poseedor del balón (Pressing tras pérdida).')
ON CONFLICT DO NOTHING;

-- Insert Macrocycle
INSERT INTO public.macrocycles (club_id, season_id, name, phase_type, start_date, end_date)
VALUES 
((SELECT id FROM public.clubs LIMIT 1), (SELECT id FROM public.seasons WHERE is_active = true LIMIT 1), 'Macrociclo Competitivo 26/27', 'Competición', '2026-08-01', '2027-06-30')
ON CONFLICT DO NOTHING;

-- Insert Mesocycles
WITH macro AS (SELECT id FROM public.macrocycles WHERE name = 'Macrociclo Competitivo 26/27' AND club_id = (SELECT id FROM public.clubs LIMIT 1) LIMIT 1)
INSERT INTO public.mesocycles (club_id, macrocycle_id, name, focus_phase, start_date, end_date)
VALUES 
((SELECT id FROM public.clubs LIMIT 1), (SELECT id FROM macro), 'Mesociclo 1 - Adquisición', 'Aprendizaje', '2026-08-01', '2026-08-31'),
((SELECT id FROM public.clubs LIMIT 1), (SELECT id FROM macro), 'Mesociclo 2 - Consolidación', 'Consolidación', '2026-09-01', '2026-09-30')
ON CONFLICT DO NOTHING;


-- ─── EJERCICIOS ─────────────────────────────────────────────────────────────
-- carga_fisica, carga_cognitiva, oposicion, representatividad: máximo 4
-- intensity_level: máximo 5

-- U6 (Querubín) - 5 exercises
INSERT INTO public.banco_ejercicios (
    club_id, nombre, tipo, descripcion, correcciones, objetivo_tecnico, objetivo_tactico,
    categoria_edad, age_category, dificultad, duracion_recomendada, min_players, max_players,
    material, variantes, tags, bloque_sesion, carga_fisica, carga_cognitiva, oposicion, representatividad,
    intensity_level, game_phase, drill_structure, espacio, criterios_exito
) VALUES 
((SELECT id FROM public.clubs LIMIT 1), 'El Zoo', 'Juego Lúdico', 'Cada niño con un balón. El entrenador nombra un animal y los niños deben imitarlo conduciendo el balón.', 'Evitar usar las manos, mantener la mirada alta.', ARRAY['Conducción'], ARRAY['Ocupación racional'], ARRAY['querubin'], 'querubin', 1, 10, 6, 15, ARRAY['balones', 'conos'], ARRAY['Sin balón primero'], ARRAY['lúdico', 'conducción'], 'calentamiento', 2, 1, 1, 1, 1, 'general', 'circuit', '20x20m', ARRAY['Todos participan y se divierten']),
((SELECT id FROM public.clubs LIMIT 1), 'Pilla-Pilla con Balón', 'Juego Lúdico', 'Dos "cazadores" sin balón intentan tocar a los demás que conducen su balón. Si te tocan, te quedas congelado.', 'Protección del balón, cambios de dirección.', ARRAY['Conducción', 'Regate'], ARRAY['Percepción'], ARRAY['querubin'], 'querubin', 1, 12, 8, 16, ARRAY['balones', 'petos'], ARRAY['Cazadores con balón'], ARRAY['lúdico', 'percepción'], 'calentamiento', 2, 2, 2, 1, 2, 'general', 'game', '20x20m', ARRAY['No chocar entre compañeros']),
((SELECT id FROM public.clubs LIMIT 1), 'Limpiar la Casa', 'Juego Lúdico', 'Dos equipos divididos por una línea. Hay que lanzar los balones al campo contrario. Gana quien tenga menos.', 'Golpeo con empeine, fuerza.', ARRAY['Pase', 'Golpeo'], ARRAY['Cooperación'], ARRAY['querubin'], 'querubin', 1, 8, 8, 20, ARRAY['muchos balones'], ARRAY['Solo usar pie izquierdo'], ARRAY['golpeo', 'juego'], 'principal', 3, 1, 1, 1, 2, 'general', 'game', '15x15m', ARRAY['Mantener el campo limpio']),
((SELECT id FROM public.clubs LIMIT 1), 'Carrera de Relevos Simple', 'Circuito', 'Conducir hasta un cono, dar la vuelta y pasar el balón al siguiente compañero.', 'Control de la fuerza en la conducción.', ARRAY['Conducción'], ARRAY['Ninguno'], ARRAY['querubin'], 'querubin', 1, 10, 4, 12, ARRAY['balones', 'conos'], ARRAY['Ida pie derecho, vuelta pie izquierdo'], ARRAY['circuito', 'técnica'], 'calentamiento', 2, 1, 1, 1, 2, 'general', 'circuit', '10m', ARRAY['El balón no se escapa más de 1 metro']),
((SELECT id FROM public.clubs LIMIT 1), 'Minipartidos 1v1', 'SSG', 'Partidillos 1 contra 1 en mini-porterías. Muy cortos y rotación constante.', 'Fomentar el atrevimiento, regate y finalización.', ARRAY['Regate', 'Finalización'], ARRAY['1v1 ofensivo'], ARRAY['querubin'], 'querubin', 2, 15, 2, 12, ARRAY['balones', 'miniporterías'], ARRAY['Sin portero, meter gol pasando línea'], ARRAY['1v1', 'finalización'], 'principal', 3, 2, 3, 3, 3, 'attacking_build_up', 'ssg', '10x15m', ARRAY['Atreverse a regatear', 'Tirar a puerta']);

-- U8 (Prebenjamín) - 5 exercises
INSERT INTO public.banco_ejercicios (
    club_id, nombre, tipo, descripcion, correcciones, objetivo_tecnico, objetivo_tactico,
    categoria_edad, age_category, dificultad, duracion_recomendada, min_players, max_players,
    material, variantes, tags, bloque_sesion, carga_fisica, carga_cognitiva, oposicion, representatividad,
    intensity_level, game_phase, drill_structure, espacio, criterios_exito
) VALUES 
((SELECT id FROM public.clubs LIMIT 1), 'El Semáforo', 'Juego Lúdico', 'Conducción libre. Verde: Rápido. Ámbar: Lento. Rojo: Parar pisando el balón.', 'Reacción rápida, balón pegado al pie.', ARRAY['Conducción', 'Control'], ARRAY['Atención'], ARRAY['prebenjamin'], 'prebenjamin', 1, 10, 8, 16, ARRAY['balones'], ARRAY['Cambio de dirección al rojo'], ARRAY['conducción', 'cognitivo'], 'calentamiento', 2, 2, 1, 1, 2, 'general', 'game', '20x20m', ARRAY['Parar rápido al rojo']),
((SELECT id FROM public.clubs LIMIT 1), '1v1 con Dos Porterías', 'SSG', 'Atacante puede marcar en cualquiera de las dos porterías pequeñas. El defensa debe elegir bien cuál cubrir.', 'Uso del engaño (fintas).', ARRAY['Regate'], ARRAY['Toma de decisiones', 'Amplitud'], ARRAY['prebenjamin'], 'prebenjamin', 2, 12, 4, 12, ARRAY['balones', 'conos'], ARRAY['El defensa empieza pasivo'], ARRAY['1v1', 'decisiones'], 'principal', 3, 2, 3, 3, 3, 'attacking_build_up', 'ssg', '15x15m', ARRAY['Buscar la portería vacía']),
((SELECT id FROM public.clubs LIMIT 1), 'Rueda de Pases Simple', 'Analítico', 'Pase al frente y voy a mi derecha (triángulo). Pase y voy donde pasé.', 'Superficie de contacto (interior del pie).', ARRAY['Pase', 'Control'], ARRAY['Movilidad'], ARRAY['prebenjamin'], 'prebenjamin', 1, 10, 3, 9, ARRAY['balones', 'conos'], ARRAY['Control con la otra pierna'], ARRAY['pase', 'técnica'], 'calentamiento', 1, 2, 1, 1, 1, 'general', 'passing_pattern', '5x5m', ARRAY['Pase tenso al pie']),
((SELECT id FROM public.clubs LIMIT 1), '2v2 + Comodín Ofensivo', 'SSG', 'Partido 2 contra 2 con un jugador que siempre ataca. Buscar la ventaja 3v2.', 'Buscar siempre al hombre libre.', ARRAY['Pase'], ARRAY['Superioridad numérica'], ARRAY['prebenjamin'], 'prebenjamin', 2, 15, 5, 10, ARRAY['petos', 'balones'], ARRAY['Limitación de toques al comodín'], ARRAY['2v2', 'superioridad'], 'principal', 3, 3, 3, 3, 3, 'attacking_build_up', 'ssg', '20x20m', ARRAY['Aprovechar el 3v2 para progresar']),
((SELECT id FROM public.clubs LIMIT 1), 'Circuito Técnico-Coordinativo', 'Circuito', 'Zigzag entre picas, salto a vallas y finalización a pequeña portería.', 'Coordinación pies, precisión del tiro.', ARRAY['Conducción', 'Finalización'], ARRAY['Ninguno'], ARRAY['prebenjamin'], 'prebenjamin', 2, 15, 4, 12, ARRAY['picas', 'vallas', 'balones'], ARRAY['Cambiar circuito cada 5 min'], ARRAY['circuito', 'finalización'], 'principal', 2, 1, 1, 1, 2, 'general', 'circuit', '20m', ARRAY['No tirar picas', 'Tiro preciso']);

-- U10 (Benjamín) - 5 exercises
INSERT INTO public.banco_ejercicios (
    club_id, nombre, tipo, descripcion, correcciones, objetivo_tecnico, objetivo_tactico,
    categoria_edad, age_category, dificultad, duracion_recomendada, min_players, max_players,
    material, variantes, tags, bloque_sesion, carga_fisica, carga_cognitiva, oposicion, representatividad,
    intensity_level, game_phase, drill_structure, espacio, criterios_exito
) VALUES 
((SELECT id FROM public.clubs LIMIT 1), 'Rondo 3v1 Clásico', 'Rondo', '3 jugadores mantienen la posesión contra 1 en un cuadrado pequeño.', 'Perfilación corporal, jugar al pie alejado.', ARRAY['Pase', 'Control orientado'], ARRAY['Líneas de pase'], ARRAY['benjamin'], 'benjamin', 2, 12, 4, 12, ARRAY['petos', 'conos'], ARRAY['Máximo 2 toques'], ARRAY['rondo', 'posesión'], 'calentamiento', 2, 2, 2, 2, 2, 'general', 'rondo', '6x6m', ARRAY['Dar al menos 10 pases seguidos']),
((SELECT id FROM public.clubs LIMIT 1), 'Partido 3v3 con Apoyo Lateral', 'SSG', 'Partido 3v3 pero con un comodín en cada banda para centrar. Goles de centro valen doble.', 'Uso de la amplitud, finalización.', ARRAY['Centro', 'Remate'], ARRAY['Amplitud', 'Desdoblamientos'], ARRAY['benjamin'], 'benjamin', 3, 15, 8, 12, ARRAY['petos', 'porterías'], ARRAY['Goles de centro valen doble'], ARRAY['3v3', 'amplitud'], 'principal', 3, 3, 3, 3, 4, 'attacking_build_up', 'ssg', '30x20m', ARRAY['Utilizar las bandas para progresar']),
((SELECT id FROM public.clubs LIMIT 1), 'Duelo 1v1 con Transición', 'SSG', 'Jugador A ataca. Si B roba, hace transición rápida a la otra portería. Si A marca, defiende a C.', 'Agresividad defensiva, velocidad de transición.', ARRAY['Regate', 'Entrada'], ARRAY['Transición defensiva'], ARRAY['benjamin'], 'benjamin', 3, 12, 4, 12, ARRAY['balones', 'porterías pequeñas'], ARRAY['2v1 en transición'], ARRAY['1v1', 'transición'], 'principal', 4, 3, 4, 3, 4, 'transition_def_to_atk', 'ssg', '20x15m', ARRAY['Finalizar rápido tras robo']),
((SELECT id FROM public.clubs LIMIT 1), 'Pase, Control y Tiro', 'Analítico', 'Pase largo, control orientado esquivando pica y tiro a puerta.', 'Orientar el control hacia la portería, no parar el balón.', ARRAY['Control orientado', 'Tiro'], ARRAY['Ninguno'], ARRAY['benjamin'], 'benjamin', 2, 10, 4, 12, ARRAY['picas', 'balones'], ARRAY['Uso de pierna no dominante'], ARRAY['técnica', 'tiro'], 'calentamiento', 2, 1, 1, 1, 2, 'general', 'individual_technical', '25m', ARRAY['Control orientado en un solo toque']),
((SELECT id FROM public.clubs LIMIT 1), 'Partido de 4 Porterías', 'SSG', '3v3. Se puntúa pasando el balón conducido por cualquiera de las 2 mini porterías del rival.', 'Cambio de orientación, buscar espacios libres.', ARRAY['Pase largo'], ARRAY['Cambio de orientación', 'Ocupación de espacios'], ARRAY['benjamin'], 'benjamin', 3, 15, 6, 12, ARRAY['conos', 'petos'], ARRAY['Pase en lugar de conducción'], ARRAY['partido', 'táctica'], 'global', 3, 3, 3, 3, 3, 'attacking_build_up', 'ssg', '25x25m', ARRAY['Circular el balón para mover al rival']);

-- U12 (Alevín) - 5 exercises
INSERT INTO public.banco_ejercicios (
    club_id, nombre, tipo, descripcion, correcciones, objetivo_tecnico, objetivo_tactico,
    categoria_edad, age_category, dificultad, duracion_recomendada, min_players, max_players,
    material, variantes, tags, bloque_sesion, carga_fisica, carga_cognitiva, oposicion, representatividad,
    intensity_level, game_phase, drill_structure, espacio, criterios_exito
) VALUES 
((SELECT id FROM public.clubs LIMIT 1), 'Rondo 4v2', 'Rondo', '4 mantienen contra 2. Buscar pase interior por medio de los dos defensores.', 'Atraer para soltar, ritmo alto de balón.', ARRAY['Pase', 'Control'], ARRAY['Pase interior', 'Tercer hombre'], ARRAY['alevin'], 'alevin', 3, 12, 6, 12, ARRAY['petos'], ARRAY['Obligatorio pase interior para punto extra'], ARRAY['rondo', '4v2'], 'calentamiento', 2, 3, 2, 2, 3, 'attacking_build_up', 'rondo', '8x8m', ARRAY['Conseguir pase entre los dos defensores']),
((SELECT id FROM public.clubs LIMIT 1), 'Juego de Posición 4v4 + 3', 'Posicional', 'Comodines por fuera y uno dentro. Posesión con objetivo de ir de un lado a otro.', 'Perfilación corporal, no estar en la misma línea de pase.', ARRAY['Pase corto', 'Pase largo'], ARRAY['Conservación', 'Progresión'], ARRAY['alevin'], 'alevin', 4, 15, 11, 15, ARRAY['petos', 'conos'], ARRAY['Límite de toques'], ARRAY['posicional', 'juego de posición'], 'principal', 3, 4, 3, 3, 4, 'attacking_build_up', 'positional_game', '25x25m', ARRAY['Encontrar al comodín interior']),
((SELECT id FROM public.clubs LIMIT 1), 'Salida de Balón 4v3', 'Táctico', 'Línea de 4 defensores saca balón contra 3 atacantes que presionan. Objetivo: pasar mediocampo.', 'Amplitud de laterales, mediocentro ofreciendo apoyo.', ARRAY['Pase', 'Conducción'], ARRAY['Salida de balón', 'Superar línea de presión'], ARRAY['alevin'], 'alevin', 3, 15, 7, 14, ARRAY['porterías pequeñas'], ARRAY['Añadir un mediocentro'], ARRAY['salida de balón', 'táctica'], 'principal', 3, 3, 3, 4, 3, 'attacking_build_up', 'ssg', '30x30m', ARRAY['Superar la primera línea de presión']),
((SELECT id FROM public.clubs LIMIT 1), 'Transición 3v2 → 2v1', 'SSG', '3 atacan a 2. Al finalizar, los 2 defensas salen rápido en 2v1 contra el último pasador.', 'Velocidad en el ataque, replegamiento rápido.', ARRAY['Pase al hueco', 'Definición'], ARRAY['Transición rápida', 'Temporización defensiva'], ARRAY['alevin'], 'alevin', 4, 15, 6, 15, ARRAY['porterías'], ARRAY['Obligatorio finalizar en 10 seg'], ARRAY['transición', 'contraataque'], 'principal', 4, 3, 3, 3, 4, 'transition_atk_to_def', 'ssg', '40x30m', ARRAY['No dejar que se arme la defensa']),
((SELECT id FROM public.clubs LIMIT 1), 'Rueda de Pases con Finalización', 'Analítico', 'Circulación: central → lateral → extremo → centro al delantero para remate.', 'Timing del desmarque, tensión del pase.', ARRAY['Centro', 'Remate', 'Pase'], ARRAY['Desmarques de ruptura'], ARRAY['alevin'], 'alevin', 2, 10, 6, 15, ARRAY['conos', 'balones'], ARRAY['Intercambio de posiciones automático'], ARRAY['rueda pases', 'finalización'], 'calentamiento', 2, 2, 1, 2, 2, 'attacking_build_up', 'passing_pattern', 'Medio campo', ARRAY['Remate al primer toque tras centro']);

-- U14 (Infantil) - 5 exercises
INSERT INTO public.banco_ejercicios (
    club_id, nombre, tipo, descripcion, correcciones, objetivo_tecnico, objetivo_tactico,
    categoria_edad, age_category, dificultad, duracion_recomendada, min_players, max_players,
    material, variantes, tags, bloque_sesion, carga_fisica, carga_cognitiva, oposicion, representatividad,
    intensity_level, game_phase, drill_structure, espacio, criterios_exito
) VALUES 
((SELECT id FROM public.clubs LIMIT 1), 'Posicional 6v4 + Portero', 'Posicional', 'Los 6 (línea defensiva + 2 MC) salen jugando ante 4 presionando. Objetivo: dar pase a comodín en campo contrario.', 'Movilidad de los MC, atraer presión para saltar línea.', ARRAY['Pase', 'Control orientado'], ARRAY['Salida lavolpiana', 'Tercer hombre'], ARRAY['infantil'], 'infantil', 4, 18, 11, 15, ARRAY['petos', 'portería'], ARRAY['Comodín debe recibir al espacio'], ARRAY['juego de posición', 'salida balón'], 'principal', 3, 4, 3, 4, 4, 'attacking_build_up', 'positional_game', 'Medio campo', ARRAY['Superar la primera línea de presión 5 veces']),
((SELECT id FROM public.clubs LIMIT 1), 'Oleadas de Presión 3v3', 'Táctico', 'El equipo A inicia posesión, el equipo B sale a presionar en sprint. Si roba, ataca. Al salir el balón, nuevo equipo presiona.', 'Coordinación en la presión, basculación.', ARRAY['Interceptación', 'Entrada'], ARRAY['Pressing alto', 'Basculación'], ARRAY['infantil'], 'infantil', 4, 15, 9, 15, ARRAY['balones', 'porterías pequeñas'], ARRAY['Obligatorio robar en < 6 seg'], ARRAY['presión', 'táctica'], 'principal', 4, 3, 4, 3, 5, 'defending_high_press', 'ssg', '30x20m', ARRAY['Robar balón en zona alta']),
((SELECT id FROM public.clubs LIMIT 1), 'Rondo Móvil 5v2 (2 zonas)', 'Rondo', 'Mantienen 5 contra 2. A los 5 pases, deben transferir el balón a la otra zona y todos se mueven.', 'Velocidad de circulación, reacción a la transición de zona.', ARRAY['Pase corto', 'Pase medio'], ARRAY['Conservación', 'Movilidad'], ARRAY['infantil'], 'infantil', 3, 12, 7, 14, ARRAY['conos', 'petos'], ARRAY['Defensas se cambian cada robo'], ARRAY['rondo', 'posesión'], 'calentamiento', 3, 3, 2, 2, 3, 'attacking_build_up', 'rondo', '15x30m', ARRAY['Conseguir cambiar de zona 3 veces seguidas']),
((SELECT id FROM public.clubs LIMIT 1), 'Finalización tras Centro Lateral', 'Táctico', 'Creación de jugada por banda, 2v1 al lateral, centro al área donde esperan 2 atacantes vs 2 centrales.', 'Timing de remate, ocupación de zonas de remate (1º palo, 2º palo, rechace).', ARRAY['Centro', 'Remate de cabeza', 'Volea'], ARRAY['Desdoblamiento', 'Ocupación área'], ARRAY['infantil'], 'infantil', 3, 15, 8, 16, ARRAY['portería grande'], ARRAY['Añadir mediocentro llegador'], ARRAY['finalización', 'bandas'], 'principal', 2, 3, 3, 4, 3, 'attacking_finishing', 'passing_pattern', 'Zona ataque', ARRAY['Un rematador ataca siempre el primer palo']),
((SELECT id FROM public.clubs LIMIT 1), 'Partido Modificado: Zonas de Riesgo', 'SSG', 'Pérdida en zona de creación (zona central marcada) vale doble para el rival si marcan en transición.', 'Seguridad en el pase, no arriesgar en zonas prohibidas.', ARRAY['Pase de seguridad'], ARRAY['Gestión de riesgo', 'Seguridad defensiva'], ARRAY['infantil'], 'infantil', 4, 20, 14, 22, ARRAY['conos para marcar zonas'], ARRAY['Solo 2 toques en zona de riesgo'], ARRAY['partido', 'táctica'], 'global', 3, 4, 4, 4, 4, 'defending_mid_block', 'ssg', 'Campo entero', ARRAY['0 pérdidas en zona de riesgo']);

-- U16 (Cadete) - 5 exercises
INSERT INTO public.banco_ejercicios (
    club_id, nombre, tipo, descripcion, correcciones, objetivo_tecnico, objetivo_tactico,
    categoria_edad, age_category, dificultad, duracion_recomendada, min_players, max_players,
    material, variantes, tags, bloque_sesion, carga_fisica, carga_cognitiva, oposicion, representatividad,
    intensity_level, game_phase, drill_structure, espacio, criterios_exito
) VALUES 
((SELECT id FROM public.clubs LIMIT 1), 'Juego de Posición 7v7 + 3', 'Posicional', 'Posesión intensa. 3 comodines (2 por fuera, 1 por dentro). Foco en encontrar el tercer hombre.', 'Uso del comodín interior, perfilación ofensiva.', ARRAY['Pase tenso'], ARRAY['Tercer hombre', 'Juego interior'], ARRAY['cadete'], 'cadete', 5, 20, 17, 20, ARRAY['petos'], ARRAY['Si pase a comodín interior, libre toques'], ARRAY['juego posición', 'cadete'], 'principal', 4, 4, 4, 4, 4, 'attacking_build_up', 'positional_game', '40x40m', ARRAY['Encontrar al comodín interior 5 veces']),
((SELECT id FROM public.clubs LIMIT 1), 'Transición Ofensiva Rápida 4v3', 'SSG', 'El entrenador mete balón a zona defensiva. Central despeja a MC, que lanza rápido a 3 delanteros contra 3 defensas.', 'Pase profundo inmediato tras recuperación.', ARRAY['Pase en profundidad'], ARRAY['Transición rápida', 'Contraataque'], ARRAY['cadete'], 'cadete', 4, 15, 8, 16, ARRAY['balones', 'portería'], ARRAY['Limite de tiempo: 8 segundos para finalizar'], ARRAY['contraataque', 'transición'], 'principal', 4, 3, 4, 3, 5, 'transition_def_to_atk', 'passing_pattern', 'Medio campo', ARRAY['Finalizar antes de 8 segundos']),
((SELECT id FROM public.clubs LIMIT 1), 'Automatismo Defensivo: Basculación Línea 4', 'Táctico', 'Línea de 4 defensas más pivote. El rival mueve el balón de lado a lado. Los defensas bascularán sin perder distancias.', 'Distancia entre centrales, laterales cerrando, perfil corporal.', ARRAY['Despeje'], ARRAY['Basculación', 'Cobertura'], ARRAY['cadete'], 'cadete', 4, 15, 10, 15, ARRAY['conos para referencia'], ARRAY['Mover balón más rápido'], ARRAY['defensa', 'línea 4'], 'principal', 2, 4, 2, 4, 3, 'defending_mid_block', 'positional_game', 'Ancho de campo', ARRAY['No perder la estructura de la línea']),
((SELECT id FROM public.clubs LIMIT 1), 'Rondo de Presión 6v2 Intenso', 'Rondo', '2 en el medio presionan a 6 a alta intensidad. Robo o 10 pases cambia los del medio.', 'Presión conjunta, cerrar línea de pase dividiendo.', ARRAY['Pase al primer toque'], ARRAY['Pressing', 'Cerrar líneas de pase'], ARRAY['cadete'], 'cadete', 3, 10, 8, 10, ARRAY['petos'], ARRAY['1 toque obligatorio'], ARRAY['rondo', 'presión'], 'calentamiento', 4, 3, 3, 2, 4, 'defending_high_press', 'rondo', '10x10m', ARRAY['Robar en menos de 5 pases']),
((SELECT id FROM public.clubs LIMIT 1), 'Partido Táctico: Defensa en Bloque Medio', 'SSG', 'El equipo defensor espera en bloque medio. Si el rival entra, se dispara la presión coordinada.', 'Temporización, saltos a la presión coordinados.', ARRAY['Interceptación'], ARRAY['Bloque medio', 'Presión tras gatillo'], ARRAY['cadete'], 'cadete', 5, 25, 22, 22, ARRAY['campo completo'], ARRAY['Puntos dobles por robar en mediocampo'], ARRAY['partido', 'táctica', '11v11'], 'global', 4, 4, 4, 4, 4, 'defending_mid_block', 'positional_game', 'Campo entero', ARRAY['El rival no progresa por el centro']);

-- U19 / Senior (Juvenil/Amateur) - 10 exercises
INSERT INTO public.banco_ejercicios (
    club_id, nombre, tipo, descripcion, correcciones, objetivo_tecnico, objetivo_tactico,
    categoria_edad, age_category, dificultad, duracion_recomendada, min_players, max_players,
    material, variantes, tags, bloque_sesion, carga_fisica, carga_cognitiva, oposicion, representatividad,
    intensity_level, game_phase, drill_structure, espacio, criterios_exito
) VALUES 
((SELECT id FROM public.clubs LIMIT 1), 'Salida de Balón vs Presión Alta 11v11', 'SSG', 'Equipo A saca de puerta buscando conectar con MC. Equipo B presiona al hombre.', 'Uso del tercer hombre, lateral atrayendo, central fijando.', ARRAY['Pase', 'Control'], ARRAY['Salida de balón', 'Superar presión alta'], ARRAY['juvenil', 'senior'], 'senior', 5, 20, 22, 22, ARRAY['ninguno'], ARRAY['Punto extra si Equipo A llega a mediocampo con balón controlado'], ARRAY['salida balón', '11v11', 'táctica'], 'global', 4, 4, 4, 4, 4, 'attacking_build_up', 'positional_game', 'Campo entero', ARRAY['Superar presión 3 veces seguidas sin pérdida']),
((SELECT id FROM public.clubs LIMIT 1), 'ABP: Córner a Favor (Estrategia)', 'Analítico', 'Ensayo de 3 jugadas de córner (1º palo, 2º palo, corto). Repetición analítica y luego con oposición activa.', 'Timing de desmarque, precisión del lanzador, bloqueos.', ARRAY['Golpeo balón parado', 'Remate de cabeza'], ARRAY['Bloqueos', 'Desmarques'], ARRAY['juvenil', 'senior'], 'senior', 3, 15, 11, 20, ARRAY['balones', 'portería'], ARRAY['Añadir contraataque rival si despejan'], ARRAY['abp', 'córner', 'estrategia'], 'principal', 1, 4, 3, 4, 2, 'set_pieces', 'passing_pattern', 'Área penal', ARRAY['Rematar el 80% de los centros']),
((SELECT id FROM public.clubs LIMIT 1), 'Pressing tras Pérdida: 8v8', 'SSG', 'Posesión 8v8. El equipo que pierde el balón tiene 5 segundos para robar. Si no lo hace, repliega a zona marcada.', 'Reacción inmediata a la pérdida, cerrar primeros pases.', ARRAY['Entrada'], ARRAY['Pressing tras pérdida', 'Cambio de chip'], ARRAY['juvenil', 'senior'], 'senior', 5, 18, 16, 20, ARRAY['petos', 'zonas delimitadas'], ARRAY['Si se roba en 5s y marca, vale x3'], ARRAY['transición', 'pressing'], 'principal', 4, 4, 4, 4, 5, 'transition_atk_to_def', 'positional_game', 'Medio campo', ARRAY['Robar en menos de 5 segundos']),
((SELECT id FROM public.clubs LIMIT 1), 'Ataque Posicional: Hundir Bloque Bajo', 'Táctico', 'Ataque 10v9. El equipo defensor juega en 5-4-1 muy replegado. Objetivo: mover rápido para abrir huecos.', 'Velocidad de circulación, uso de los carrileros, tiros lejanos.', ARRAY['Pase tenso', 'Centro'], ARRAY['Desequilibrio', 'Ataque a bloque bajo'], ARRAY['juvenil', 'senior'], 'senior', 5, 20, 19, 22, ARRAY['balones'], ARRAY['Límite de toques en el centro del campo'], ARRAY['ataque posicional', 'bloque bajo'], 'principal', 3, 4, 4, 4, 4, 'attacking_build_up', 'positional_game', '3/4 campo', ARRAY['Generar tiro claro al menos cada 2 minutos']),
((SELECT id FROM public.clubs LIMIT 1), 'Rueda Alta Intensidad (Calentamiento Senior)', 'Analítico', 'Pase fuerte, dejada de cara, balón largo al espacio y finalización a puerta.', 'Tensión del pase, timing perfecto del desmarque.', ARRAY['Pase largo', 'Dejada de cara'], ARRAY['Tercer hombre analítico'], ARRAY['juvenil', 'senior'], 'senior', 4, 12, 10, 15, ARRAY['conos', 'picas', 'balones'], ARRAY['A un solo toque todo'], ARRAY['calentamiento', 'técnica', 'senior'], 'calentamiento', 3, 3, 1, 2, 3, 'general', 'passing_pattern', '40m', ARRAY['Ningún pase debe ir botando']),
((SELECT id FROM public.clubs LIMIT 1), 'Juego de Posición 5v5+5', 'Posicional', '5 por fuera, 5 dentro y 5 defensores. Mantener posesión jugando siempre por dentro para conectar con los de fuera.', 'Juego interior, visión periférica.', ARRAY['Pase oculto', 'Control orientado'], ARRAY['Juego interior', 'Fijar y descargar'], ARRAY['juvenil', 'senior'], 'senior', 5, 15, 15, 15, ARRAY['petos', 'conos'], ARRAY['Defensa que roba pasa a atacar al instante'], ARRAY['juego de posición', 'posesión'], 'principal', 4, 4, 4, 3, 4, 'attacking_build_up', 'positional_game', '30x30m', ARRAY['Jugar por dentro antes de jugar por fuera']),
((SELECT id FROM public.clubs LIMIT 1), 'ABP: Falta Lateral', 'Analítico', 'Ensayo de falta lateral. Variantes: tiro directo o centro a zonas asignadas. Trabajo de los rechaces.', 'Posición corporal para rematar, segunda jugada.', ARRAY['Tiro libre', 'Remate'], ARRAY['Ocupación racional del área'], ARRAY['juvenil', 'senior'], 'senior', 3, 15, 11, 20, ARRAY['balones'], ARRAY['Defensa en zona vs defensa al hombre'], ARRAY['abp', 'falta'], 'principal', 1, 4, 3, 4, 2, 'set_pieces', 'passing_pattern', 'Área', ARRAY['Ganar la segunda jugada siempre']),
((SELECT id FROM public.clubs LIMIT 1), 'Duelos 1v1, 2v2 y 3v3 Continuos', 'SSG', 'Se juega un 1v1, al finalizar entra un jugador de cada equipo → 2v2, luego 3v3. Alta intensidad.', 'Ganar el duelo individual, transiciones muy rápidas.', ARRAY['Regate', 'Entrada', 'Tiro'], ARRAY['Duelo', 'Coberturas en 2v2'], ARRAY['juvenil', 'senior'], 'senior', 4, 15, 8, 16, ARRAY['balones', 'porterías'], ARRAY['Obligatorio finalizar la jugada rápido'], ARRAY['duelos', 'físico', 'alta intensidad'], 'principal', 4, 3, 4, 2, 5, 'general', 'ssg', '30x20m', ARRAY['Ganar el 60% de los duelos 1v1']),
((SELECT id FROM public.clubs LIMIT 1), 'Circuito Físico-Técnico Intermitente', 'Circuito', 'Posta 1: salto vallas + cabezazo. Posta 2: Sprint 20m + tiro. Posta 3: zigzag + pase tenso.', 'Mantener precisión con fatiga alta.', ARRAY['Pase', 'Tiro', 'Remate cabeza'], ARRAY['Ninguno'], ARRAY['juvenil', 'senior'], 'senior', 3, 20, 10, 20, ARRAY['material diverso', 'balones'], ARRAY['Aumentar distancia del sprint'], ARRAY['físico', 'resistencia', 'técnica'], 'principal', 4, 2, 1, 1, 5, 'general', 'circuit', 'Medio campo', ARRAY['No fallar el gesto técnico por fatiga']),
((SELECT id FROM public.clubs LIMIT 1), 'Partido Modificado: Condicionantes de Zona', 'SSG', 'Campo dividido en 3 zonas. Prohibido dar más de 3 pases en zona de inicio, obligatorio pasar por el centro para atacar.', 'Velocidad en salida, obligar a jugar por dentro.', ARRAY['Pase', 'Control'], ARRAY['Verticalidad', 'Uso del pasillo central'], ARRAY['juvenil', 'senior'], 'senior', 5, 25, 22, 22, ARRAY['conos para marcar zonas'], ARRAY['Gol tras recuperación en zona alta vale doble'], ARRAY['partido modificado', 'táctica global'], 'global', 4, 4, 4, 4, 4, 'general', 'ssg', 'Campo entero', ARRAY['Cumplir las reglas de zona']);
